/* ============================================================
   核心词例句库 —— 覆盖无法拆解的基础词
   全部为专升本考试语域（书信/议论/校园/社会），可直接用于写作
   ============================================================ */
const CORE_SENTS = [
["abandon","They had to abandon the plan because of the heavy rain.","因为大雨，他们不得不放弃这个计划。"],
["able","She is able to finish the task on her own.","她能够独自完成这项任务。"],
["absence","In the absence of evidence, we cannot blame him.","在缺乏证据的情况下，我们不能责怪他。"],
["absolute","I have absolute confidence in my team.","我对我的团队有绝对的信心。"],
["absorb","Plants absorb water through their roots.","植物通过根部吸收水分。"],
["abstract","This concept is too abstract for beginners.","这个概念对初学者来说太抽象了。"],
["accent","He speaks English with a slight accent.","他说英语带一点口音。"],
["accident","The accident was caused by careless driving.","这起事故是由粗心驾驶造成的。"],
["accompany","Her mother accompanied her to the hospital.","她母亲陪她去了医院。"],
["accomplish","We accomplished the task ahead of time.","我们提前完成了任务。"],
["according","According to the report, sales have increased.","根据报告，销售额增加了。"],
["account","You should open a bank account first.","你应该先开一个银行账户。"],
["accurate","Please give me the accurate figures.","请给我准确的数字。"],
["accuse","He was accused of stealing the money.","他被指控偷了钱。"],
["acid","Acid rain does great harm to forests.","酸雨对森林危害极大。"],
["across","There is a bank across the street.","街对面有一家银行。"],
["act","We must act now before it is too late.","我们必须现在行动，以免太迟。"],
["actual","The actual cost was higher than expected.","实际费用比预期的高。"],
["adapt","It takes time to adapt to a new environment.","适应新环境需要时间。"],
["add","Please add your name to the list.","请把你的名字加到名单上。"],
["admire","I admire his courage and honesty.","我钦佩他的勇气和诚实。"],
["admit","He admitted making a mistake.","他承认犯了错误。"],
["adopt","The school adopted a new teaching method.","学校采用了一种新的教学方法。"],
["advance","Science has advanced rapidly in recent years.","近年来科学发展迅速。"],
["advise","The teacher advised me to read more books.","老师建议我多读书。"],
["affair","This is a private affair.","这是私事。"],
["afford","We cannot afford to waste any more time.","我们浪费不起更多时间了。"],
["afraid","I am afraid of making mistakes in public.","我害怕在众人面前犯错。"],
["age","Children of this age learn very quickly.","这个年龄的孩子学得很快。"],
["agree","I quite agree with your opinion.","我很同意你的看法。"],
["aim","Our aim is to improve service quality.","我们的目标是提高服务质量。"],
["alarm","The fire alarm went off suddenly.","火警警报突然响了。"],
["allow","My parents do not allow me to stay up late.","父母不允许我熬夜。"],
["almost","I almost missed the last bus.","我差点错过了末班车。"],
["alone","She lives alone but never feels lonely.","她独自生活，但从不觉得孤独。"],
["along","We walked along the river for an hour.","我们沿着河边走了一小时。"],
["already","He had already left when I arrived.","我到的时候他已经走了。"],
["although","Although it was raining, we went out.","尽管下着雨，我们还是出去了。"],
["always","She always arrives on time.","她总是准时到达。"],
["amount","A large amount of money was spent on it.","大量的钱花在了这上面。"],
["ancient","Ancient China made great contributions to the world.","古代中国对世界作出了巨大贡献。"],
["anger","He could not control his anger.","他无法控制自己的愤怒。"],
["announce","The school announced the exam results yesterday.","学校昨天公布了考试成绩。"],
["answer","Please answer the question in English.","请用英语回答问题。"],
["anxious","She was anxious about the coming exam.","她对即将到来的考试感到焦虑。"],
["apply","I am writing to apply for the position.","我写信申请这个职位。"],
["appreciate","I would appreciate it if you could reply soon.","如果您能尽快回复，我将不胜感激。"],
["approach","We need a new approach to this problem.","我们需要用新方法解决这个问题。"],
["approve","The plan was approved by the committee.","该计划得到了委员会的批准。"],
["area","This area is famous for its scenery.","这个地区以风景闻名。"],
["argue","They argued about the plan for hours.","他们就这个计划争论了几个小时。"],
["arrange","I have arranged a meeting for tomorrow.","我已安排明天开会。"],
["arrive","We arrived at the airport on time.","我们准时到达机场。"],
["article","I read an interesting article this morning.","今天早上我读了一篇有趣的文章。"],
["ashamed","He felt ashamed of his behaviour.","他为自己的行为感到羞愧。"],
["aside","Put aside some money for emergencies.","留出一些钱以备急用。"],
["ask","May I ask you a question?","我可以问你一个问题吗？"],
["asleep","He fell asleep during the lecture.","他在讲座中睡着了。"],
["assume","We cannot assume that he will agree.","我们不能假定他会同意。"],
["attach","Please attach your photo to the form.","请将照片贴在表格上。"],
["attack","The village was attacked at midnight.","村庄在半夜遭到袭击。"],
["attempt","He made an attempt to solve the problem.","他试图解决这个问题。"],
["attend","All students are required to attend the meeting.","所有学生都必须参加会议。"],
["attract","The city attracts thousands of tourists each year.","这座城市每年吸引成千上万游客。"],
["audience","The audience gave him a warm welcome.","观众给了他热烈的欢迎。"],
["author","He is the author of several famous novels.","他是几部名著的作者。"],
["available","The book is available in the library.","这本书图书馆有。"],
["average","The average score of our class is 85.","我们班的平均分是85。"],
["avoid","We left early to avoid the traffic jam.","我们提早出发以避开交通拥堵。"],
["award","She won the first award in the competition.","她在比赛中获得一等奖。"],
["aware","Few people are aware of the danger.","很少有人意识到这种危险。"],
["balance","It is hard to balance study and work.","很难平衡学习和工作。"],
["base","The theory is based on careful research.","这一理论基于细致的研究。"],
["battle","They fought a hard battle and won.","他们打了一场硬仗并获胜。"],
["bear","I cannot bear the noise any longer.","我再也忍受不了这噪音了。"],
["beat","Our team beat theirs by two goals.","我们队以两球战胜了他们队。"],
["become","He has become a well-known writer.","他已成为一位著名作家。"],
["begin","Let us begin with the first question.","我们从第一个问题开始吧。"],
["behave","The children behaved very well today.","孩子们今天表现很好。"],
["belong","This book belongs to the library.","这本书属于图书馆。"],
["below","The temperature dropped below zero.","气温降到零度以下。"],
["beside","She sat beside her mother quietly.","她安静地坐在母亲旁边。"],
["besides","Besides English, he also speaks French.","除了英语，他还会说法语。"],
["beyond","The problem is beyond my ability.","这个问题超出了我的能力。"],
["blame","You should not blame others for your mistakes.","你不该把自己的错误归咎于他人。"],
["blank","Fill in the blanks with proper words.","用适当的词填空。"],
["blow","The wind blew the door open.","风把门吹开了。"],
["boil","Water boils at one hundred degrees.","水在一百度时沸腾。"],
["border","The town lies on the border of two provinces.","这个镇位于两省交界处。"],
["borrow","May I borrow your dictionary?","我可以借你的词典吗？"],
["bother","Sorry to bother you, but I need help.","抱歉打扰你，但我需要帮助。"],
["brief","He gave us a brief introduction.","他给我们做了简短的介绍。"],
["bright","The future looks bright for young people.","年轻人的前景看起来光明。"],
["bring","Please bring your textbook tomorrow.","请明天把课本带来。"],
["broad","He has a broad knowledge of history.","他对历史有广博的知识。"],
["budget","The project went over budget.","这个项目超出了预算。"],
["burn","The fire burned for three hours.","大火燃烧了三个小时。"],
["burst","She burst into tears at the news.","听到这个消息她突然大哭起来。"],
["bury","The village was buried under the snow.","村庄被埋在雪下。"],
["busy","I am busy preparing for the exam.","我正忙着准备考试。"],
["calculate","Let me calculate the total cost.","让我计算一下总费用。"],
["cancel","The meeting was cancelled because of the storm.","会议因暴风雨取消了。"],
["capital","Beijing is the capital of China.","北京是中国的首都。"],
["capture","The photo captured a beautiful moment.","这张照片捕捉了一个美好瞬间。"],
["carry","She carried a heavy bag on her back.","她背着一个沉重的包。"],
["case","In that case, we should change our plan.","那样的话，我们该改变计划。"],
["catch","I ran fast to catch the early bus.","我跑得很快去赶早班车。"],
["cause","Careless driving causes many accidents.","粗心驾驶造成许多事故。"],
["celebrate","We celebrated her birthday last night.","我们昨晚为她庆祝了生日。"],
["certain","I am certain that he will come.","我确信他会来。"],
["challenge","Learning a new language is a challenge.","学习新语言是一项挑战。"],
["chance","This is a good chance to practise English.","这是练习英语的好机会。"],
["charge","They charge ten yuan for delivery.","他们收取十元配送费。"],
["check","Please check your answers carefully.","请仔细检查你的答案。"],
["choose","You may choose either of the two.","这两个你可以任选一个。"],
["claim","He claimed that he was innocent.","他声称自己是无辜的。"],
["clear","The instructions are very clear.","说明非常清楚。"],
["climb","They climbed the mountain in four hours.","他们用四小时爬上了山。"],
["close","The shop closes at nine every evening.","这家店每晚九点关门。"],
["collect","She collects stamps as a hobby.","她把集邮作为爱好。"],
["combine","We should combine theory with practice.","我们应该把理论与实践结合起来。"],
["comfort","The news brought comfort to the family.","这个消息给这家人带来了安慰。"],
["command","He has a good command of English.","他精通英语。"],
["comment","She made no comment on the matter.","她对此事未作评论。"],
["compare","Compared with last year, sales have risen.","与去年相比，销售额上升了。"],
["compete","Many students compete for the scholarship.","许多学生争夺奖学金。"],
["complain","Customers complained about the poor service.","顾客抱怨服务差。"],
["complete","It took a month to complete the project.","完成这个项目花了一个月。"],
["concern","Health is a matter of great concern.","健康是十分令人关注的问题。"],
["conclude","We concluded that the plan was workable.","我们得出结论认为该计划可行。"],
["condition","Under no condition should you give up.","无论如何你都不应放弃。"],
["conduct","They conducted a survey among students.","他们在学生中开展了一项调查。"],
["confirm","Please confirm your booking by email.","请通过邮件确认你的预订。"],
["confuse","The two words are easy to confuse.","这两个词容易混淆。"],
["connect","The bridge connects the two cities.","这座桥连接两座城市。"],
["consider","You should consider the problem carefully.","你应该仔细考虑这个问题。"],
["consist","The team consists of ten members.","这个团队由十名成员组成。"],
["contact","Please keep in contact with me.","请与我保持联系。"],
["contain","This drink contains no sugar.","这种饮料不含糖。"],
["continue","The rain continued all night.","雨下了一整夜。"],
["contribute","Everyone should contribute to society.","每个人都应为社会作贡献。"],
["control","He could not control his emotions.","他无法控制自己的情绪。"],
["convenient","Online shopping is very convenient.","网上购物非常方便。"],
["cover","The article covers many important topics.","这篇文章涵盖许多重要话题。"],
["create","Technology creates new jobs every year.","科技每年创造新的工作岗位。"],
["credit","He deserves credit for his hard work.","他的努力值得称赞。"],
["crowd","A large crowd gathered in the square.","广场上聚集了一大群人。"],
["cure","There is no cure for this disease yet.","这种病目前还没有治愈方法。"],
["damage","The storm caused serious damage.","暴风雨造成了严重损失。"],
["dare","How dare you say such a thing?","你怎么敢说这种话？"],
["deal","We must deal with the problem at once.","我们必须立即处理这个问题。"],
["decide","She decided to study abroad.","她决定出国留学。"],
["declare","The government declared a state of emergency.","政府宣布进入紧急状态。"],
["decline","Sales have declined since last year.","自去年以来销售额下降了。"],
["decrease","The number of smokers has decreased.","吸烟者的数量减少了。"],
["defend","He defended his opinion firmly.","他坚定地捍卫自己的观点。"],
["define","It is hard to define happiness.","很难给幸福下定义。"],
["delay","The flight was delayed by two hours.","航班延误了两小时。"],
["deliver","The package was delivered this morning.","包裹今天早上送到了。"],
["demand","This job demands great patience.","这份工作需要极大的耐心。"],
["deny","He denied taking the money.","他否认拿了钱。"],
["depend","Success depends on hard work.","成功取决于努力。"],
["describe","Please describe the picture in your own words.","请用自己的话描述这幅图。"],
["deserve","She deserves the prize for her effort.","她的努力值得这个奖。"],
["design","The building was designed by a famous architect.","这栋楼由一位著名建筑师设计。"],
["desire","People have a strong desire for real experiences.","人们对真实体验有强烈渴望。"],
["destroy","The fire destroyed the whole building.","大火摧毁了整栋楼。"],
["determine","He was determined to succeed.","他决心要成功。"],
["develop","China has developed rapidly.","中国发展迅速。"],
["devote","She devoted her life to teaching.","她一生致力于教育事业。"],
["differ","Opinions differ on this question.","对这个问题看法不一。"],
["discover","Scientists discovered a new species.","科学家发现了一个新物种。"],
["discuss","We discussed the plan for two hours.","我们讨论这个计划两小时。"],
["divide","Let us divide the work among us.","我们把工作分一下吧。"],
["doubt","I doubt whether he will come.","我怀疑他是否会来。"],
["due","The report is due next Monday.","报告下周一到期。"],
["earn","He earns a living by teaching.","他靠教书谋生。"],
["effect","Exercise has a positive effect on health.","锻炼对健康有积极影响。"],
["effort","Success comes from constant effort.","成功来自不懈的努力。"],
["employ","The company employs over 500 workers.","这家公司雇用五百多名工人。"],
["encourage","My teacher encouraged me to keep going.","老师鼓励我坚持下去。"],
["enjoy","I enjoy reading before going to bed.","我喜欢睡前阅读。"],
["ensure","Please ensure that the door is locked.","请确保门已锁好。"],
["enter","He entered the room without knocking.","他没敲门就进了房间。"],
["equal","All people are equal before the law.","法律面前人人平等。"],
["escape","They escaped from the fire safely.","他们安全逃离了火场。"],
["establish","The school was established in 1950.","这所学校建于1950年。"],
["estimate","It is estimated that the cost will double.","据估计费用将翻倍。"],
["exchange","They work in guesthouses in exchange for a room.","他们在旅馆工作以换取住处。"],
["exist","Such problems still exist today.","这类问题今天仍然存在。"],
["expect","We expect the price to fall next month.","我们预计下月价格会下降。"],
["experience","She has rich experience in teaching.","她有丰富的教学经验。"],
["explain","Could you explain this rule to me?","你能给我解释这条规则吗？"],
["explore","Young people spend a year exploring rural areas.","年轻人花一年时间探索乡村地区。"],
["express","It is hard to express my feelings in words.","很难用言语表达我的感受。"],
["fail","He failed the exam because of carelessness.","他因粗心考试不及格。"],
["familiar","This song sounds familiar to me.","这首歌听起来很耳熟。"],
["favour","Could you do me a favour?","你能帮我个忙吗？"],
["fear","There is no need to fear failure.","没必要害怕失败。"],
["feed","She feeds the birds every morning.","她每天早上喂鸟。"],
["figure","I cannot figure out what he means.","我搞不懂他是什么意思。"],
["fill","Fill in the form with a black pen.","用黑笔填表。"],
["focus","We should focus on the main problem.","我们应该关注主要问题。"],
["follow","Please follow the instructions carefully.","请仔细遵照说明。"],
["force","Nobody can force you to do it.","没人能强迫你做这件事。"],
["forgive","Please forgive me for being late.","请原谅我迟到。"],
["form","Water can form ice at low temperature.","水在低温下会结成冰。"],
["found","The company was founded in 1998.","这家公司成立于1998年。"],
["gain","She gained a lot from the experience.","她从这段经历中收获很多。"],
["gather","People gathered in the square to celebrate.","人们聚集在广场上庆祝。"],
["generation","Each generation faces its own problems.","每一代人都面临自己的问题。"],
["glance","He glanced at his watch and left.","他瞥了一眼手表就走了。"],
["guard","The soldiers guarded the gate day and night.","士兵们日夜守卫大门。"],
["guess","I guess he will not come today.","我猜他今天不会来。"],
["handle","She handled the situation very well.","她把局面处理得很好。"],
["hang","Please hang your coat on the hook.","请把外套挂在钩子上。"],
["harm","Smoking does great harm to health.","吸烟对健康危害很大。"],
["hate","I hate wasting time on meaningless things.","我讨厌把时间浪费在无意义的事上。"],
["hire","The company hired ten new workers.","公司雇用了十名新工人。"],
["hold","The meeting will be held on Friday.","会议将于周五举行。"],
["hurt","He hurt his leg while playing football.","他踢足球时伤了腿。"],
["ignore","You should not ignore the warning.","你不该忽视这个警告。"],
["imagine","I cannot imagine life without the Internet.","我无法想象没有网络的生活。"],
["impress","His speech impressed all of us.","他的演讲给我们所有人留下深刻印象。"],
["include","The price includes breakfast.","价格包含早餐。"],
["indicate","The study indicates that exercise reduces stress.","研究表明锻炼能减轻压力。"],
["influence","Parents have a great influence on children.","父母对孩子有很大影响。"],
["inform","Please inform me of any changes.","如有变动请通知我。"],
["injure","Two people were injured in the accident.","两人在事故中受伤。"],
["insist","She insisted on paying the bill.","她坚持要付账。"],
["inspire","His story inspired many young people.","他的故事激励了许多年轻人。"],
["intend","I intend to take the exam next year.","我打算明年参加考试。"],
["interest","He showed great interest in history.","他对历史表现出浓厚兴趣。"],
["introduce","Let me introduce myself briefly.","让我简单介绍一下自己。"],
["invite","On behalf of our class, I invite you.","我代表全班邀请你。"],
["involve","The job involves a lot of travelling.","这份工作涉及大量出差。"],
["join","She joined the volunteer team last year.","她去年加入了志愿队。"],
["judge","Do not judge a book by its cover.","不要以貌取人。"],
["keep","Keep in touch with me, please.","请与我保持联系。"],
["lack","He failed because of a lack of practice.","他因缺乏练习而失败。"],
["last","The meeting lasted two hours.","会议持续了两小时。"],
["lay","She laid the book on the table.","她把书放在桌上。"],
["lead","Hard work leads to success.","努力带来成功。"],
["learn","We learn a lot about ourselves during such trips.","这样的旅行中我们了解了很多关于自己的事。"],
["leave","Do not leave your luggage unattended.","不要让行李无人看管。"],
["lend","Could you lend me your bike?","你能借我自行车吗？"],
["limit","There is no limit to what you can learn.","你能学到的东西没有极限。"],
["link","The two events are closely linked.","这两件事密切相关。"],
["locate","The school is located in the city centre.","学校位于市中心。"],
["lose","Do not lose heart when you fail.","失败时不要灰心。"],
["maintain","It is important to maintain a healthy diet.","保持健康饮食很重要。"],
["manage","She manages a team of six people.","她管理着一个六人团队。"],
["mark","Please mark the correct answer.","请标出正确答案。"],
["match","The colour of the bag matches your coat.","包的颜色和你的外套很搭。"],
["mean","What do you mean by that?","你那样说是什么意思？"],
["measure","We must take effective measures.","我们必须采取有效措施。"],
["meet","The product meets international standards.","该产品符合国际标准。"],
["mention","He mentioned your name at the meeting.","他在会上提到了你的名字。"],
["mind","Would you mind opening the window?","你介意开一下窗吗？"],
["miss","I missed the last bus home.","我错过了回家的末班车。"],
["mix","Do not mix the two concepts.","不要混淆这两个概念。"],
["notice","I noticed that he looked tired.","我注意到他看起来很累。"],
["obey","Everyone must obey the traffic rules.","每个人都必须遵守交通规则。"],
["observe","Scientists observed the animals for months.","科学家观察这些动物数月之久。"],
["obtain","She obtained a degree in engineering.","她获得了工程学学位。"],
["occur","The accident occurred late at night.","事故发生在深夜。"],
["offer","They offered me a part-time job.","他们给我提供了一份兼职。"],
["operate","The machine is easy to operate.","这台机器操作简便。"],
["oppose","Many people opposed the new plan.","许多人反对这项新计划。"],
["order","The books are arranged in alphabetical order.","书按字母顺序排列。"],
["organise","The students organised a charity sale.","学生们组织了一场义卖。"],
["owe","I owe you an apology.","我欠你一个道歉。"],
["own","He owns a small bookshop downtown.","他在市中心拥有一家小书店。"],
["participate","Over 500 students participated in the event.","五百多名学生参加了这次活动。"],
["perform","She performed very well in the interview.","她在面试中表现很好。"],
["permit","Smoking is not permitted here.","这里不允许吸烟。"],
["persuade","I persuaded him to change his mind.","我说服他改变了主意。"],
["pick","Please pick the correct word.","请挑选正确的词。"],
["plan","We are planning a trip to Xi'an.","我们正在计划去西安旅行。"],
["play","Education plays an important role in society.","教育在社会中起重要作用。"],
["point","There is no point in worrying about it.","为此担心没有意义。"],
["possess","He possesses great patience.","他具有极大的耐心。"],
["practise","You should practise speaking every day.","你应该每天练习口语。"],
["prefer","I prefer tea to coffee.","比起咖啡我更喜欢茶。"],
["prepare","I am preparing for the entrance examination.","我正在准备入学考试。"],
["present","He presented his ideas clearly.","他清晰地表达了自己的想法。"],
["prevent","Washing hands can prevent diseases.","洗手能预防疾病。"],
["produce","The factory produces electronic products.","这家工厂生产电子产品。"],
["promise","He promised to help me with my English.","他答应帮我学英语。"],
["prove","The method has proved to be useful.","这个方法已被证明有用。"],
["provide","The school provides free lunch.","学校提供免费午餐。"],
["publish","The book was published last year.","这本书去年出版。"],
["pull","He pulled the door open.","他把门拉开。"],
["purchase","She purchased a new laptop online.","她在网上买了台新笔记本电脑。"],
["push","Do not push others in the queue.","排队时不要推搡他人。"],
["quit","He quit smoking for his health.","为了健康他戒了烟。"],
["raise","They raised money for the poor children.","他们为贫困儿童筹款。"],
["reach","We reached an agreement at last.","我们最终达成了协议。"],
["realise","I suddenly realised my mistake.","我突然意识到自己的错误。"],
["receive","I received your letter yesterday.","我昨天收到了你的信。"],
["recognise","I did not recognise him at first.","我起初没认出他。"],
["recommend","I recommend this book to all students.","我向所有学生推荐这本书。"],
["record","She broke the world record last month.","她上个月打破了世界纪录。"],
["reduce","We should reduce the use of plastic.","我们应该减少塑料的使用。"],
["refer","Please refer to page ten.","请参阅第十页。"],
["reflect","The change reflects a deeper desire.","这一变化反映了更深的渴望。"],
["refuse","She refused to give up her dream.","她拒绝放弃梦想。"],
["regard","I regard him as my best friend.","我把他视为最好的朋友。"],
["regret","I regret not studying harder.","我后悔没有更努力学习。"],
["reject","The company rejected his application.","公司拒绝了他的申请。"],
["relate","This problem relates to everyone.","这个问题与每个人都有关。"],
["release","The film will be released next month.","这部电影下月上映。"],
["rely","You can rely on him completely.","你可以完全信赖他。"],
["remain","Many questions remain unanswered.","许多问题仍未得到解答。"],
["remind","Please remind me to call her.","请提醒我给她打电话。"],
["remove","Please remove your shoes before entering.","进门前请脱鞋。"],
["repair","The bike needs to be repaired.","这辆自行车需要修理。"],
["repeat","Could you repeat that, please?","请你再说一遍好吗？"],
["replace","Machines cannot replace human care.","机器无法取代人的关怀。"],
["reply","I would appreciate an early reply.","希望您能尽快回复。"],
["report","The researchers reported their findings.","研究人员报告了他们的发现。"],
["represent","He represented our school in the contest.","他代表我们学校参赛。"],
["request","Your request has been approved.","你的请求已获批准。"],
["require","This job requires great patience.","这份工作需要极大的耐心。"],
["rescue","The firemen rescued three children.","消防员救出了三名儿童。"],
["research","They conducted research on air pollution.","他们对空气污染进行了研究。"],
["resist","He could not resist the temptation.","他无法抵挡诱惑。"],
["respect","We should respect other cultures.","我们应该尊重其他文化。"],
["respond","She responded to the letter quickly.","她很快回复了这封信。"],
["rest","You should have a good rest.","你应该好好休息。"],
["result","As a result, he lost the chance.","结果他失去了机会。"],
["return","He returned home late last night.","他昨晚很晚才回家。"],
["reveal","The study revealed an interesting fact.","研究揭示了一个有趣的事实。"],
["review","Let us review what we learned today.","我们复习一下今天学的内容。"],
["reward","Hard work will be rewarded.","努力会得到回报。"],
["rise","Prices have risen sharply this year.","今年物价急剧上涨。"],
["risk","Adults who exercise have a lower risk of heart disease.","经常锻炼的成年人心脏病风险较低。"],
["rush","Instead of rushing, slow travellers stay longer.","慢旅行者不匆忙赶路，而是停留更久。"],
["satisfy","The result satisfied everyone.","结果让所有人满意。"],
["save","We should save water in daily life.","日常生活中我们应节约用水。"],
["search","They searched for the missing child all night.","他们整夜寻找失踪的孩子。"],
["seek","Many graduates seek jobs in big cities.","许多毕业生在大城市求职。"],
["seem","He seems to be in a good mood today.","他今天似乎心情不错。"],
["select","Please select the best answer.","请选出最佳答案。"],
["sell","The shop sells fresh vegetables.","这家店卖新鲜蔬菜。"],
["send","I will send you the file by email.","我会把文件用邮件发给你。"],
["separate","Keep the two files separate.","把这两份文件分开放。"],
["serve","This restaurant serves local food.","这家餐厅供应当地食物。"],
["settle","They settled the problem peacefully.","他们和平地解决了问题。"],
["share","She shared her experience with us.","她与我们分享了她的经历。"],
["shine","The sun is shining brightly today.","今天阳光明媚。"],
["shock","The news shocked the whole country.","这个消息震惊了全国。"],
["show","The study shows that exercise improves mood.","研究表明锻炼能改善情绪。"],
["sign","Please sign your name here.","请在此签名。"],
["solve","We must find a way to solve it.","我们必须找到解决办法。"],
["spend","He spends two hours a day reading.","他每天花两小时阅读。"],
["spread","The news spread quickly.","消息传播得很快。"],
["stand","I cannot stand the noise.","我受不了这噪音。"],
["start","The meeting starts at nine.","会议九点开始。"],
["state","The report states the facts clearly.","报告清楚地陈述了事实。"],
["stay","They prefer to stay longer in one city.","他们更愿意在一座城市停留更久。"],
["stick","Stick to your plan and you will succeed.","坚持你的计划，你会成功的。"],
["stop","He stopped smoking for his health.","为了健康他戒了烟。"],
["strike","The clock struck twelve.","钟敲了十二下。"],
["struggle","She struggled to finish the work on time.","她努力按时完成工作。"],
["study","A study of 2,000 adults found this.","一项对两千名成年人的研究发现了这一点。"],
["succeed","If you keep trying, you will succeed.","如果坚持尝试，你会成功。"],
["suffer","Many people suffer from stress.","许多人受压力困扰。"],
["suggest","The doctor suggested that he take exercise.","医生建议他锻炼。"],
["supply","The company supplies goods to schools.","这家公司向学校供货。"],
["support","My parents always support my decisions.","父母总是支持我的决定。"],
["suppose","You are supposed to arrive on time.","你应该准时到达。"],
["survive","Only a few plants survived the cold.","只有少数植物在严寒中存活。"],
["taste","They taste the food that locals eat every day.","他们品尝当地人每天吃的食物。"],
["teach","She teaches English at a middle school.","她在一所中学教英语。"],
["tend","Young people tend to prefer online shopping.","年轻人往往更喜欢网购。"],
["thank","Thank you for your kind invitation.","感谢你的盛情邀请。"],
["throw","Do not throw rubbish everywhere.","不要乱扔垃圾。"],
["touch","Please keep in touch with me.","请与我保持联系。"],
["train","He was trained as an engineer.","他被培养成一名工程师。"],
["treat","Doctors treat patients with great care.","医生非常细心地治疗病人。"],
["try","Keep trying and you will make it.","不断尝试，你会做到的。"],
["turn","It is your turn to answer.","轮到你回答了。"],
["understand","I cannot understand what he means.","我无法理解他的意思。"],
["use","We should reduce the use of plastic bags.","我们应减少塑料袋的使用。"],
["value","We should value every opportunity.","我们应该珍惜每一个机会。"],
["vary","Prices vary from shop to shop.","各家店价格不同。"],
["visit","I visited the Palace Museum last summer.","去年夏天我参观了故宫。"],
["volunteer","Some even volunteer on farms.","有些人甚至在农场做志愿者。"],
["wait","We waited for him for half an hour.","我们等了他半小时。"],
["warn","The researchers warned that it is not a cure.","研究人员警告说这不是治愈方法。"],
["waste","Do not waste time on trifles.","不要在琐事上浪费时间。"],
["watch","They watched the sunrise together.","他们一起看了日出。"],
["wear","She wore a red dress to the party.","她穿了一件红裙子去参加聚会。"],
["welcome","The local people are friendly to visitors.","当地人对游客很友好。"],
["win","Our team won the first prize.","我们队赢得了一等奖。"],
["wish","I wish you every success.","祝你一切顺利。"],
["wonder","I wonder if you could help me.","不知你能否帮我一下。"],
["work","Some work in small guesthouses.","有些人在小旅馆工作。"],
["worry","There is no point in worrying.","担心没有用。"],
["write","I am writing to apply for the position.","我写信申请这个职位。"]
];

/* 并入例句索引 */
(function mergeCore(){
  if(typeof buildSentIndex!=='function') return;
  const _b=buildSentIndex;
  buildSentIndex=function(){
    const idx=_b();
    if(idx.__core) return idx;
    CORE_SENTS.forEach(e=>{
      const k=e[0].toLowerCase();
      idx[k]=idx[k]||[];
      if(!idx[k].some(x=>x.sent===e[1])) idx[k].push({sent:e[1], src:'考试例句', note:'', cn:e[2]});
    });
    idx.__core=true;
    return idx;
  };
})();
