/* ============================================================
   英语模块 · 湖北省普通高等教育专升本《大学英语》
   命题依据：《高职高专教育英语课程教学基本要求(试行)》B级标准（听力除外）
   ============================================================ */

const EN_META = {
  course: '大学英语',
  region: '湖北省普通高等教育专升本',
  method: '闭卷、笔试',
  duration: 120,
  fullScore: 100,
  standard: '《高职高专教育英语课程教学基本要求（试行）》B级标准（听力部分除外）',
  focus: '重点考查语法结构、词汇运用、阅读理解、英汉翻译和英语写作等方面的综合语言应用能力',
  vocabRequire: '约 3400 个基础词汇 + 常用词组，其中约 1500 个为高频核心词',
  sections: [
    { name: '词汇与结构', score: 25, detail: '词汇、词组与短语用法 10 题 + 语法结构 15 题，每题 1 分', color: '#4a7c9e' },
    { name: '阅读理解', score: 45, detail: '多篇不同体裁文章，考查细节定位、主旨归纳、词义猜测、推理判断', color: '#5b9279' },
    { name: '翻译', score: 20, detail: '英译汉为主，部分年份为翻译填空，需结合上下文补全', color: '#d9a441' },
    { name: '写作', score: 10, detail: '应用文为主：书信、便条、通知、简历等，词句正确、格式恰当', color: '#c1666b' }
  ],
  note: '各年度题型分值略有浮动（如翻译由单句翻译改为翻译填空），请以当年官方大纲为准。'
};

/* ---------- 语法体系：按零基础学习顺序排列 ---------- */
const GRAMMAR = [
  {
    id: 'g1', title: '词类与句子成分', weeks: '第1-2周', must: true,
    why: '这是英语的"字母表"。不知道什么是主语宾语，后面所有语法都是天书。',
    points: [
      { k: '十大词类', v: '名词、代词、动词、形容词、副词、介词、连词、冠词、数词、感叹词' },
      { k: '句子成分', v: '主语、谓语、宾语、表语、定语、状语、补语' },
      { k: '五大基本句型', v: 'S+V / S+V+O / S+V+P / S+V+IO+DO / S+V+O+OC' },
      { k: '判断技巧', v: '先找谓语动词，动词前是主语，动词后是宾语或表语' }
    ],
    exam: '本身不直接出题，但决定了你能否读懂长句。'
  },
  {
    id: 'g2', title: '时态（16种，重点8种）', weeks: '第3-5周', must: true,
    why: '语法题必考，翻译写作全靠它。时态错=句子错。',
    points: [
      { k: '一般现在时', v: 'do/does。表习惯、真理。主语第三人称单数动词加s' },
      { k: '一般过去时', v: 'did。表过去动作，常与 yesterday, ago, last 连用' },
      { k: '一般将来时', v: 'will do / be going to do' },
      { k: '现在进行时', v: 'am/is/are doing。表此刻正在发生' },
      { k: '过去进行时', v: 'was/were doing。常与 when, while 连用' },
      { k: '现在完成时', v: 'have/has done。已完成对现在有影响，标志词 already, yet, ever, never, since, for' },
      { k: '过去完成时', v: 'had done。"过去的过去"，常见于 by the time, before 从句' },
      { k: '现在完成进行时', v: 'have/has been doing。强调动作持续到现在还在继续' }
    ],
    exam: '⭐高频。看到 since/for 立刻想现在完成时；看到 by the time + 过去式，主句用过去完成时。'
  },
  {
    id: 'g3', title: '被动语态', weeks: '第6周', must: true,
    why: '阅读中大量出现，翻译必考，是中英思维差异的核心点。',
    points: [
      { k: '基本结构', v: 'be + 过去分词（done）' },
      { k: '各时态被动', v: '一般现在 am/is/are done；过去 was/were done；将来 will be done；完成 have been done' },
      { k: '情态动词被动', v: 'can/must/should + be done' },
      { k: '主动变被动', v: '原宾语提前作主语，动词变be+done，原主语用by引出' },
      { k: '常见固定', v: 'It is said that... 据说；It is reported that... 据报道' }
    ],
    exam: '⭐高频。英语爱用被动，汉语爱用主动，翻译时常需转换。'
  },
  {
    id: 'g4', title: '非谓语动词', weeks: '第7-9周', must: true,
    why: '专升本语法最大难点，也是拉开分差的地方。长难句几乎都含非谓语。',
    points: [
      { k: '三种形式', v: '不定式 to do、动名词 doing、分词 doing/done' },
      { k: '只接to do的动词', v: 'want, hope, decide, refuse, agree, promise, manage, afford' },
      { k: '只接doing的动词', v: 'enjoy, finish, mind, avoid, suggest, consider, practice, keep' },
      { k: '两者皆可但意义不同', v: 'remember/forget/regret + to do(未做) vs doing(已做)；stop to do(停下来去做) vs stop doing(停止做)' },
      { k: '现在分词vs过去分词', v: 'doing表主动进行（exciting令人兴奋），done表被动完成（excited感到兴奋）' },
      { k: '独立主格', v: '名词/代词 + 分词，作状语。Weather permitting, we will go.' }
    ],
    exam: '⭐⭐最高频难点。-ing修饰物，-ed修饰人，这条口诀能解决大量题目。'
  },
  {
    id: 'g5', title: '定语从句', weeks: '第10-11周', must: true,
    why: '阅读长难句的头号障碍，翻译高频考点。',
    points: [
      { k: '关系代词', v: 'who(人主/宾)、whom(人宾)、whose(所属)、which(物)、that(人物皆可)' },
      { k: '关系副词', v: 'when(时间)、where(地点)、why(原因)' },
      { k: '只能用that', v: '先行词被 all, any, no, every, only, 最高级, 序数词修饰时' },
      { k: '不能用that', v: '非限制性定语从句（逗号后）、介词后' },
      { k: '限制性vs非限制性', v: '有逗号的是非限制性，去掉不影响主句意思，翻译时常单独成句' },
      { k: '介词+关系代词', v: 'the house in which he lives = the house where he lives' }
    ],
    exam: '⭐⭐高频。判断口诀：先找先行词，再看它在从句中作什么成分。'
  },
  {
    id: 'g6', title: '名词性从句', weeks: '第12周', must: false,
    why: '写作提分利器，阅读中常见。',
    points: [
      { k: '四种类型', v: '主语从句、宾语从句、表语从句、同位语从句' },
      { k: '引导词', v: 'that(无意义不作成分)、whether/if(是否)、疑问词 what/who/when/where/how/why' },
      { k: 'that与what区别', v: 'that不作成分不翻译，what作成分译"所…的"' },
      { k: '形式主语', v: 'It is important that... / It is said that...' },
      { k: '语序', v: '从句一律用陈述语序，不能倒装' }
    ],
    exam: '写作中用 It is + adj + that 句型可提升档次。'
  },
  {
    id: 'g7', title: '状语从句', weeks: '第13周', must: false,
    why: '连词选择题的主要考点，翻译中处理逻辑关系必备。',
    points: [
      { k: '时间', v: 'when, while, as, before, after, until, as soon as, since' },
      { k: '原因', v: 'because, since, as, for' },
      { k: '条件', v: 'if, unless(=if not), as long as, provided that' },
      { k: '让步', v: 'though, although, even if, no matter how/what' },
      { k: '目的结果', v: 'so that, in order that；so...that, such...that' },
      { k: '主将从现', v: '时间和条件状语从句中，主句将来时，从句用一般现在时' }
    ],
    exam: '⭐高频。although与but不能同时出现，because与so不能同时出现（中式英语陷阱）。'
  },
  {
    id: 'g8', title: '虚拟语气', weeks: '第14周', must: false,
    why: '难点但考点固定，掌握三个公式就能拿分。',
    points: [
      { k: '与现在相反', v: 'If + 主语 + did/were, 主语 + would/could/might + do' },
      { k: '与过去相反', v: 'If + 主语 + had done, 主语 + would have done' },
      { k: '与将来相反', v: 'If + 主语 + should do/were to do, 主语 + would do' },
      { k: '宾语从句虚拟', v: 'suggest, insist, demand, require, order + that + 主语 + (should) do' },
      { k: '固定句型', v: 'wish + 虚拟；as if + 虚拟；It is time that + did' }
    ],
    exam: '记住"过去完成配would have"这一条就能应付大部分题。'
  },
  {
    id: 'g9', title: '比较级最高级与倒装', weeks: '第15周', must: false,
    why: '零散但每年都考，属于送分点。',
    points: [
      { k: '比较级', v: 'than；the + 比较级, the + 比较级（越…越…）；比较级 + and + 比较级（越来越）' },
      { k: '最高级', v: 'the + est/most + in/of 范围；one of the + 最高级 + 复数名词' },
      { k: '倍数表达', v: 'A is three times as large as B / three times larger than B' },
      { k: '完全倒装', v: '地点副词/介词短语置句首：Here comes the bus.' },
      { k: '部分倒装', v: '否定词置句首：Never have I seen... / Not only...but also...' },
      { k: 'only置句首', v: 'Only in this way can we succeed.' }
    ],
    exam: '看到句首 never, seldom, hardly, not only, only + 状语，立刻想部分倒装。'
  },
  {
    id: 'g10', title: '介词与固定搭配', weeks: '第16周', must: true,
    why: '词汇题的隐形主力，靠积累不靠理解。',
    points: [
      { k: '时间介词', v: 'in(年月季)、on(具体某天)、at(具体时刻)' },
      { k: '动词+介词', v: 'depend on, look for, deal with, result in, result from, consist of' },
      { k: '形容词+介词', v: 'be good at, be afraid of, be interested in, be famous for, be responsible for' },
      { k: '名词+介词', v: 'reason for, solution to, key to, access to, attitude towards' },
      { k: '易混对比', v: 'result in(导致) vs result from(源于)；be made of(看得出原料) vs be made from(看不出)' }
    ],
    exam: '⭐高频。这类题不会就是不会，必须靠背，建议每天10个搭配。'
  }
];

/* ---------- 英语学习路径 ---------- */
const EN_PATH = [
  { stage: 1, name: '零基础启动', weeks: '第1-2周',
    goal: '搞清楚句子是怎么组成的，能拆解简单句',
    tasks: ['学完「词类与句子成分」', '掌握五大基本句型', '每天背20个核心词（Level 1）'],
    tip: '别急着背语法规则，先能把一个句子拆成"谁 + 做了什么 + 对谁"。这一步没通，后面全是死记硬背。' },
  { stage: 2, name: '时态攻坚', weeks: '第3-6周',
    goal: '8大常用时态 + 被动语态全部过关',
    tasks: ['学完时态与被动语态', '每个时态自己造5个句子', '每天背25个核心词'],
    tip: '时态是英语的骨架。建议做一张表，横轴时间（过去/现在/将来），纵轴状态（一般/进行/完成），自己填满。' },
  { stage: 3, name: '啃硬骨头', weeks: '第7-11周',
    goal: '非谓语动词 + 定语从句，这是分水岭',
    tasks: ['非谓语动词三种形式辨析', '定语从句关系词选择', '开始每天精读1篇短文章'],
    tip: '这两块是专升本英语最难的地方，也是最能拉分的地方。慢一点没关系，一定要弄懂，不能囫囵吞枣。' },
  { stage: 4, name: '补齐短板', weeks: '第12-16周',
    goal: '名词性从句、状语从句、虚拟、倒装、固定搭配',
    tasks: ['过完剩余语法专题', '词汇量推进到1500核心词', '每天1篇阅读 + 5个句子翻译'],
    tip: '这阶段语法基本齐了，重心逐渐转向阅读和词汇。固定搭配要开始高强度背。' },
  { stage: 5, name: '技能强化', weeks: '第17-22周',
    goal: '阅读提速、翻译成句、写作模板',
    tasks: ['每天2篇阅读（限时8分钟/篇）', '翻译技巧专项训练', '背熟3类应用文模板', '词汇冲刺3000'],
    tip: '阅读45分是最大头，必须限时练。翻译要动笔写，不能只在脑子里过。写作背模板 + 替换词是最快见效的。' },
  { stage: 6, name: '真题冲刺', weeks: '第23-26周',
    goal: '限时模拟、查漏补缺、错题复盘',
    tasks: ['120分钟整套限时模拟', '错题本二刷三刷', '高频词最后强化', '作文模板默写'],
    tip: '严格按120分钟计时。做完立刻订正，把每道错题归到具体语法点或词汇上，回去补那个点。' }
];

/* ---------- 词汇：分级核心词库 ----------
   L1 入门必备 / L2 高频核心 / L3 进阶拓展
   格式: [单词, 音标, 词性释义, 等级]
------------------------------------------- */
const VOCAB = [
["abandon","/ə'bændən/","v. 放弃，抛弃",2],
["ability","/ə'bɪlətɪ/","n. 能力，才能",1],
["able","/'eɪbl/","a. 能够的，有能力的",1],
["abroad","/ə'brɔːd/","ad. 在国外，到国外",1],
["absence","/'æbsəns/","n. 缺席，不在",2],
["absolute","/'æbsəluːt/","a. 绝对的，完全的",2],
["absorb","/əb'sɔːb/","v. 吸收，吸引",2],
["abstract","/'æbstrækt/","a. 抽象的 n. 摘要",3],
["abuse","/ə'bjuːz/","v./n. 滥用，虐待",3],
["accent","/'æksent/","n. 口音，重音",2],
["accept","/ək'sept/","v. 接受，认可",1],
["access","/'ækses/","n. 通道，接近 v. 访问",2],
["accident","/'æksɪdənt/","n. 事故，意外",1],
["accompany","/ə'kʌmpənɪ/","v. 陪伴，伴随",2],
["accomplish","/ə'kʌmplɪʃ/","v. 完成，实现",2],
["according","/ə'kɔːdɪŋ/","ad. 根据（to）",1],
["account","/ə'kaʊnt/","n. 账户，描述 v. 解释",2],
["accurate","/'ækjərət/","a. 精确的，准确的",2],
["accuse","/ə'kjuːz/","v. 控告，指责",3],
["achieve","/ə'tʃiːv/","v. 达到，完成",1],
["acid","/'æsɪd/","n. 酸 a. 酸的",3],
["acquire","/ə'kwaɪə/","v. 获得，习得",2],
["across","/ə'krɒs/","prep. 穿过，横过",1],
["act","/ækt/","v. 行动，表演 n. 行为",1],
["active","/'æktɪv/","a. 积极的，活跃的",1],
["activity","/æk'tɪvətɪ/","n. 活动",1],
["actual","/'æktʃuəl/","a. 实际的，真实的",1],
["adapt","/ə'dæpt/","v. 适应，改编",2],
["add","/æd/","v. 增加，添加",1],
["addition","/ə'dɪʃn/","n. 增加，加法",1],
["address","/ə'dres/","n. 地址 v. 演说，处理",1],
["adequate","/'ædɪkwət/","a. 足够的，适当的",2],
["adjust","/ə'dʒʌst/","v. 调整，适应",2],
["administration","/ədˌmɪnɪ'streɪʃn/","n. 管理，行政",3],
["admire","/əd'maɪə/","v. 钦佩，欣赏",2],
["admit","/əd'mɪt/","v. 承认，允许进入",1],
["adopt","/ə'dɒpt/","v. 采取，收养",2],
["advance","/əd'vɑːns/","v./n. 前进，进步",2],
["advantage","/əd'vɑːntɪdʒ/","n. 优点，优势",1],
["adventure","/əd'ventʃə/","n. 冒险",2],
["advertise","/'ædvətaɪz/","v. 做广告",2],
["advice","/əd'vaɪs/","n. 建议（不可数）",1],
["advise","/əd'vaɪz/","v. 建议，劝告",1],
["affair","/ə'feə/","n. 事务，事件",2],
["affect","/ə'fekt/","v. 影响",1],
["afford","/ə'fɔːd/","v. 买得起，负担得起",1],
["afraid","/ə'freɪd/","a. 害怕的",1],
["age","/eɪdʒ/","n. 年龄，时代",1],
["agency","/'eɪdʒənsɪ/","n. 代理，机构",2],
["agent","/'eɪdʒənt/","n. 代理人",2],
["aggressive","/ə'gresɪv/","a. 侵略的，好斗的",3],
["agree","/ə'griː/","v. 同意",1],
["agriculture","/'ægrɪkʌltʃə/","n. 农业",2],
["ahead","/ə'hed/","ad. 在前，向前",1],
["aid","/eɪd/","n./v. 帮助，援助",2],
["aim","/eɪm/","n. 目标 v. 瞄准",1],
["air","/eə/","n. 空气",1],
["aircraft","/'eəkrɑːft/","n. 飞机，航空器",2],
["alarm","/ə'lɑːm/","n. 警报 v. 使惊恐",2],
["alcohol","/'ælkəhɒl/","n. 酒精",2],
["alike","/ə'laɪk/","a. 相似的 ad. 同样地",2],
["alive","/ə'laɪv/","a. 活着的",1],
["allow","/ə'laʊ/","v. 允许",1],
["almost","/'ɔːlməʊst/","ad. 几乎",1],
["alone","/ə'ləʊn/","a./ad. 单独的，仅仅",1],
["along","/ə'lɒŋ/","prep. 沿着",1],
["aloud","/ə'laʊd/","ad. 出声地，大声地",2],
["already","/ɔːl'redɪ/","ad. 已经",1],
["also","/'ɔːlsəʊ/","ad. 也",1],
["alter","/'ɔːltə/","v. 改变，修改",2],
["alternative","/ɔːl'tɜːnətɪv/","n. 选择 a. 可替代的",3],
["although","/ɔːl'ðəʊ/","conj. 虽然",1],
["altogether","/ˌɔːltə'geðə/","ad. 总共，完全",2],
["always","/'ɔːlweɪz/","ad. 总是",1],
["amaze","/ə'meɪz/","v. 使惊奇",2],
["ambition","/æm'bɪʃn/","n. 雄心，抱负",2],
["among","/ə'mʌŋ/","prep. 在…之中",1],
["amount","/ə'maʊnt/","n. 数量，总额",1],
["analyse","/'ænəlaɪz/","v. 分析",2],
["analysis","/ə'næləsɪs/","n. 分析",2],
["ancient","/'eɪnʃənt/","a. 古代的",1],
["anger","/'æŋgə/","n. 愤怒",1],
["angle","/'æŋgl/","n. 角，角度",2],
["announce","/ə'naʊns/","v. 宣布",2],
["annoy","/ə'nɔɪ/","v. 使恼怒",2],
["annual","/'ænjuəl/","a. 每年的",2],
["another","/ə'nʌðə/","a./pron. 另一个",1],
["answer","/'ɑːnsə/","n./v. 回答",1],
["anxious","/'æŋkʃəs/","a. 焦虑的，渴望的",2],
["anybody","/'enɪbɒdɪ/","pron. 任何人",1],
["apart","/ə'pɑːt/","ad. 分开地，相隔",2],
["apologize","/ə'pɒlədʒaɪz/","v. 道歉",2],
["apparent","/ə'pærənt/","a. 明显的，表面的",2],
["appeal","/ə'piːl/","v./n. 呼吁，吸引",2],
["appear","/ə'pɪə/","v. 出现，显得",1],
["appetite","/'æpɪtaɪt/","n. 食欲，欲望",3],
["apply","/ə'plaɪ/","v. 申请，应用",1],
["appoint","/ə'pɔɪnt/","v. 任命，约定",2],
["appreciate","/ə'priːʃɪeɪt/","v. 欣赏，感激",2],
["approach","/ə'prəʊtʃ/","n. 方法 v. 接近",2],
["appropriate","/ə'prəʊprɪət/","a. 适当的",2],
["approve","/ə'pruːv/","v. 赞成，批准",2],
["approximately","/ə'prɒksɪmətlɪ/","ad. 大约",3],
["area","/'eərɪə/","n. 面积，地区",1],
["argue","/'ɑːgjuː/","v. 争论，辩论",1],
["arise","/ə'raɪz/","v. 出现，产生",2],
["arm","/ɑːm/","n. 手臂 v. 武装",1],
["army","/'ɑːmɪ/","n. 军队",1],
["around","/ə'raʊnd/","prep. 在…周围",1],
["arrange","/ə'reɪndʒ/","v. 安排，整理",1],
["arrest","/ə'rest/","v./n. 逮捕",2],
["arrive","/ə'raɪv/","v. 到达",1],
["article","/'ɑːtɪkl/","n. 文章，物品",1],
["artificial","/ˌɑːtɪ'fɪʃl/","a. 人造的，虚假的",2],
["ashamed","/ə'ʃeɪmd/","a. 羞愧的",2],
["aside","/ə'saɪd/","ad. 在旁边",2],
["aspect","/'æspekt/","n. 方面",2],
["assess","/ə'ses/","v. 评估",3],
["assign","/ə'saɪn/","v. 分配，指派",2],
["assist","/ə'sɪst/","v. 帮助",2],
["associate","/ə'səʊʃɪeɪt/","v. 联想，交往",2],
["assume","/ə'sjuːm/","v. 假定，承担",2],
["assure","/ə'ʃʊə/","v. 保证，使确信",3],
["astonish","/ə'stɒnɪʃ/","v. 使惊讶",3],
["atmosphere","/'ætməsfɪə/","n. 大气，气氛",2],
["attach","/ə'tætʃ/","v. 附上，贴上",2],
["attack","/ə'tæk/","v./n. 攻击",1],
["attempt","/ə'tempt/","v./n. 尝试",2],
["attend","/ə'tend/","v. 出席，照料",1],
["attention","/ə'tenʃn/","n. 注意",1],
["attitude","/'ætɪtjuːd/","n. 态度",1],
["attract","/ə'trækt/","v. 吸引",1],
["audience","/'ɔːdɪəns/","n. 观众，听众",1],
["author","/'ɔːθə/","n. 作者",1],
["authority","/ɔː'θɒrətɪ/","n. 权威，当局",2],
["automatic","/ˌɔːtə'mætɪk/","a. 自动的",2],
["available","/ə'veɪləbl/","a. 可用的，可得到的",1],
["average","/'ævərɪdʒ/","n./a. 平均（的）",1],
["avoid","/ə'vɔɪd/","v. 避免",1],
["await","/ə'weɪt/","v. 等待",3],
["awake","/ə'weɪk/","a. 醒着的",2],
["award","/ə'wɔːd/","n. 奖 v. 授予",2],
["aware","/ə'weə/","a. 意识到的",1],
["awful","/'ɔːfl/","a. 可怕的，糟糕的",2],
["background","/'bækgraʊnd/","n. 背景",1],
["balance","/'bæləns/","n./v. 平衡",1],
["ban","/bæn/","v./n. 禁止",2],
["band","/bænd/","n. 乐队，带子",2],
["bargain","/'bɑːgɪn/","n. 便宜货 v. 讨价还价",2],
["barrier","/'bærɪə/","n. 障碍，屏障",2],
["base","/beɪs/","n. 基础 v. 以…为基础",1],
["basic","/'beɪsɪk/","a. 基本的",1],
["basis","/'beɪsɪs/","n. 基础，根据",2],
["battle","/'bætl/","n. 战斗",1],
["bear","/beə/","v. 忍受，承担 n. 熊",1],
["beat","/biːt/","v. 打败，敲打",1],
["beauty","/'bjuːtɪ/","n. 美，美人",1],
["become","/bɪ'kʌm/","v. 变成",1],
["beg","/beg/","v. 乞求，请求",2],
["begin","/bɪ'gɪn/","v. 开始",1],
["behave","/bɪ'heɪv/","v. 表现，举止",2],
["behavior","/bɪ'heɪvjə/","n. 行为",1],
["behind","/bɪ'haɪnd/","prep. 在…后面",1],
["belief","/bɪ'liːf/","n. 信念，信仰",1],
["believe","/bɪ'liːv/","v. 相信",1],
["belong","/bɪ'lɒŋ/","v. 属于（to）",1],
["below","/bɪ'ləʊ/","prep. 在…下面",1],
["benefit","/'benɪfɪt/","n. 利益 v. 有益于",1],
["beside","/bɪ'saɪd/","prep. 在…旁边",1],
["besides","/bɪ'saɪdz/","prep./ad. 除…之外（还）",1],
["between","/bɪ'twiːn/","prep. 在…之间",1],
["beyond","/bɪ'jɒnd/","prep. 超过，在…之外",2],
["bill","/bɪl/","n. 账单，法案",1],
["bind","/baɪnd/","v. 捆绑，束缚",2],
["birth","/bɜːθ/","n. 出生",1],
["bite","/baɪt/","v. 咬",1],
["bitter","/'bɪtə/","a. 苦的，痛苦的",2],
["blame","/bleɪm/","v./n. 责备",2],
["blank","/blæŋk/","a. 空白的 n. 空白",1],
["blind","/blaɪnd/","a. 瞎的",1],
["block","/blɒk/","n. 街区 v. 阻塞",1],
["blood","/blʌd/","n. 血",1],
["blow","/bləʊ/","v. 吹 n. 打击",1],
["board","/bɔːd/","n. 板，董事会 v. 登上",1],
["boast","/bəʊst/","v. 吹嘘",3],
["boil","/bɔɪl/","v. 沸腾，煮",1],
["bold","/bəʊld/","a. 大胆的",2],
["bond","/bɒnd/","n. 纽带，债券",3],
["border","/'bɔːdə/","n. 边界",2],
["bore","/bɔː/","v. 使厌烦",2],
["borrow","/'bɒrəʊ/","v. 借入",1],
["bother","/'bɒðə/","v. 打扰，麻烦",2],
["bottom","/'bɒtəm/","n. 底部",1],
["bound","/baʊnd/","a. 一定的，被束缚的",2],
["branch","/brɑːntʃ/","n. 树枝，分支",1],
["brave","/breɪv/","a. 勇敢的",1],
["breath","/breθ/","n. 呼吸",1],
["breathe","/briːð/","v. 呼吸",1],
["brief","/briːf/","a. 简短的",2],
["bright","/braɪt/","a. 明亮的，聪明的",1],
["brilliant","/'brɪlɪənt/","a. 辉煌的，杰出的",2],
["bring","/brɪŋ/","v. 带来",1],
["broad","/brɔːd/","a. 宽阔的",1],
["budget","/'bʌdʒɪt/","n. 预算",2],
["build","/bɪld/","v. 建造",1],
["burden","/'bɜːdn/","n. 负担",2],
["burn","/bɜːn/","v. 燃烧",1],
["burst","/bɜːst/","v. 爆裂，突然发作",2],
["bury","/'berɪ/","v. 埋葬",2],
["business","/'bɪznəs/","n. 生意，事务",1],
["busy","/'bɪzɪ/","a. 忙碌的",1],
["calculate","/'kælkjuleɪt/","v. 计算",2],
["campaign","/kæm'peɪn/","n. 运动，战役",2],
["cancel","/'kænsl/","v. 取消",2],
["candidate","/'kændɪdət/","n. 候选人",2],
["capable","/'keɪpəbl/","a. 有能力的",2],
["capacity","/kə'pæsətɪ/","n. 容量，能力",2],
["capital","/'kæpɪtl/","n. 首都，资本",1],
["capture","/'kæptʃə/","v. 捕获",2],
["care","/keə/","n./v. 关心，照顾",1],
["career","/kə'rɪə/","n. 职业，生涯",1],
["careful","/'keəfl/","a. 仔细的",1],
["carry","/'kærɪ/","v. 携带，搬运",1],
["case","/keɪs/","n. 情况，案例，箱子",1],
["cash","/kæʃ/","n. 现金",1],
["cast","/kɑːst/","v. 投掷，投射",2],
["casual","/'kæʒuəl/","a. 随便的，偶然的",2],
["catch","/kætʃ/","v. 抓住，赶上",1],
["cause","/kɔːz/","n. 原因 v. 引起",1],
["cautious","/'kɔːʃəs/","a. 谨慎的",3],
["cease","/siːs/","v. 停止",3],
["celebrate","/'selɪbreɪt/","v. 庆祝",1],
["cell","/sel/","n. 细胞，牢房",2],
["central","/'sentrəl/","a. 中心的",1],
["century","/'sentʃərɪ/","n. 世纪",1],
["certain","/'sɜːtn/","a. 确定的，某些",1],
["challenge","/'tʃælɪndʒ/","n./v. 挑战",1],
["chance","/tʃɑːns/","n. 机会，可能性",1],
["change","/tʃeɪndʒ/","n./v. 改变",1],
["channel","/'tʃænl/","n. 频道，渠道",2],
["character","/'kærəktə/","n. 性格，角色，字符",1],
["characteristic","/ˌkærəktə'rɪstɪk/","n. 特征 a. 典型的",2],
["charge","/tʃɑːdʒ/","v. 收费，控告 n. 费用",1],
["charity","/'tʃærətɪ/","n. 慈善",2],
["chase","/tʃeɪs/","v. 追逐",2],
["cheat","/tʃiːt/","v. 欺骗，作弊",2],
["check","/tʃek/","v. 检查 n. 支票",1],
["cheer","/tʃɪə/","v. 欢呼，使高兴",1],
["chemical","/'kemɪkl/","a. 化学的 n. 化学品",2],
["chief","/tʃiːf/","a. 主要的 n. 首领",1],
["choice","/tʃɔɪs/","n. 选择",1],
["choose","/tʃuːz/","v. 选择",1],
["circle","/'sɜːkl/","n. 圆，圈子",1],
["circumstance","/'sɜːkəmstəns/","n. 情况，环境",2],
["cite","/saɪt/","v. 引用",3],
["citizen","/'sɪtɪzn/","n. 公民",1],
["civil","/'sɪvl/","a. 公民的，民事的",2],
["claim","/kleɪm/","v. 声称，索取",2],
["class","/klɑːs/","n. 班级，阶级",1],
["classic","/'klæsɪk/","a. 经典的",2],
["clean","/kliːn/","a. 干净的 v. 打扫",1],
["clear","/klɪə/","a. 清楚的",1],
["clerk","/klɑːk/","n. 职员",1],
["clever","/'klevə/","a. 聪明的",1],
["client","/'klaɪənt/","n. 客户",2],
["climate","/'klaɪmət/","n. 气候",1],
["climb","/klaɪm/","v. 攀登",1],
["close","/kləʊz/","v. 关闭 a. 接近的",1],
["clothes","/kləʊðz/","n. 衣服",1],
["cloud","/klaʊd/","n. 云",1],
["club","/klʌb/","n. 俱乐部",1],
["coach","/kəʊtʃ/","n. 教练，长途汽车",1],
["coast","/kəʊst/","n. 海岸",1],
["code","/kəʊd/","n. 代码，法规",2],
["collapse","/kə'læps/","v./n. 倒塌，崩溃",3],
["colleague","/'kɒliːg/","n. 同事",2],
["collect","/kə'lekt/","v. 收集",1],
["college","/'kɒlɪdʒ/","n. 学院，大学",1],
["combine","/kəm'baɪn/","v. 结合",1],
["comfort","/'kʌmfət/","n. 舒适 v. 安慰",1],
["command","/kə'mɑːnd/","n./v. 命令，指挥",2],
["comment","/'kɒment/","n./v. 评论",2],
["commercial","/kə'mɜːʃl/","a. 商业的",2],
["commit","/kə'mɪt/","v. 犯（罪），承诺",2],
["committee","/kə'mɪtɪ/","n. 委员会",2],
["common","/'kɒmən/","a. 共同的，普通的",1],
["communicate","/kə'mjuːnɪkeɪt/","v. 交流",1],
["community","/kə'mjuːnətɪ/","n. 社区，共同体",1],
["company","/'kʌmpənɪ/","n. 公司，陪伴",1],
["compare","/kəm'peə/","v. 比较",1],
["compete","/kəm'piːt/","v. 竞争",1],
["complain","/kəm'pleɪn/","v. 抱怨",1],
["complete","/kəm'pliːt/","a. 完整的 v. 完成",1],
["complex","/'kɒmpleks/","a. 复杂的",2],
["complicated","/'kɒmplɪkeɪtɪd/","a. 复杂的",2],
["compose","/kəm'pəʊz/","v. 组成，创作",2],
["comprehensive","/ˌkɒmprɪ'hensɪv/","a. 综合的，全面的",3],
["compromise","/'kɒmprəmaɪz/","n./v. 妥协",3],
["compute","/kəm'pjuːt/","v. 计算",2],
["concentrate","/'kɒnsntreɪt/","v. 集中",2],
["concept","/'kɒnsept/","n. 概念",2],
["concern","/kən'sɜːn/","v. 关心，涉及 n. 担心",1],
["conclude","/kən'kluːd/","v. 结束，得出结论",2],
["conclusion","/kən'kluːʒn/","n. 结论",2],
["condition","/kən'dɪʃn/","n. 条件，状况",1],
["conduct","/kən'dʌkt/","v. 进行，指挥",2],
["conference","/'kɒnfərəns/","n. 会议",2],
["confident","/'kɒnfɪdənt/","a. 自信的",1],
["confirm","/kən'fɜːm/","v. 确认",2],
["conflict","/'kɒnflɪkt/","n. 冲突",2],
["confuse","/kən'fjuːz/","v. 使困惑",2],
["congratulate","/kən'grætʃuleɪt/","v. 祝贺",2],
["connect","/kə'nekt/","v. 连接",1],
["conscious","/'kɒnʃəs/","a. 有意识的",2],
["consequence","/'kɒnsɪkwəns/","n. 结果，后果",2],
["consider","/kən'sɪdə/","v. 考虑，认为",1],
["considerable","/kən'sɪdərəbl/","a. 相当大的",2],
["consist","/kən'sɪst/","v. 由…组成（of）",2],
["constant","/'kɒnstənt/","a. 不断的，恒定的",2],
["construct","/kən'strʌkt/","v. 建造",2],
["consult","/kən'sʌlt/","v. 咨询",2],
["consume","/kən'sjuːm/","v. 消费，消耗",2],
["contact","/'kɒntækt/","n./v. 联系",1],
["contain","/kən'teɪn/","v. 包含",1],
["contemporary","/kən'temprərɪ/","a. 当代的",3],
["content","/'kɒntent/","n. 内容 a. 满足的",1],
["contest","/'kɒntest/","n. 比赛",2],
["context","/'kɒntekst/","n. 上下文，背景",2],
["continue","/kən'tɪnjuː/","v. 继续",1],
["contract","/'kɒntrækt/","n. 合同 v. 收缩",2],
["contrast","/'kɒntrɑːst/","n. 对比",2],
["contribute","/kən'trɪbjuːt/","v. 贡献，捐助",2],
["control","/kən'trəʊl/","n./v. 控制",1],
["convenient","/kən'viːnɪənt/","a. 方便的",1],
["conversation","/ˌkɒnvə'seɪʃn/","n. 对话",1],
["convey","/kən'veɪ/","v. 传达，运输",3],
["convince","/kən'vɪns/","v. 使信服",2],
["cooperate","/kəʊ'ɒpəreɪt/","v. 合作",2],
["cope","/kəʊp/","v. 应付（with）",2],
["copy","/'kɒpɪ/","n. 副本 v. 复制",1],
["correct","/kə'rekt/","a. 正确的 v. 改正",1],
["cost","/kɒst/","n. 成本 v. 花费",1],
["count","/kaʊnt/","v. 计数，重要",1],
["country","/'kʌntrɪ/","n. 国家，乡村",1],
["couple","/'kʌpl/","n. 一对，夫妇",1],
["courage","/'kʌrɪdʒ/","n. 勇气",1],
["course","/kɔːs/","n. 课程，过程",1],
["court","/kɔːt/","n. 法庭，球场",1],
["cover","/'kʌvə/","v. 覆盖，包括",1],
["crash","/kræʃ/","n./v. 碰撞，坠毁",2],
["create","/krɪ'eɪt/","v. 创造",1],
["credit","/'kredɪt/","n. 信用，学分",1],
["crime","/kraɪm/","n. 犯罪",1],
["crisis","/'kraɪsɪs/","n. 危机",2],
["critical","/'krɪtɪkl/","a. 批判的，关键的",2],
["criticize","/'krɪtɪsaɪz/","v. 批评",2],
["crop","/krɒp/","n. 庄稼，收成",2],
["cross","/krɒs/","v. 穿过 n. 十字",1],
["crowd","/kraʊd/","n. 人群",1],
["crucial","/'kruːʃl/","a. 至关重要的",3],
["cruel","/'kruːəl/","a. 残酷的",2],
["cultural","/'kʌltʃərəl/","a. 文化的",1],
["culture","/'kʌltʃə/","n. 文化",1],
["cure","/kjʊə/","v./n. 治愈",1],
["curious","/'kjʊərɪəs/","a. 好奇的",2],
["current","/'kʌrənt/","a. 当前的 n. 电流",1],
["custom","/'kʌstəm/","n. 习俗",1],
["customer","/'kʌstəmə/","n. 顾客",1],
["cut","/kʌt/","v. 切，削减",1],
["damage","/'dæmɪdʒ/","n./v. 损害",1],
["danger","/'deɪndʒə/","n. 危险",1],
["dare","/deə/","v. 敢",1],
["dark","/dɑːk/","a. 黑暗的",1],
["data","/'deɪtə/","n. 数据",1],
["deal","/diːl/","v. 处理（with）n. 交易",1],
["debate","/dɪ'beɪt/","n./v. 辩论",2],
["debt","/det/","n. 债务",2],
["decade","/'dekeɪd/","n. 十年",2],
["decide","/dɪ'saɪd/","v. 决定",1],
["decision","/dɪ'sɪʒn/","n. 决定",1],
["declare","/dɪ'kleə/","v. 宣布，申报",2],
["decline","/dɪ'klaɪn/","v./n. 下降，拒绝",2],
["decrease","/dɪ'kriːs/","v./n. 减少",2],
["deep","/diːp/","a. 深的",1],
["defeat","/dɪ'fiːt/","v./n. 击败",2],
["defend","/dɪ'fend/","v. 保卫，辩护",2],
["define","/dɪ'faɪn/","v. 定义",2],
["definite","/'defɪnət/","a. 明确的",2],
["degree","/dɪ'griː/","n. 程度，学位，度",1],
["delay","/dɪ'leɪ/","v./n. 延迟",1],
["deliberate","/dɪ'lɪbərət/","a. 故意的，深思熟虑的",3],
["delicate","/'delɪkət/","a. 精致的，微妙的",3],
["deliver","/dɪ'lɪvə/","v. 递送，发表",2],
["demand","/dɪ'mɑːnd/","n./v. 要求，需求",1],
["demonstrate","/'demənstreɪt/","v. 证明，演示",2],
["deny","/dɪ'naɪ/","v. 否认",2],
["depend","/dɪ'pend/","v. 依靠（on）",1],
["describe","/dɪ'skraɪb/","v. 描述",1],
["desert","/'dezət/","n. 沙漠 v. 抛弃",1],
["deserve","/dɪ'zɜːv/","v. 应得",2],
["design","/dɪ'zaɪn/","n./v. 设计",1],
["desire","/dɪ'zaɪə/","n./v. 渴望",1],
["despite","/dɪ'spaɪt/","prep. 尽管",2],
["destroy","/dɪ'strɔɪ/","v. 破坏",1],
["detail","/'diːteɪl/","n. 细节",1],
["detect","/dɪ'tekt/","v. 察觉，探测",2],
["determine","/dɪ'tɜːmɪn/","v. 决定，确定",1],
["develop","/dɪ'veləp/","v. 发展，开发",1],
["device","/dɪ'vaɪs/","n. 装置，设备",2],
["devote","/dɪ'vəʊt/","v. 奉献（to）",2],
["dialogue","/'daɪəlɒg/","n. 对话",1],
["differ","/'dɪfə/","v. 不同",1],
["difficulty","/'dɪfɪkəltɪ/","n. 困难",1],
["digital","/'dɪdʒɪtl/","a. 数字的",1],
["direct","/dɪ'rekt/","a. 直接的 v. 指导",1],
["direction","/dɪ'rekʃn/","n. 方向",1],
["disagree","/ˌdɪsə'griː/","v. 不同意",1],
["disappear","/ˌdɪsə'pɪə/","v. 消失",1],
["disappoint","/ˌdɪsə'pɔɪnt/","v. 使失望",1],
["disaster","/dɪ'zɑːstə/","n. 灾难",2],
["discipline","/'dɪsəplɪn/","n. 纪律，学科",2],
["discount","/'dɪskaʊnt/","n. 折扣",1],
["discover","/dɪ'skʌvə/","v. 发现",1],
["discuss","/dɪ'skʌs/","v. 讨论",1],
["disease","/dɪ'ziːz/","n. 疾病",1],
["display","/dɪ'spleɪ/","n./v. 展示",1],
["distance","/'dɪstəns/","n. 距离",1],
["distinguish","/dɪ'stɪŋgwɪʃ/","v. 区分",2],
["distribute","/dɪ'strɪbjuːt/","v. 分配，分发",2],
["district","/'dɪstrɪkt/","n. 地区",2],
["disturb","/dɪ'stɜːb/","v. 打扰",2],
["divide","/dɪ'vaɪd/","v. 分开，划分",1],
["document","/'dɒkjumənt/","n. 文件",1],
["domestic","/də'mestɪk/","a. 国内的，家庭的",2],
["dominate","/'dɒmɪneɪt/","v. 支配，主导",3],
["doubt","/daʊt/","n./v. 怀疑",1],
["draft","/drɑːft/","n. 草稿 v. 起草",2],
["drag","/dræg/","v. 拖",2],
["drama","/'drɑːmə/","n. 戏剧",2],
["dramatic","/drə'mætɪk/","a. 戏剧性的，显著的",2],
["draw","/drɔː/","v. 画，拉，吸引",1],
["dream","/driːm/","n./v. 梦想",1],
["dress","/dres/","n. 连衣裙 v. 穿衣",1],
["drop","/drɒp/","v. 掉落 n. 滴",1],
["due","/djuː/","a. 到期的，due to 由于",2],
["duty","/'djuːtɪ/","n. 责任，职责",1],
["eager","/'iːgə/","a. 渴望的",2],
["earn","/ɜːn/","v. 赚，获得",1],
["ease","/iːz/","n. 容易 v. 减轻",2],
["economic","/ˌiːkə'nɒmɪk/","a. 经济的",1],
["economy","/ɪ'kɒnəmɪ/","n. 经济",1],
["edge","/edʒ/","n. 边缘",1],
["edit","/'edɪt/","v. 编辑",2],
["educate","/'edʒukeɪt/","v. 教育",1],
["effect","/ɪ'fekt/","n. 效果，影响",1],
["effective","/ɪ'fektɪv/","a. 有效的",1],
["efficient","/ɪ'fɪʃnt/","a. 高效的",2],
["effort","/'efət/","n. 努力",1],
["either","/'aɪðə/","a./pron. 两者之一",1],
["elect","/ɪ'lekt/","v. 选举",2],
["electric","/ɪ'lektrɪk/","a. 电的",1],
["element","/'elɪmənt/","n. 元素，要素",1],
["eliminate","/ɪ'lɪmɪneɪt/","v. 消除",3],
["else","/els/","ad. 别的，其他",1],
["embarrass","/ɪm'bærəs/","v. 使尴尬",2],
["emerge","/ɪ'mɜːdʒ/","v. 出现，浮现",2],
["emergency","/ɪ'mɜːdʒənsɪ/","n. 紧急情况",2],
["emotion","/ɪ'məʊʃn/","n. 情感",1],
["emphasize","/'emfəsaɪz/","v. 强调",2],
["employ","/ɪm'plɔɪ/","v. 雇用，使用",1],
["empty","/'emptɪ/","a. 空的",1],
["enable","/ɪ'neɪbl/","v. 使能够",1],
["encourage","/ɪn'kʌrɪdʒ/","v. 鼓励",1],
["endure","/ɪn'djʊə/","v. 忍受",3],
["enemy","/'enəmɪ/","n. 敌人",1],
["energy","/'enədʒɪ/","n. 能量，精力",1],
["engage","/ɪn'geɪdʒ/","v. 从事，吸引",2],
["engine","/'endʒɪn/","n. 发动机",1],
["enhance","/ɪn'hɑːns/","v. 提高，增强",3],
["enormous","/ɪ'nɔːməs/","a. 巨大的",2],
["ensure","/ɪn'ʃʊə/","v. 确保",2],
["enter","/'entə/","v. 进入",1],
["enterprise","/'entəpraɪz/","n. 企业",2],
["entertainment","/ˌentə'teɪnmənt/","n. 娱乐",1],
["enthusiasm","/ɪn'θjuːzɪæzəm/","n. 热情",3],
["entire","/ɪn'taɪə/","a. 整个的",1],
["entitle","/ɪn'taɪtl/","v. 使有资格，给…title",3],
["environment","/ɪn'vaɪrənmənt/","n. 环境",1],
["equal","/'iːkwəl/","a. 相等的",1],
["equipment","/ɪ'kwɪpmənt/","n. 设备",1],
["error","/'erə/","n. 错误",1],
["escape","/ɪ'skeɪp/","v./n. 逃跑",1],
["especially","/ɪ'speʃəlɪ/","ad. 尤其",1],
["essential","/ɪ'senʃl/","a. 必要的，本质的",2],
["establish","/ɪ'stæblɪʃ/","v. 建立",1],
["estimate","/'estɪmeɪt/","v./n. 估计",2],
["evaluate","/ɪ'væljueɪt/","v. 评估",2],
["eventually","/ɪ'ventʃuəlɪ/","ad. 最终",2],
["evidence","/'evɪdəns/","n. 证据",1],
["evident","/'evɪdənt/","a. 明显的",2],
["exact","/ɪg'zækt/","a. 精确的",1],
["examine","/ɪg'zæmɪn/","v. 检查",1],
["exceed","/ɪk'siːd/","v. 超过",3],
["excellent","/'eksələnt/","a. 优秀的",1],
["except","/ɪk'sept/","prep. 除…之外",1],
["exchange","/ɪks'tʃeɪndʒ/","n./v. 交换",1],
["excite","/ɪk'saɪt/","v. 使兴奋",1],
["exclude","/ɪk'skluːd/","v. 排除",3],
["excuse","/ɪk'skjuːs/","n. 借口 v. 原谅",1],
["execute","/'eksɪkjuːt/","v. 执行",3],
["exercise","/'eksəsaɪz/","n./v. 锻炼，练习",1],
["exhaust","/ɪg'zɔːst/","v. 使精疲力尽，耗尽",3],
["exhibit","/ɪg'zɪbɪt/","v. 展览 n. 展品",2],
["exist","/ɪg'zɪst/","v. 存在",1],
["expand","/ɪk'spænd/","v. 扩展",2],
["expect","/ɪk'spekt/","v. 期望",1],
["expense","/ɪk'spens/","n. 费用",1],
["expensive","/ɪk'spensɪv/","a. 昂贵的",1],
["experience","/ɪk'spɪərɪəns/","n. 经验 v. 经历",1],
["experiment","/ɪk'sperɪmənt/","n. 实验",1],
["expert","/'ekspɜːt/","n. 专家",1],
["explain","/ɪk'spleɪn/","v. 解释",1],
["explore","/ɪk'splɔː/","v. 探索",1],
["export","/'ekspɔːt/","n./v. 出口",2],
["expose","/ɪk'spəʊz/","v. 暴露",2],
["express","/ɪk'spres/","v. 表达 a. 快速的",1],
["extend","/ɪk'stend/","v. 延伸，扩展",2],
["extent","/ɪk'stent/","n. 程度，范围",2],
["external","/ɪk'stɜːnl/","a. 外部的",2],
["extra","/'ekstrə/","a. 额外的",1],
["extreme","/ɪk'striːm/","a. 极端的",2],
["facility","/fə'sɪlətɪ/","n. 设施",2],
["factor","/'fæktə/","n. 因素",1],
["fade","/feɪd/","v. 褪色，消退",2],
["fail","/feɪl/","v. 失败",1],
["fair","/feə/","a. 公平的 n. 集市",1],
["faith","/feɪθ/","n. 信任，信仰",2],
["false","/fɔːls/","a. 错误的，假的",1],
["fame","/feɪm/","n. 名声",2],
["familiar","/fə'mɪlɪə/","a. 熟悉的",1],
["famous","/'feɪməs/","a. 著名的",1],
["fancy","/'fænsɪ/","a. 花哨的 v. 想象",2],
["fashion","/'fæʃn/","n. 时尚，方式",1],
["fasten","/'fɑːsn/","v. 系紧",2],
["fault","/fɔːlt/","n. 过错，缺点",1],
["favor","/'feɪvə/","n. 恩惠 v. 赞成",1],
["favorite","/'feɪvərɪt/","a. 最喜欢的",1],
["fear","/fɪə/","n./v. 害怕",1],
["feature","/'fiːtʃə/","n. 特征",1],
["fee","/fiː/","n. 费用",1],
["feed","/fiːd/","v. 喂养",1],
["feeling","/'fiːlɪŋ/","n. 感觉",1],
["fellow","/'feləʊ/","n. 家伙，同伴",2],
["female","/'fiːmeɪl/","a. 女性的",1],
["fetch","/fetʃ/","v. 去取来",2],
["field","/fiːld/","n. 田野，领域",1],
["fierce","/fɪəs/","a. 凶猛的，激烈的",2],
["figure","/'fɪgə/","n. 数字，人物 v. 认为",1],
["file","/faɪl/","n. 文件 v. 归档",1],
["fill","/fɪl/","v. 填满",1],
["film","/fɪlm/","n. 电影，胶片",1],
["final","/'faɪnl/","a. 最后的",1],
["finance","/'faɪnæns/","n. 财政 v. 提供资金",2],
["financial","/faɪ'nænʃl/","a. 财政的",2],
["find","/faɪnd/","v. 发现",1],
["fine","/faɪn/","a. 好的 n. 罚款",1],
["finish","/'fɪnɪʃ/","v. 完成",1],
["fire","/'faɪə/","n. 火 v. 解雇",1],
["firm","/fɜːm/","n. 公司 a. 坚定的",1],
["fit","/fɪt/","v. 适合 a. 健康的",1],
["fix","/fɪks/","v. 修理，固定",1],
["flame","/fleɪm/","n. 火焰",2],
["flash","/flæʃ/","n./v. 闪光",2],
["flat","/flæt/","a. 平的 n. 公寓",1],
["flee","/fliː/","v. 逃跑",3],
["flexible","/'fleksəbl/","a. 灵活的",2],
["float","/fləʊt/","v. 漂浮",2],
["flood","/flʌd/","n. 洪水",1],
["flow","/fləʊ/","v./n. 流动",1],
["fluent","/'fluːənt/","a. 流利的",2],
["focus","/'fəʊkəs/","v. 集中 n. 焦点",1],
["fold","/fəʊld/","v. 折叠",2],
["follow","/'fɒləʊ/","v. 跟随，遵循",1],
["fond","/fɒnd/","a. 喜爱的（of）",2],
["force","/fɔːs/","n. 力量 v. 强迫",1],
["forecast","/'fɔːkɑːst/","n./v. 预报",2],
["foreign","/'fɒrən/","a. 外国的",1],
["forever","/fə'revə/","ad. 永远",1],
["forget","/fə'get/","v. 忘记",1],
["forgive","/fə'gɪv/","v. 原谅",1],
["form","/fɔːm/","n. 形式，表格 v. 形成",1],
["formal","/'fɔːml/","a. 正式的",1],
["former","/'fɔːmə/","a. 前者的，以前的",2],
["fortune","/'fɔːtʃuːn/","n. 财富，运气",2],
["forward","/'fɔːwəd/","ad. 向前",1],
["found","/faʊnd/","v. 建立，创办",2],
["frame","/freɪm/","n. 框架",2],
["free","/friː/","a. 自由的，免费的",1],
["freedom","/'friːdəm/","n. 自由",1],
["freeze","/friːz/","v. 冻结",1],
["frequent","/'friːkwənt/","a. 频繁的",2],
["fresh","/freʃ/","a. 新鲜的",1],
["friendly","/'frendlɪ/","a. 友好的",1],
["frighten","/'fraɪtn/","v. 使害怕",2],
["front","/frʌnt/","n. 前面",1],
["fuel","/'fjuːəl/","n. 燃料",1],
["fulfill","/fʊl'fɪl/","v. 履行，实现",2],
["function","/'fʌŋkʃn/","n. 功能 v. 运作",1],
["fund","/fʌnd/","n. 基金 v. 资助",2],
["fundamental","/ˌfʌndə'mentl/","a. 基本的",2],
["furniture","/'fɜːnɪtʃə/","n. 家具（不可数）",1],
["further","/'fɜːðə/","a./ad. 进一步",1],
["future","/'fjuːtʃə/","n. 未来",1],
["gain","/geɪn/","v. 获得 n. 收益",1],
["gap","/gæp/","n. 差距，间隙",1],
["gather","/'gæðə/","v. 聚集",1],
["general","/'dʒenrəl/","a. 一般的 n. 将军",1],
["generate","/'dʒenəreɪt/","v. 产生",2],
["generation","/ˌdʒenə'reɪʃn/","n. 一代",1],
["generous","/'dʒenərəs/","a. 慷慨的",2],
["gentle","/'dʒentl/","a. 温和的",1],
["genuine","/'dʒenjuɪn/","a. 真正的",3],
["gesture","/'dʒestʃə/","n. 手势",2],
["gift","/gɪft/","n. 礼物，天赋",1],
["glance","/glɑːns/","v./n. 瞥一眼",2],
["global","/'gləʊbl/","a. 全球的",1],
["glory","/'glɔːrɪ/","n. 荣耀",2],
["goal","/gəʊl/","n. 目标",1],
["govern","/'gʌvn/","v. 统治，管理",2],
["grade","/greɪd/","n. 年级，等级",1],
["gradual","/'grædʒuəl/","a. 逐渐的",2],
["grain","/greɪn/","n. 谷物，颗粒",2],
["grant","/grɑːnt/","v. 授予 n. 拨款",2],
["grasp","/grɑːsp/","v. 抓住，理解",2],
["grateful","/'greɪtfl/","a. 感激的",2],
["greet","/griːt/","v. 问候",1],
["grow","/grəʊ/","v. 生长，成长",1],
["guarantee","/ˌgærən'tiː/","n./v. 保证",2],
["guard","/gɑːd/","n. 警卫 v. 守卫",1],
["guess","/ges/","v. 猜测",1],
["guest","/gest/","n. 客人",1],
["guide","/gaɪd/","n. 指南 v. 引导",1],
["guilty","/'gɪltɪ/","a. 有罪的，内疚的",2],
["habit","/'hæbɪt/","n. 习惯",1],
["handle","/'hændl/","v. 处理 n. 把手",1],
["hang","/hæŋ/","v. 悬挂",1],
["happen","/'hæpən/","v. 发生",1],
["harbor","/'hɑːbə/","n. 港口",2],
["hardly","/'hɑːdlɪ/","ad. 几乎不",1],
["harm","/hɑːm/","n./v. 伤害",1],
["harvest","/'hɑːvɪst/","n./v. 收获",2],
["hate","/heɪt/","v. 憎恨",1],
["head","/hed/","n. 头 v. 前往",1],
["heal","/hiːl/","v. 治愈",2],
["health","/helθ/","n. 健康",1],
["heat","/hiːt/","n. 热 v. 加热",1],
["heavy","/'hevɪ/","a. 重的",1],
["height","/haɪt/","n. 高度",1],
["hesitate","/'hezɪteɪt/","v. 犹豫",2],
["hide","/haɪd/","v. 隐藏",1],
["highly","/'haɪlɪ/","ad. 高度地，非常",1],
["hire","/'haɪə/","v. 雇用，租用",1],
["historical","/hɪ'stɒrɪkl/","a. 历史的",1],
["hit","/hɪt/","v. 打击 n. 热门",1],
["hold","/həʊld/","v. 拿着，举行",1],
["hole","/həʊl/","n. 洞",1],
["holiday","/'hɒlədeɪ/","n. 假日",1],
["honest","/'ɒnɪst/","a. 诚实的",1],
["honor","/'ɒnə/","n. 荣誉 v. 尊敬",1],
["hope","/həʊp/","n./v. 希望",1],
["horrible","/'hɒrəbl/","a. 可怕的",2],
["host","/həʊst/","n. 主人 v. 主办",1],
["however","/haʊ'evə/","ad. 然而",1],
["huge","/hjuːdʒ/","a. 巨大的",1],
["human","/'hjuːmən/","a. 人类的 n. 人",1],
["humor","/'hjuːmə/","n. 幽默",1],
["hunt","/hʌnt/","v. 打猎，搜寻",1],
["hurry","/'hʌrɪ/","v. 赶快",1],
["hurt","/hɜːt/","v. 伤害",1],
["idea","/aɪ'dɪə/","n. 主意，想法",1],
["ideal","/aɪ'dɪəl/","a. 理想的",1],
["identify","/aɪ'dentɪfaɪ/","v. 识别，确认",2],
["ignore","/ɪg'nɔː/","v. 忽视",1],
["illegal","/ɪ'liːgl/","a. 非法的",2],
["illustrate","/'ɪləstreɪt/","v. 说明，图解",2],
["image","/'ɪmɪdʒ/","n. 形象，图像",1],
["imagine","/ɪ'mædʒɪn/","v. 想象",1],
["immediate","/ɪ'miːdɪət/","a. 立即的",1],
["impact","/'ɪmpækt/","n. 影响，冲击",2],
["imply","/ɪm'plaɪ/","v. 暗示",2],
["import","/'ɪmpɔːt/","n./v. 进口",2],
["impose","/ɪm'pəʊz/","v. 强加",3],
["impress","/ɪm'pres/","v. 给…留下印象",1],
["improve","/ɪm'pruːv/","v. 改善",1],
["include","/ɪn'kluːd/","v. 包括",1],
["income","/'ɪnkʌm/","n. 收入",1],
["increase","/ɪn'kriːs/","v./n. 增加",1],
["indeed","/ɪn'diːd/","ad. 确实",1],
["independent","/ˌɪndɪ'pendənt/","a. 独立的",1],
["indicate","/'ɪndɪkeɪt/","v. 表明，指示",2],
["individual","/ˌɪndɪ'vɪdʒuəl/","a. 个人的 n. 个人",1],
["industry","/'ɪndəstrɪ/","n. 工业，行业",1],
["influence","/'ɪnfluəns/","n./v. 影响",1],
["inform","/ɪn'fɔːm/","v. 通知",1],
["initial","/ɪ'nɪʃl/","a. 最初的",2],
["injure","/'ɪndʒə/","v. 伤害",1],
["inner","/'ɪnə/","a. 内部的",2],
["innocent","/'ɪnəsnt/","a. 无辜的，天真的",2],
["inquire","/ɪn'kwaɪə/","v. 询问",2],
["insist","/ɪn'sɪst/","v. 坚持",1],
["inspect","/ɪn'spekt/","v. 检查",2],
["inspire","/ɪn'spaɪə/","v. 激励，启发",2],
["install","/ɪn'stɔːl/","v. 安装",2],
["instance","/'ɪnstəns/","n. 例子",1],
["instant","/'ɪnstənt/","a. 立即的",2],
["instead","/ɪn'sted/","ad. 代替，反而",1],
["institute","/'ɪnstɪtjuːt/","n. 机构，学院",2],
["instruct","/ɪn'strʌkt/","v. 指导，命令",2],
["instrument","/'ɪnstrəmənt/","n. 工具，乐器",1],
["insurance","/ɪn'ʃʊərəns/","n. 保险",2],
["intend","/ɪn'tend/","v. 打算",1],
["intense","/ɪn'tens/","a. 强烈的",3],
["intention","/ɪn'tenʃn/","n. 意图",2],
["interest","/'ɪntrəst/","n. 兴趣，利息",1],
["interfere","/ˌɪntə'fɪə/","v. 干涉",3],
["internal","/ɪn'tɜːnl/","a. 内部的",2],
["interpret","/ɪn'tɜːprɪt/","v. 解释，口译",2],
["interrupt","/ˌɪntə'rʌpt/","v. 打断",2],
["interview","/'ɪntəvjuː/","n./v. 面试，采访",1],
["introduce","/ˌɪntrə'djuːs/","v. 介绍，引进",1],
["invent","/ɪn'vent/","v. 发明",1],
["invest","/ɪn'vest/","v. 投资",2],
["investigate","/ɪn'vestɪgeɪt/","v. 调查",2],
["invite","/ɪn'vaɪt/","v. 邀请",1],
["involve","/ɪn'vɒlv/","v. 涉及，包含",1],
["isolate","/'aɪsəleɪt/","v. 隔离",3],
["issue","/'ɪʃuː/","n. 问题，期刊 v. 发行",1],
["item","/'aɪtəm/","n. 项目，条款",1],
["join","/dʒɔɪn/","v. 加入，连接",1],
["joint","/dʒɔɪnt/","a. 共同的 n. 关节",2],
["journal","/'dʒɜːnl/","n. 期刊，日志",2],
["journey","/'dʒɜːnɪ/","n. 旅程",1],
["judge","/dʒʌdʒ/","n. 法官 v. 判断",1],
["justice","/'dʒʌstɪs/","n. 正义，司法",2],
["justify","/'dʒʌstɪfaɪ/","v. 证明…正当",3],
["keen","/kiːn/","a. 热衷的，敏锐的",2],
["keep","/kiːp/","v. 保持，保存",1],
["key","/kiː/","n. 钥匙，关键 a. 关键的",1],
["kill","/kɪl/","v. 杀死",1],
["kind","/kaɪnd/","n. 种类 a. 友善的",1],
["knock","/nɒk/","v. 敲",1],
["knowledge","/'nɒlɪdʒ/","n. 知识",1],
["labor","/'leɪbə/","n. 劳动，劳工",1],
["lack","/læk/","n./v. 缺乏",1],
["land","/lænd/","n. 土地 v. 着陆",1],
["language","/'læŋgwɪdʒ/","n. 语言",1],
["large","/lɑːdʒ/","a. 大的",1],
["last","/lɑːst/","a. 最后的 v. 持续",1],
["late","/leɪt/","a. 晚的",1],
["latter","/'lætə/","a. 后者的",2],
["laugh","/lɑːf/","v. 笑",1],
["launch","/lɔːntʃ/","v. 发射，发起",2],
["law","/lɔː/","n. 法律",1],
["lay","/leɪ/","v. 放置，铺设",1],
["lead","/liːd/","v. 领导，导致",1],
["leading","/'liːdɪŋ/","a. 主要的",1],
["league","/liːg/","n. 联盟",2],
["lean","/liːn/","v. 倾斜，依靠",2],
["learn","/lɜːn/","v. 学习，得知",1],
["least","/liːst/","a. 最少的",1],
["leave","/liːv/","v. 离开，留下",1],
["lecture","/'lektʃə/","n. 讲座",1],
["legal","/'liːgl/","a. 合法的",2],
["lend","/lend/","v. 借出",1],
["length","/leŋθ/","n. 长度",1],
["less","/les/","a. 更少的",1],
["lesson","/'lesn/","n. 课，教训",1],
["level","/'levl/","n. 水平，层次",1],
["liberal","/'lɪbərəl/","a. 自由的",3],
["library","/'laɪbrərɪ/","n. 图书馆",1],
["license","/'laɪsns/","n. 执照",2],
["lie","/laɪ/","v. 躺，位于，说谎",1],
["lift","/lɪft/","v. 举起 n. 电梯",1],
["light","/laɪt/","n. 光 a. 轻的",1],
["likely","/'laɪklɪ/","a. 可能的",1],
["limit","/'lɪmɪt/","n./v. 限制",1],
["link","/lɪŋk/","n./v. 连接",1],
["liquid","/'lɪkwɪd/","n. 液体",1],
["list","/lɪst/","n. 清单 v. 列出",1],
["literature","/'lɪtrətʃə/","n. 文学",2],
["load","/ləʊd/","n. 负载 v. 装载",1],
["loan","/ləʊn/","n. 贷款",2],
["local","/'ləʊkl/","a. 当地的",1],
["locate","/ləʊ'keɪt/","v. 位于，找到",1],
["lock","/lɒk/","n. 锁 v. 锁上",1],
["logical","/'lɒdʒɪkl/","a. 合乎逻辑的",2],
["lonely","/'ləʊnlɪ/","a. 孤独的",1],
["loose","/luːs/","a. 松的",2],
["lose","/luːz/","v. 丢失，输",1],
["loss","/lɒs/","n. 损失",1],
["loud","/laʊd/","a. 大声的",1],
["love","/lʌv/","n./v. 爱",1],
["lower","/'ləʊə/","v. 降低 a. 较低的",1],
["luck","/lʌk/","n. 运气",1],
["luxury","/'lʌkʃərɪ/","n. 奢侈品",3],
["machine","/mə'ʃiːn/","n. 机器",1],
["magazine","/ˌmægə'ziːn/","n. 杂志",1],
["main","/meɪn/","a. 主要的",1],
["maintain","/meɪn'teɪn/","v. 维持，保养",1],
["major","/'meɪdʒə/","a. 主要的 n. 专业",1],
["majority","/mə'dʒɒrətɪ/","n. 大多数",1],
["make","/meɪk/","v. 制造，使得",1],
["male","/meɪl/","a. 男性的",1],
["manage","/'mænɪdʒ/","v. 管理，设法做到",1],
["manner","/'mænə/","n. 方式，举止",1],
["manufacture","/ˌmænju'fæktʃə/","v./n. 制造",2],
["margin","/'mɑːdʒɪn/","n. 边缘，利润",3],
["mark","/mɑːk/","n. 标记，分数 v. 标记",1],
["market","/'mɑːkɪt/","n. 市场",1],
["marry","/'mærɪ/","v. 结婚",1],
["mass","/mæs/","n. 大量，群众",1],
["master","/'mɑːstə/","n. 主人 v. 掌握",1],
["match","/mætʃ/","n. 比赛，火柴 v. 匹配",1],
["material","/mə'tɪərɪəl/","n. 材料",1],
["matter","/'mætə/","n. 事情 v. 要紧",1],
["mature","/mə'tʃʊə/","a. 成熟的",2],
["maximum","/'mæksɪməm/","n./a. 最大（的）",2],
["mean","/miːn/","v. 意味 a. 吝啬的",1],
["means","/miːnz/","n. 方法，手段",1],
["measure","/'meʒə/","v. 测量 n. 措施",1],
["mechanic","/mɪ'kænɪk/","n. 技工",2],
["media","/'miːdɪə/","n. 媒体",1],
["medical","/'medɪkl/","a. 医学的",1],
["medicine","/'medsn/","n. 药，医学",1],
["medium","/'miːdɪəm/","a. 中等的 n. 媒介",1],
["meet","/miːt/","v. 遇见，满足",1],
["member","/'membə/","n. 成员",1],
["memory","/'memərɪ/","n. 记忆",1],
["mental","/'mentl/","a. 精神的",1],
["mention","/'menʃn/","v. 提及",1],
["mercy","/'mɜːsɪ/","n. 仁慈",3],
["mere","/mɪə/","a. 仅仅的",2],
["message","/'mesɪdʒ/","n. 消息",1],
["method","/'meθəd/","n. 方法",1],
["middle","/'mɪdl/","n./a. 中间（的）",1],
["might","/maɪt/","aux. 可能 n. 力量",1],
["mind","/maɪnd/","n. 头脑 v. 介意",1],
["minimum","/'mɪnɪməm/","n./a. 最小（的）",2],
["minister","/'mɪnɪstə/","n. 部长",2],
["minor","/'maɪnə/","a. 次要的",2],
["minute","/'mɪnɪt/","n. 分钟",1],
["miss","/mɪs/","v. 错过，想念",1],
["mistake","/mɪ'steɪk/","n. 错误",1],
["mix","/mɪks/","v. 混合",1],
["mobile","/'məʊbaɪl/","a. 移动的",1],
["model","/'mɒdl/","n. 模型，模特",1],
["modern","/'mɒdn/","a. 现代的",1],
["modest","/'mɒdɪst/","a. 谦虚的，适度的",3],
["modify","/'mɒdɪfaɪ/","v. 修改",2],
["moment","/'məʊmənt/","n. 时刻",1],
["monitor","/'mɒnɪtə/","n. 显示器 v. 监控",2],
["mood","/muːd/","n. 心情",1],
["moral","/'mɒrəl/","a. 道德的",2],
["moreover","/mɔːr'əʊvə/","ad. 此外",2],
["motion","/'məʊʃn/","n. 运动",2],
["motivate","/'məʊtɪveɪt/","v. 激励",2],
["move","/muːv/","v. 移动，感动",1],
["multiple","/'mʌltɪpl/","a. 多重的",2],
["murder","/'mɜːdə/","n./v. 谋杀",2],
["mutual","/'mjuːtʃuəl/","a. 相互的",3],
["mystery","/'mɪstərɪ/","n. 神秘",2],
["narrow","/'nærəʊ/","a. 狭窄的",1],
["nation","/'neɪʃn/","n. 国家，民族",1],
["native","/'neɪtɪv/","a. 本地的",1],
["natural","/'nætʃrəl/","a. 自然的",1],
["nature","/'neɪtʃə/","n. 自然，本性",1],
["nearly","/'nɪəlɪ/","ad. 几乎",1],
["necessary","/'nesəsərɪ/","a. 必要的",1],
["negative","/'negətɪv/","a. 消极的，负的",1],
["neglect","/nɪ'glekt/","v. 忽视",2],
["negotiate","/nɪ'gəʊʃɪeɪt/","v. 谈判",3],
["neighbor","/'neɪbə/","n. 邻居",1],
["neither","/'naɪðə/","a./pron. 两者都不",1],
["nerve","/nɜːv/","n. 神经，勇气",2],
["nervous","/'nɜːvəs/","a. 紧张的",1],
["network","/'netwɜːk/","n. 网络",1],
["nevertheless","/ˌnevəðə'les/","ad. 然而",2],
["normal","/'nɔːml/","a. 正常的",1],
["note","/nəʊt/","n. 笔记 v. 注意",1],
["notice","/'nəʊtɪs/","n. 通知 v. 注意到",1],
["notion","/'nəʊʃn/","n. 概念",3],
["novel","/'nɒvl/","n. 小说 a. 新颖的",1],
["nowadays","/'naʊədeɪz/","ad. 如今",1],
["nuclear","/'njuːklɪə/","a. 核的",2],
["numerous","/'njuːmərəs/","a. 众多的",2],
["obey","/ə'beɪ/","v. 服从",1],
["object","/'ɒbdʒɪkt/","n. 物体，宾语 v. 反对",1],
["objective","/əb'dʒektɪv/","n. 目标 a. 客观的",2],
["oblige","/ə'blaɪdʒ/","v. 迫使，使感激",3],
["observe","/əb'zɜːv/","v. 观察，遵守",1],
["obtain","/əb'teɪn/","v. 获得",2],
["obvious","/'ɒbvɪəs/","a. 明显的",1],
["occasion","/ə'keɪʒn/","n. 场合，时机",1],
["occupy","/'ɒkjupaɪ/","v. 占据",2],
["occur","/ə'kɜː/","v. 发生",1],
["offer","/'ɒfə/","v. 提供 n. 提议",1],
["official","/ə'fɪʃl/","a. 官方的 n. 官员",1],
["operate","/'ɒpəreɪt/","v. 操作，手术",1],
["opinion","/ə'pɪnjən/","n. 意见",1],
["opportunity","/ˌɒpə'tjuːnətɪ/","n. 机会",1],
["oppose","/ə'pəʊz/","v. 反对",2],
["opposite","/'ɒpəzɪt/","a. 相反的",1],
["option","/'ɒpʃn/","n. 选择",2],
["order","/'ɔːdə/","n. 命令，订单，顺序",1],
["ordinary","/'ɔːdnrɪ/","a. 普通的",1],
["organize","/'ɔːgənaɪz/","v. 组织",1],
["origin","/'ɒrɪdʒɪn/","n. 起源",2],
["original","/ə'rɪdʒənl/","a. 原来的，独创的",1],
["otherwise","/'ʌðəwaɪz/","ad. 否则",1],
["outcome","/'aʊtkʌm/","n. 结果",2],
["outline","/'aʊtlaɪn/","n. 大纲，轮廓",2],
["output","/'aʊtpʊt/","n. 产出",2],
["outstanding","/aʊt'stændɪŋ/","a. 杰出的",2],
["overcome","/ˌəʊvə'kʌm/","v. 克服",2],
["overlook","/ˌəʊvə'lʊk/","v. 忽视，俯瞰",3],
["owe","/əʊ/","v. 欠",1],
["own","/əʊn/","a. 自己的 v. 拥有",1],
["pace","/peɪs/","n. 步伐，速度",2],
["pack","/pæk/","v. 打包 n. 包",1],
["pain","/peɪn/","n. 疼痛",1],
["paint","/peɪnt/","v. 绘画，油漆",1],
["panel","/'pænl/","n. 面板，专门小组",3],
["parallel","/'pærəlel/","a. 平行的",2],
["participate","/pɑː'tɪsɪpeɪt/","v. 参与",2],
["particular","/pə'tɪkjələ/","a. 特别的",1],
["partner","/'pɑːtnə/","n. 伙伴",1],
["passage","/'pæsɪdʒ/","n. 段落，通道",1],
["passenger","/'pæsɪndʒə/","n. 乘客",1],
["passion","/'pæʃn/","n. 激情",2],
["passive","/'pæsɪv/","a. 被动的",2],
["path","/pɑːθ/","n. 路径",1],
["patience","/'peɪʃns/","n. 耐心",1],
["patient","/'peɪʃnt/","n. 病人 a. 耐心的",1],
["pattern","/'pætn/","n. 模式，图案",1],
["pause","/pɔːz/","v./n. 暂停",2],
["pay","/peɪ/","v. 支付",1],
["peace","/piːs/","n. 和平",1],
["peak","/piːk/","n. 顶峰",2],
["peculiar","/pɪ'kjuːlɪə/","a. 奇怪的，特有的",3],
["perceive","/pə'siːv/","v. 察觉，认为",3],
["percentage","/pə'sentɪdʒ/","n. 百分比",1],
["perfect","/'pɜːfɪkt/","a. 完美的",1],
["perform","/pə'fɔːm/","v. 表演，执行",1],
["performance","/pə'fɔːməns/","n. 表演，表现",1],
["perhaps","/pə'hæps/","ad. 也许",1],
["period","/'pɪərɪəd/","n. 时期",1],
["permanent","/'pɜːmənənt/","a. 永久的",2],
["permit","/pə'mɪt/","v. 允许 n. 许可证",1],
["persist","/pə'sɪst/","v. 坚持",3],
["personal","/'pɜːsənl/","a. 个人的",1],
["personality","/ˌpɜːsə'nælətɪ/","n. 个性",1],
["persuade","/pə'sweɪd/","v. 说服",2],
["phenomenon","/fə'nɒmɪnən/","n. 现象",3],
["phrase","/freɪz/","n. 短语",1],
["physical","/'fɪzɪkl/","a. 身体的，物理的",1],
["pick","/pɪk/","v. 挑选，采摘",1],
["picture","/'pɪktʃə/","n. 图片",1],
["piece","/piːs/","n. 一块，一片",1],
["pile","/paɪl/","n. 堆 v. 堆积",2],
["pilot","/'paɪlət/","n. 飞行员",1],
["pity","/'pɪtɪ/","n. 遗憾，同情",1],
["place","/pleɪs/","n. 地方 v. 放置",1],
["plain","/pleɪn/","a. 朴素的，清楚的",1],
["plan","/plæn/","n./v. 计划",1],
["plant","/plɑːnt/","n. 植物，工厂 v. 种植",1],
["play","/pleɪ/","v. 玩，扮演 n. 戏剧",1],
["pleasant","/'pleznt/","a. 令人愉快的",1],
["please","/pliːz/","v. 使高兴",1],
["plenty","/'plentɪ/","n. 大量",1],
["plot","/plɒt/","n. 情节，阴谋",2],
["poem","/'pəʊɪm/","n. 诗",1],
["point","/pɔɪnt/","n. 点，观点 v. 指",1],
["policy","/'pɒləsɪ/","n. 政策",1],
["polite","/pə'laɪt/","a. 礼貌的",1],
["political","/pə'lɪtɪkl/","a. 政治的",1],
["pollution","/pə'luːʃn/","n. 污染",1],
["popular","/'pɒpjələ/","a. 流行的",1],
["population","/ˌpɒpju'leɪʃn/","n. 人口",1],
["portion","/'pɔːʃn/","n. 部分",2],
["position","/pə'zɪʃn/","n. 位置，职位",1],
["positive","/'pɒzətɪv/","a. 积极的，正的",1],
["possess","/pə'zes/","v. 拥有",2],
["possible","/'pɒsəbl/","a. 可能的",1],
["potential","/pə'tenʃl/","a. 潜在的 n. 潜力",2],
["pour","/pɔː/","v. 倾倒",1],
["poverty","/'pɒvətɪ/","n. 贫穷",2],
["power","/'paʊə/","n. 力量，权力，电力",1],
["practical","/'præktɪkl/","a. 实际的",1],
["practice","/'præktɪs/","n./v. 练习",1],
["praise","/preɪz/","n./v. 赞扬",1],
["precise","/prɪ'saɪs/","a. 精确的",2],
["predict","/prɪ'dɪkt/","v. 预测",2],
["prefer","/prɪ'fɜː/","v. 更喜欢",1],
["prejudice","/'predʒudɪs/","n. 偏见",3],
["prepare","/prɪ'peə/","v. 准备",1],
["present","/'preznt/","a. 现在的 n. 礼物 v. 呈现",1],
["preserve","/prɪ'zɜːv/","v. 保存",2],
["press","/pres/","v. 按压 n. 新闻界",1],
["pressure","/'preʃə/","n. 压力",1],
["pretend","/prɪ'tend/","v. 假装",2],
["prevent","/prɪ'vent/","v. 防止",1],
["previous","/'priːvɪəs/","a. 先前的",1],
["price","/praɪs/","n. 价格",1],
["pride","/praɪd/","n. 骄傲",1],
["primary","/'praɪmərɪ/","a. 主要的，初级的",1],
["principle","/'prɪnsəpl/","n. 原则",2],
["print","/prɪnt/","v. 打印",1],
["prior","/'praɪə/","a. 先前的（to）",3],
["priority","/praɪ'ɒrətɪ/","n. 优先",2],
["private","/'praɪvət/","a. 私人的",1],
["privilege","/'prɪvəlɪdʒ/","n. 特权",3],
["prize","/praɪz/","n. 奖品",1],
["probably","/'prɒbəblɪ/","ad. 大概",1],
["problem","/'prɒbləm/","n. 问题",1],
["procedure","/prə'siːdʒə/","n. 程序",2],
["proceed","/prə'siːd/","v. 继续进行",3],
["process","/'prəʊses/","n. 过程 v. 处理",1],
["produce","/prə'djuːs/","v. 生产",1],
["product","/'prɒdʌkt/","n. 产品",1],
["profession","/prə'feʃn/","n. 职业",2],
["professional","/prə'feʃənl/","a. 专业的",1],
["profit","/'prɒfɪt/","n. 利润",1],
["progress","/'prəʊgres/","n. 进步",1],
["project","/'prɒdʒekt/","n. 项目",1],
["promise","/'prɒmɪs/","n./v. 承诺",1],
["promote","/prə'məʊt/","v. 促进，晋升",2],
["prompt","/prɒmpt/","a. 迅速的 v. 促使",3],
["proof","/pruːf/","n. 证据",2],
["proper","/'prɒpə/","a. 适当的",1],
["property","/'prɒpətɪ/","n. 财产，属性",2],
["proportion","/prə'pɔːʃn/","n. 比例",2],
["propose","/prə'pəʊz/","v. 提议，求婚",2],
["protect","/prə'tekt/","v. 保护",1],
["proud","/praʊd/","a. 骄傲的",1],
["prove","/pruːv/","v. 证明",1],
["provide","/prə'vaɪd/","v. 提供",1],
["public","/'pʌblɪk/","a. 公共的 n. 公众",1],
["publish","/'pʌblɪʃ/","v. 出版",1],
["pull","/pʊl/","v. 拉",1],
["punish","/'pʌnɪʃ/","v. 惩罚",1],
["purchase","/'pɜːtʃəs/","v./n. 购买",2],
["pure","/pjʊə/","a. 纯的",1],
["purpose","/'pɜːpəs/","n. 目的",1],
["pursue","/pə'sjuː/","v. 追求",2],
["push","/pʊʃ/","v. 推",1],
["qualify","/'kwɒlɪfaɪ/","v. 使合格",2],
["quality","/'kwɒlətɪ/","n. 质量，品质",1],
["quantity","/'kwɒntətɪ/","n. 数量",1],
["quarter","/'kwɔːtə/","n. 四分之一，季度",1],
["quiet","/'kwaɪət/","a. 安静的",1],
["quit","/kwɪt/","v. 放弃，辞职",1],
["quite","/kwaɪt/","ad. 相当",1],
["quote","/kwəʊt/","v. 引用",2],
["race","/reɪs/","n. 比赛，种族",1],
["radical","/'rædɪkl/","a. 激进的，根本的",3],
["raise","/reɪz/","v. 提高，抚养",1],
["random","/'rændəm/","a. 随机的",2],
["range","/reɪndʒ/","n. 范围 v. 排列",1],
["rank","/ræŋk/","n. 等级 v. 排名",2],
["rapid","/'ræpɪd/","a. 快速的",1],
["rare","/reə/","a. 稀有的",1],
["rate","/reɪt/","n. 比率，速度",1],
["rather","/'rɑːðə/","ad. 相当，宁愿",1],
["reach","/riːtʃ/","v. 到达，够到",1],
["react","/rɪ'ækt/","v. 反应",2],
["ready","/'redɪ/","a. 准备好的",1],
["real","/rɪəl/","a. 真实的",1],
["realize","/'rɪəlaɪz/","v. 意识到，实现",1],
["reason","/'riːzn/","n. 原因，理由",1],
["reasonable","/'riːznəbl/","a. 合理的",1],
["recall","/rɪ'kɔːl/","v. 回忆，召回",2],
["receive","/rɪ'siːv/","v. 收到",1],
["recent","/'riːsnt/","a. 最近的",1],
["recognize","/'rekəgnaɪz/","v. 认出，承认",1],
["recommend","/ˌrekə'mend/","v. 推荐",1],
["record","/'rekɔːd/","n. 记录 v. 录制",1],
["recover","/rɪ'kʌvə/","v. 恢复",1],
["reduce","/rɪ'djuːs/","v. 减少",1],
["refer","/rɪ'fɜː/","v. 提到，参考（to）",1],
["reflect","/rɪ'flekt/","v. 反射，反映",2],
["reform","/rɪ'fɔːm/","n./v. 改革",2],
["refuse","/rɪ'fjuːz/","v. 拒绝",1],
["regard","/rɪ'gɑːd/","v. 认为，看待",1],
["region","/'riːdʒən/","n. 地区",1],
["register","/'redʒɪstə/","v. 注册",2],
["regret","/rɪ'gret/","v./n. 后悔",1],
["regular","/'regjələ/","a. 规则的，定期的",1],
["regulate","/'regjuleɪt/","v. 管理，调节",2],
["reject","/rɪ'dʒekt/","v. 拒绝",2],
["relate","/rɪ'leɪt/","v. 联系，related to",1],
["relation","/rɪ'leɪʃn/","n. 关系",1],
["relative","/'relətɪv/","a. 相对的 n. 亲戚",1],
["relax","/rɪ'læks/","v. 放松",1],
["release","/rɪ'liːs/","v. 释放，发布",2],
["relevant","/'reləvənt/","a. 相关的",2],
["reliable","/rɪ'laɪəbl/","a. 可靠的",2],
["relief","/rɪ'liːf/","n. 减轻，宽慰",2],
["religion","/rɪ'lɪdʒən/","n. 宗教",2],
["reluctant","/rɪ'lʌktənt/","a. 不情愿的",3],
["rely","/rɪ'laɪ/","v. 依靠（on）",1],
["remain","/rɪ'meɪn/","v. 保持，剩余",1],
["remark","/rɪ'mɑːk/","n. 评论",2],
["remarkable","/rɪ'mɑːkəbl/","a. 显著的",2],
["remedy","/'remədɪ/","n. 补救，治疗",3],
["remind","/rɪ'maɪnd/","v. 提醒",1],
["remove","/rɪ'muːv/","v. 移除",1],
["repair","/rɪ'peə/","v./n. 修理",1],
["repeat","/rɪ'piːt/","v. 重复",1],
["replace","/rɪ'pleɪs/","v. 替换",1],
["reply","/rɪ'plaɪ/","v./n. 回复",1],
["report","/rɪ'pɔːt/","n./v. 报告",1],
["represent","/ˌreprɪ'zent/","v. 代表",1],
["reputation","/ˌrepju'teɪʃn/","n. 名声",2],
["request","/rɪ'kwest/","n./v. 请求",1],
["require","/rɪ'kwaɪə/","v. 需要，要求",1],
["rescue","/'reskjuː/","v./n. 营救",2],
["research","/rɪ'sɜːtʃ/","n./v. 研究",1],
["reserve","/rɪ'zɜːv/","v. 预订，保留",2],
["resident","/'rezɪdənt/","n. 居民",2],
["resist","/rɪ'zɪst/","v. 抵抗",2],
["resource","/rɪ'sɔːs/","n. 资源",1],
["respect","/rɪ'spekt/","n./v. 尊重",1],
["respond","/rɪ'spɒnd/","v. 回应",1],
["response","/rɪ'spɒns/","n. 回应",1],
["responsible","/rɪ'spɒnsəbl/","a. 负责的",1],
["rest","/rest/","n. 休息，剩余部分",1],
["restore","/rɪ'stɔː/","v. 恢复",2],
["restrict","/rɪ'strɪkt/","v. 限制",2],
["result","/rɪ'zʌlt/","n. 结果",1],
["retain","/rɪ'teɪn/","v. 保留",3],
["retire","/rɪ'taɪə/","v. 退休",1],
["reveal","/rɪ'viːl/","v. 揭示",2],
["reverse","/rɪ'vɜːs/","v. 颠倒 a. 相反的",2],
["review","/rɪ'vjuː/","n./v. 复习，评论",1],
["revise","/rɪ'vaɪz/","v. 修订，复习",2],
["reward","/rɪ'wɔːd/","n. 奖励",1],
["rid","/rɪd/","v. 摆脱（get rid of）",2],
["ridiculous","/rɪ'dɪkjələs/","a. 荒谬的",3],
["right","/raɪt/","a. 正确的 n. 权利",1],
["rise","/raɪz/","v. 上升",1],
["risk","/rɪsk/","n. 风险",1],
["role","/rəʊl/","n. 角色，作用",1],
["roll","/rəʊl/","v. 滚动",1],
["root","/ruːt/","n. 根",1],
["rough","/rʌf/","a. 粗糙的，大致的",2],
["round","/raʊnd/","a. 圆的 n. 回合",1],
["route","/ruːt/","n. 路线",2],
["routine","/ruː'tiːn/","n. 常规",2],
["row","/rəʊ/","n. 排，行",1],
["rub","/rʌb/","v. 摩擦",2],
["rule","/ruːl/","n. 规则 v. 统治",1],
["rural","/'rʊərəl/","a. 农村的",2],
["rush","/rʌʃ/","v. 冲，赶",1],
["sacrifice","/'sækrɪfaɪs/","n./v. 牺牲",2],
["safe","/seɪf/","a. 安全的",1],
["safety","/'seɪftɪ/","n. 安全",1],
["salary","/'sælərɪ/","n. 薪水",1],
["sample","/'sɑːmpl/","n. 样品",1],
["satisfy","/'sætɪsfaɪ/","v. 满足",1],
["save","/seɪv/","v. 拯救，节省",1],
["scale","/skeɪl/","n. 规模，刻度",2],
["scare","/skeə/","v. 惊吓",2],
["scene","/siːn/","n. 场景",1],
["schedule","/'ʃedjuːl/","n. 时间表 v. 安排",1],
["scheme","/skiːm/","n. 计划，方案",3],
["scholar","/'skɒlə/","n. 学者",2],
["science","/'saɪəns/","n. 科学",1],
["scope","/skəʊp/","n. 范围",3],
["score","/skɔː/","n. 分数 v. 得分",1],
["scratch","/skrætʃ/","v. 抓，刮",2],
["search","/sɜːtʃ/","v./n. 搜索",1],
["season","/'siːzn/","n. 季节",1],
["secret","/'siːkrət/","n. 秘密",1],
["section","/'sekʃn/","n. 部分，部门",1],
["secure","/sɪ'kjʊə/","a. 安全的 v. 保障",2],
["seek","/siːk/","v. 寻找",1],
["seem","/siːm/","v. 似乎",1],
["seize","/siːz/","v. 抓住",3],
["seldom","/'seldəm/","ad. 很少",2],
["select","/sɪ'lekt/","v. 选择",1],
["sense","/sens/","n. 感觉，意义",1],
["sensible","/'sensəbl/","a. 明智的",2],
["sensitive","/'sensətɪv/","a. 敏感的",2],
["separate","/'sepərət/","a. 分开的 v. 分离",1],
["series","/'sɪəriːz/","n. 系列",1],
["serious","/'sɪərɪəs/","a. 严肃的，严重的",1],
["serve","/sɜːv/","v. 服务",1],
["service","/'sɜːvɪs/","n. 服务",1],
["settle","/'setl/","v. 解决，定居",1],
["several","/'sevrəl/","a. 几个",1],
["severe","/sɪ'vɪə/","a. 严重的，严厉的",2],
["shade","/ʃeɪd/","n. 阴影",2],
["shake","/ʃeɪk/","v. 摇动",1],
["shallow","/'ʃæləʊ/","a. 浅的",2],
["shame","/ʃeɪm/","n. 羞耻，遗憾",1],
["shape","/ʃeɪp/","n. 形状",1],
["share","/ʃeə/","v. 分享 n. 份额",1],
["sharp","/ʃɑːp/","a. 锋利的，急剧的",1],
["shelter","/'ʃeltə/","n. 庇护所",2],
["shift","/ʃɪft/","v. 转移 n. 班次",2],
["shine","/ʃaɪn/","v. 照耀",1],
["shock","/ʃɒk/","n./v. 震惊",1],
["shoot","/ʃuːt/","v. 射击",1],
["shortage","/'ʃɔːtɪdʒ/","n. 短缺",2],
["shortly","/'ʃɔːtlɪ/","ad. 不久",2],
["shot","/ʃɒt/","n. 射击，投篮",1],
["show","/ʃəʊ/","v. 展示 n. 表演",1],
["shut","/ʃʌt/","v. 关闭",1],
["sight","/saɪt/","n. 视力，景象",1],
["sign","/saɪn/","n. 标志 v. 签名",1],
["signal","/'sɪgnəl/","n. 信号",1],
["significant","/sɪg'nɪfɪkənt/","a. 重要的，显著的",2],
["silence","/'saɪləns/","n. 沉默",1],
["silly","/'sɪlɪ/","a. 愚蠢的",1],
["similar","/'sɪmɪlə/","a. 相似的",1],
["simple","/'sɪmpl/","a. 简单的",1],
["since","/sɪns/","conj. 自从，既然",1],
["sincere","/sɪn'sɪə/","a. 真诚的",2],
["single","/'sɪŋgl/","a. 单一的，单身的",1],
["situation","/ˌsɪtʃu'eɪʃn/","n. 情况",1],
["skill","/skɪl/","n. 技能",1],
["skip","/skɪp/","v. 跳过",2],
["slave","/sleɪv/","n. 奴隶",2],
["slice","/slaɪs/","n. 薄片",2],
["slide","/slaɪd/","v. 滑动",2],
["slight","/slaɪt/","a. 轻微的",2],
["slip","/slɪp/","v. 滑倒，溜走",2],
["slope","/sləʊp/","n. 斜坡",2],
["smart","/smɑːt/","a. 聪明的",1],
["smell","/smel/","v. 闻 n. 气味",1],
["smooth","/smuːð/","a. 光滑的，顺利的",1],
["society","/sə'saɪətɪ/","n. 社会",1],
["soft","/sɒft/","a. 柔软的",1],
["software","/'sɒftweə/","n. 软件",1],
["soil","/sɔɪl/","n. 土壤",1],
["solid","/'sɒlɪd/","a. 固体的，坚固的",2],
["solution","/sə'luːʃn/","n. 解决方案",1],
["solve","/sɒlv/","v. 解决",1],
["sort","/sɔːt/","n. 种类 v. 分类",1],
["soul","/səʊl/","n. 灵魂",2],
["sound","/saʊnd/","n. 声音 v. 听起来",1],
["source","/sɔːs/","n. 来源",1],
["space","/speɪs/","n. 空间，太空",1],
["spare","/speə/","a. 空闲的 v. 抽出",1],
["special","/'speʃl/","a. 特别的",1],
["specific","/spə'sɪfɪk/","a. 具体的",2],
["speech","/spiːtʃ/","n. 演讲",1],
["speed","/spiːd/","n. 速度",1],
["spell","/spel/","v. 拼写",1],
["spend","/spend/","v. 花费",1],
["spirit","/'spɪrɪt/","n. 精神",1],
["spite","/spaɪt/","n. 恶意（in spite of 尽管）",2],
["split","/splɪt/","v. 分裂",2],
["spot","/spɒt/","n. 地点，斑点 v. 发现",1],
["spread","/spred/","v. 传播，展开",1],
["stable","/'steɪbl/","a. 稳定的",2],
["staff","/stɑːf/","n. 员工",1],
["stage","/steɪdʒ/","n. 舞台，阶段",1],
["stand","/stænd/","v. 站立，忍受",1],
["standard","/'stændəd/","n. 标准",1],
["stare","/steə/","v. 凝视",2],
["start","/stɑːt/","v. 开始",1],
["state","/steɪt/","n. 状态，州 v. 陈述",1],
["statement","/'steɪtmənt/","n. 陈述",1],
["station","/'steɪʃn/","n. 车站",1],
["statistics","/stə'tɪstɪks/","n. 统计",3],
["status","/'steɪtəs/","n. 地位，状态",2],
["stay","/steɪ/","v. 停留",1],
["steady","/'stedɪ/","a. 稳定的",2],
["steal","/stiːl/","v. 偷",1],
["steep","/stiːp/","a. 陡峭的",2],
["step","/step/","n. 步骤",1],
["stick","/stɪk/","v. 粘贴，坚持 n. 棍子",1],
["stiff","/stɪf/","a. 僵硬的",3],
["still","/stɪl/","ad. 仍然 a. 静止的",1],
["stimulate","/'stɪmjuleɪt/","v. 刺激",3],
["stock","/stɒk/","n. 股票，库存",2],
["stop","/stɒp/","v. 停止",1],
["storage","/'stɔːrɪdʒ/","n. 储存",2],
["store","/stɔː/","n. 商店 v. 储存",1],
["storm","/stɔːm/","n. 暴风雨",1],
["straight","/streɪt/","a. 直的 ad. 直接地",1],
["strange","/streɪndʒ/","a. 奇怪的",1],
["strategy","/'strætədʒɪ/","n. 策略",2],
["stream","/striːm/","n. 溪流",1],
["strength","/streŋθ/","n. 力量，优势",1],
["stress","/stres/","n. 压力 v. 强调",1],
["stretch","/stretʃ/","v. 伸展",2],
["strict","/strɪkt/","a. 严格的",1],
["strike","/straɪk/","v. 打击 n. 罢工",1],
["string","/strɪŋ/","n. 细绳，字符串",1],
["strive","/straɪv/","v. 努力",3],
["stroke","/strəʊk/","n. 中风，一击",3],
["strong","/strɒŋ/","a. 强壮的",1],
["structure","/'strʌktʃə/","n. 结构",1],
["struggle","/'strʌgl/","v./n. 挣扎，奋斗",1],
["stubborn","/'stʌbən/","a. 固执的",3],
["study","/'stʌdɪ/","v./n. 学习，研究",1],
["stuff","/stʌf/","n. 东西，材料",1],
["stupid","/'stjuːpɪd/","a. 愚蠢的",1],
["style","/staɪl/","n. 风格",1],
["subject","/'sʌbdʒɪkt/","n. 主题，科目，主语",1],
["submit","/səb'mɪt/","v. 提交，屈服",2],
["substance","/'sʌbstəns/","n. 物质",2],
["substitute","/'sʌbstɪtjuːt/","v. 代替 n. 替代品",3],
["subtle","/'sʌtl/","a. 微妙的",3],
["succeed","/sək'siːd/","v. 成功，继承",1],
["success","/sək'ses/","n. 成功",1],
["sudden","/'sʌdn/","a. 突然的",1],
["suffer","/'sʌfə/","v. 遭受",1],
["sufficient","/sə'fɪʃnt/","a. 足够的",2],
["suggest","/sə'dʒest/","v. 建议，暗示",1],
["suit","/suːt/","n. 套装 v. 适合",1],
["suitable","/'suːtəbl/","a. 合适的",1],
["sum","/sʌm/","n. 总和",1],
["summary","/'sʌmərɪ/","n. 摘要",1],
["superior","/suː'pɪərɪə/","a. 优越的",2],
["supply","/sə'plaɪ/","n./v. 供应",1],
["support","/sə'pɔːt/","n./v. 支持",1],
["suppose","/sə'pəʊz/","v. 假设，认为",1],
["sure","/ʃʊə/","a. 确信的",1],
["surface","/'sɜːfɪs/","n. 表面",1],
["surgery","/'sɜːdʒərɪ/","n. 外科手术",2],
["surprise","/sə'praɪz/","n./v. 惊讶",1],
["surround","/sə'raʊnd/","v. 包围",1],
["survey","/'sɜːveɪ/","n. 调查",2],
["survive","/sə'vaɪv/","v. 幸存",1],
["suspect","/sə'spekt/","v. 怀疑 n. 嫌疑犯",2],
["sustain","/sə'steɪn/","v. 维持",3],
["swallow","/'swɒləʊ/","v. 吞咽 n. 燕子",2],
["swear","/sweə/","v. 发誓",3],
["sweep","/swiːp/","v. 扫",1],
["sweet","/swiːt/","a. 甜的",1],
["swift","/swɪft/","a. 迅速的",3],
["swing","/swɪŋ/","v. 摇摆",2],
["switch","/swɪtʃ/","n. 开关 v. 转换",1],
["symbol","/'sɪmbl/","n. 象征，符号",1],
["sympathy","/'sɪmpəθɪ/","n. 同情",2],
["system","/'sɪstəm/","n. 系统",1],
["table","/'teɪbl/","n. 桌子，表格",1],
["tag","/tæg/","n. 标签",2],
["talent","/'tælənt/","n. 才能",1],
["target","/'tɑːgɪt/","n. 目标",1],
["task","/tɑːsk/","n. 任务",1],
["taste","/teɪst/","n. 味道 v. 品尝",1],
["teach","/tiːtʃ/","v. 教",1],
["team","/tiːm/","n. 团队",1],
["tear","/tɪə/","n. 眼泪 v. 撕裂",1],
["technical","/'teknɪkl/","a. 技术的",1],
["technique","/tek'niːk/","n. 技巧",1],
["technology","/tek'nɒlədʒɪ/","n. 技术",1],
["temper","/'tempə/","n. 脾气",2],
["temperature","/'temprətʃə/","n. 温度",1],
["temporary","/'temprərɪ/","a. 临时的",2],
["tend","/tend/","v. 倾向于",1],
["tendency","/'tendənsɪ/","n. 趋势",2],
["tender","/'tendə/","a. 温柔的，嫩的",3],
["tense","/tens/","a. 紧张的 n. 时态",2],
["tension","/'tenʃn/","n. 紧张",2],
["term","/tɜːm/","n. 学期，术语，条款",1],
["terrible","/'terəbl/","a. 可怕的",1],
["territory","/'terətrɪ/","n. 领土",3],
["test","/test/","n./v. 测试",1],
["text","/tekst/","n. 文本",1],
["theory","/'θɪərɪ/","n. 理论",1],
["therefore","/'ðeəfɔː/","ad. 因此",1],
["thick","/θɪk/","a. 厚的",1],
["thin","/θɪn/","a. 薄的，瘦的",1],
["thorough","/'θʌrə/","a. 彻底的",2],
["though","/ðəʊ/","conj. 虽然",1],
["thought","/θɔːt/","n. 想法",1],
["threat","/θret/","n. 威胁",1],
["threaten","/'θretn/","v. 威胁",1],
["throat","/θrəʊt/","n. 喉咙",1],
["through","/θruː/","prep. 通过",1],
["throughout","/θruː'aʊt/","prep. 遍及",2],
["throw","/θrəʊ/","v. 扔",1],
["thus","/ðʌs/","ad. 因此",1],
["tie","/taɪ/","v. 系 n. 领带",1],
["tight","/taɪt/","a. 紧的",1],
["tiny","/'taɪnɪ/","a. 微小的",1],
["tip","/tɪp/","n. 提示，尖端，小费",1],
["tired","/'taɪəd/","a. 疲倦的",1],
["title","/'taɪtl/","n. 标题，头衔",1],
["tone","/təʊn/","n. 语调，色调",2],
["tool","/tuːl/","n. 工具",1],
["topic","/'tɒpɪk/","n. 话题",1],
["total","/'təʊtl/","a. 总的 n. 总数",1],
["touch","/tʌtʃ/","v. 触摸",1],
["tough","/tʌf/","a. 艰难的，坚韧的",2],
["tour","/tʊə/","n. 旅行",1],
["trace","/treɪs/","n. 痕迹 v. 追踪",2],
["track","/træk/","n. 轨道 v. 追踪",1],
["trade","/treɪd/","n. 贸易",1],
["tradition","/trə'dɪʃn/","n. 传统",1],
["traffic","/'træfɪk/","n. 交通",1],
["train","/treɪn/","n. 火车 v. 训练",1],
["transfer","/træns'fɜː/","v. 转移",2],
["transform","/træns'fɔːm/","v. 转变",2],
["translate","/træns'leɪt/","v. 翻译",1],
["transport","/'trænspɔːt/","n./v. 运输",1],
["travel","/'trævl/","v./n. 旅行",1],
["treat","/triːt/","v. 对待，治疗",1],
["treatment","/'triːtmənt/","n. 治疗，对待",1],
["tremendous","/trɪ'mendəs/","a. 巨大的",3],
["trend","/trend/","n. 趋势",1],
["trial","/'traɪəl/","n. 审判，试验",2],
["tribe","/traɪb/","n. 部落",3],
["trick","/trɪk/","n. 诡计，技巧",1],
["trip","/trɪp/","n. 旅行",1],
["troop","/truːp/","n. 军队",3],
["trouble","/'trʌbl/","n. 麻烦",1],
["trust","/trʌst/","n./v. 信任",1],
["truth","/truːθ/","n. 真相",1],
["try","/traɪ/","v. 尝试",1],
["tune","/tjuːn/","n. 曲调 v. 调音",2],
["turn","/tɜːn/","v. 转动 n. 轮到",1],
["twist","/twɪst/","v. 扭曲",2],
["type","/taɪp/","n. 类型 v. 打字",1],
["typical","/'tɪpɪkl/","a. 典型的",1],
["ultimate","/'ʌltɪmət/","a. 最终的",3],
["unable","/ʌn'eɪbl/","a. 不能的",1],
["uncover","/ʌn'kʌvə/","v. 揭开",2],
["undergo","/ˌʌndə'gəʊ/","v. 经历",3],
["understand","/ˌʌndə'stænd/","v. 理解",1],
["undertake","/ˌʌndə'teɪk/","v. 承担",3],
["uniform","/'juːnɪfɔːm/","n. 制服 a. 统一的",2],
["union","/'juːnɪən/","n. 联合，工会",1],
["unique","/ju'niːk/","a. 独特的",1],
["unit","/'juːnɪt/","n. 单位",1],
["unite","/ju'naɪt/","v. 联合",1],
["universal","/ˌjuːnɪ'vɜːsl/","a. 普遍的",2],
["universe","/'juːnɪvɜːs/","n. 宇宙",1],
["unless","/ən'les/","conj. 除非",1],
["update","/ˌʌp'deɪt/","v. 更新",1],
["upset","/ʌp'set/","a. 心烦的 v. 使不安",1],
["urban","/'ɜːbən/","a. 城市的",2],
["urge","/ɜːdʒ/","v. 敦促 n. 冲动",2],
["urgent","/'ɜːdʒənt/","a. 紧急的",2],
["usage","/'juːsɪdʒ/","n. 用法",2],
["useful","/'juːsfl/","a. 有用的",1],
["usual","/'juːʒuəl/","a. 通常的",1],
["utility","/juː'tɪlətɪ/","n. 效用，公用事业",3],
["vacation","/və'keɪʃn/","n. 假期",1],
["vague","/veɪg/","a. 模糊的",3],
["valid","/'vælɪd/","a. 有效的",2],
["valuable","/'væljuəbl/","a. 有价值的",1],
["value","/'væljuː/","n. 价值",1],
["variety","/və'raɪətɪ/","n. 多样性，种类",1],
["various","/'veərɪəs/","a. 各种各样的",1],
["vary","/'veərɪ/","v. 变化",1],
["vast","/vɑːst/","a. 巨大的",2],
["vehicle","/'viːəkl/","n. 车辆",1],
["venture","/'ventʃə/","n. 冒险企业",3],
["version","/'vɜːʃn/","n. 版本",1],
["victim","/'vɪktɪm/","n. 受害者",2],
["victory","/'vɪktərɪ/","n. 胜利",1],
["view","/vjuː/","n. 观点，景色",1],
["violate","/'vaɪəleɪt/","v. 违反",3],
["violence","/'vaɪələns/","n. 暴力",2],
["virtue","/'vɜːtʃuː/","n. 美德",3],
["visible","/'vɪzəbl/","a. 可见的",1],
["vision","/'vɪʒn/","n. 视力，远见",2],
["visit","/'vɪzɪt/","v./n. 参观",1],
["vital","/'vaɪtl/","a. 至关重要的",2],
["voice","/vɔɪs/","n. 声音，语态",1],
["volume","/'vɒljuːm/","n. 体积，音量，卷",1],
["voluntary","/'vɒləntrɪ/","a. 自愿的",2],
["vote","/vəʊt/","n./v. 投票",1],
["wage","/weɪdʒ/","n. 工资",1],
["wander","/'wɒndə/","v. 漫步",2],
["warn","/wɔːn/","v. 警告",1],
["waste","/weɪst/","n./v. 浪费",1],
["weak","/wiːk/","a. 虚弱的",1],
["wealth","/welθ/","n. 财富",1],
["weapon","/'wepən/","n. 武器",1],
["wear","/weə/","v. 穿戴，磨损",1],
["weigh","/weɪ/","v. 称重",1],
["weight","/weɪt/","n. 重量",1],
["welfare","/'welfeə/","n. 福利",3],
["whatever","/wɒt'evə/","pron. 无论什么",1],
["whereas","/ˌweər'æz/","conj. 然而",3],
["whether","/'weðə/","conj. 是否",1],
["whisper","/'wɪspə/","v. 低语",2],
["whole","/həʊl/","a. 全部的",1],
["wide","/waɪd/","a. 宽的",1],
["widespread","/'waɪdspred/","a. 广泛的",2],
["wild","/waɪld/","a. 野生的",1],
["will","/wɪl/","n. 意志，遗嘱",1],
["willing","/'wɪlɪŋ/","a. 愿意的",1],
["win","/wɪn/","v. 赢",1],
["wisdom","/'wɪzdəm/","n. 智慧",2],
["wise","/waɪz/","a. 明智的",1],
["wish","/wɪʃ/","v./n. 希望",1],
["withdraw","/wɪð'drɔː/","v. 撤回，取款",3],
["within","/wɪ'ðɪn/","prep. 在…之内",1],
["without","/wɪ'ðaʊt/","prep. 没有",1],
["witness","/'wɪtnəs/","n. 目击者 v. 目睹",2],
["wonder","/'wʌndə/","v. 想知道 n. 奇迹",1],
["worth","/wɜːθ/","a. 值得的",1],
["wound","/wuːnd/","n. 伤口 v. 使受伤",2],
["wrap","/ræp/","v. 包裹",2],
["yield","/jiːld/","v. 屈服，产生",3],
["youth","/juːθ/","n. 青年",1]
];

/* ---------- 高频词组与固定搭配 ---------- */
const PHRASES = [
["account for","解释，占（比例）",2],
["adapt to","适应",2],
["add up to","总计",2],
["after all","毕竟",1],
["agree with","同意（某人）",1],
["ahead of","在…前面",1],
["all at once","突然",2],
["all in all","总而言之",2],
["allow for","考虑到",2],
["apart from","除…之外",2],
["apply for","申请",1],
["apply to","适用于",1],
["as a matter of fact","事实上",1],
["as a result","结果",1],
["as far as","就…而言",1],
["as follows","如下",2],
["as long as","只要",1],
["as soon as","一…就…",1],
["as well as","以及",1],
["ask for","请求",1],
["at any rate","无论如何",2],
["at ease","舒适，自在",2],
["at first","起初",1],
["at large","普遍的，逍遥法外",3],
["at least","至少",1],
["at present","目前",1],
["at random","随机地",2],
["at the cost of","以…为代价",2],
["at the mercy of","任由…摆布",3],
["attend to","照料，处理",2],
["back up","支持，备份",2],
["be about to","即将",1],
["be accustomed to","习惯于",2],
["be aware of","意识到",1],
["be bound to","一定会",2],
["be capable of","能够",2],
["be concerned about","关心",1],
["be engaged in","从事于",2],
["be exposed to","暴露于",2],
["be fed up with","厌倦",2],
["be fond of","喜欢",1],
["be in charge of","负责",1],
["be keen on","热衷于",2],
["be made up of","由…组成",1],
["be responsible for","对…负责",1],
["be short of","缺乏",2],
["be subject to","易受…影响",3],
["be superior to","优于",2],
["be tired of","厌倦",1],
["bear in mind","记住",2],
["break down","故障，分解",1],
["break out","爆发",1],
["break through","突破",2],
["bring about","引起",2],
["bring up","抚养，提出",1],
["by accident","偶然",1],
["by all means","一定，务必",2],
["by chance","偶然",1],
["by means of","通过…方式",2],
["by no means","决不",2],
["call for","需要，要求",1],
["call off","取消",2],
["care about","关心",1],
["carry on","继续",1],
["carry out","执行，实施",1],
["catch up with","赶上",1],
["check in","登记入住",1],
["check out","结账离开，查看",1],
["come across","偶遇",1],
["come into effect","生效",2],
["come true","实现",1],
["come up with","想出",1],
["comply with","遵守",3],
["concentrate on","专注于",1],
["consist of","由…组成",1],
["cope with","应付",2],
["count on","依靠",2],
["cut down","削减，砍倒",1],
["cut off","切断",1],
["deal with","处理",1],
["depend on","依靠",1],
["die out","灭绝",2],
["do away with","废除",3],
["do with","处理",1],
["draw up","起草",2],
["drop out","退出，辍学",2],
["due to","由于",1],
["end up","最终成为",1],
["engage in","从事",2],
["even if","即使",1],
["fall behind","落后",2],
["figure out","弄清楚",1],
["fill in","填写",1],
["find out","查明",1],
["focus on","集中于",1],
["for the sake of","为了",2],
["from time to time","不时",2],
["get along with","与…相处",1],
["get in touch with","与…联系",1],
["get over","克服，恢复",1],
["get rid of","摆脱",1],
["give in","屈服",1],
["give off","散发",2],
["give up","放弃",1],
["go over","复习，检查",1],
["go through","经历，浏览",1],
["hand in","上交",1],
["hand out","分发",1],
["hang on","坚持，等一下",1],
["have access to","有权使用",2],
["have nothing to do with","与…无关",1],
["hold on","坚持，等待",1],
["hold up","支撑，耽误",2],
["in a hurry","匆忙",1],
["in addition to","除…之外还",1],
["in advance","提前",1],
["in any case","无论如何",1],
["in case of","万一",1],
["in charge of","负责",1],
["in common","共同",1],
["in contrast","相比之下",2],
["in detail","详细地",1],
["in favor of","支持",2],
["in general","一般来说",1],
["in line with","符合",3],
["in no way","决不",2],
["in order to","为了",1],
["in particular","尤其",1],
["in place of","代替",2],
["in practice","实际上",2],
["in return","作为回报",1],
["in short","简言之",1],
["in spite of","尽管",1],
["in terms of","就…而言",2],
["in the long run","从长远看",2],
["in the way","挡道",1],
["in vain","徒劳",2],
["insist on","坚持",1],
["instead of","代替，而不是",1],
["keep up with","跟上",1],
["lead to","导致",1],
["leave out","遗漏",2],
["let alone","更不用说",3],
["live up to","不辜负",3],
["look after","照顾",1],
["look down on","看不起",2],
["look forward to","期待",1],
["look into","调查",1],
["look out","当心",1],
["look up","查阅",1],
["make a difference","有影响",1],
["make out","辨认出，理解",2],
["make sense","有意义",1],
["make up","组成，编造，化妆",1],
["make up for","弥补",2],
["make use of","利用",1],
["more or less","或多或少",2],
["no doubt","毫无疑问",1],
["no longer","不再",1],
["object to","反对",2],
["on account of","由于",2],
["on behalf of","代表",2],
["on purpose","故意",1],
["on the contrary","相反",1],
["on the other hand","另一方面",1],
["on the whole","总体上",2],
["on time","准时",1],
["once in a while","偶尔",2],
["out of date","过时",1],
["out of order","出故障",1],
["out of question","毫无疑问",3],
["out of the question","不可能",3],
["owing to","由于",2],
["participate in","参与",2],
["pass away","去世",2],
["pay attention to","注意",1],
["pay off","还清，得到回报",2],
["pick out","挑选",1],
["pick up","捡起，接人，学会",1],
["point out","指出",1],
["prefer to","更喜欢",1],
["prevent from","阻止",1],
["provide with","提供",1],
["pull down","拆除",2],
["put aside","搁置",2],
["put forward","提出",2],
["put off","推迟",1],
["put out","扑灭",1],
["put up with","忍受",2],
["refer to","提到，参考",1],
["regardless of","不管",2],
["rely on","依靠",1],
["result from","源于",2],
["result in","导致",2],
["run out of","用完",1],
["set about","开始做",2],
["set aside","留出",2],
["set off","出发，引发",1],
["set up","建立",1],
["settle down","定居，安顿",1],
["show off","炫耀",2],
["show up","出现",1],
["so as to","以便",1],
["so far","到目前为止",1],
["sooner or later","迟早",1],
["stand for","代表",1],
["stand out","突出",2],
["stick to","坚持",1],
["subject to","易受…的",3],
["substitute for","代替",2],
["succeed in","成功做成",1],
["take account of","考虑",2],
["take advantage of","利用",1],
["take away","拿走",1],
["take care of","照顾",1],
["take effect","生效",2],
["take for granted","视为理所当然",2],
["take in","吸收，欺骗",2],
["take on","承担，呈现",2],
["take over","接管",1],
["take part in","参加",1],
["take place","发生",1],
["take up","占据，开始从事",1],
["thanks to","多亏，由于",1],
["think of","想到",1],
["throw away","扔掉",1],
["to some extent","在某种程度上",2],
["turn down","拒绝，调低",1],
["turn in","上交",1],
["turn out","结果是",1],
["turn to","求助于",1],
["up to date","最新的",1],
["up to","直到，取决于",1],
["used to","过去常常",1],
["wear out","磨损，疲惫",2],
["what is more","而且",1],
["with regard to","关于",2],
["work out","算出，解决，锻炼",1],
["would rather","宁愿",1]
];

/* ---------- 英语题库 ---------- */
const EN_QUIZ = {
  g2: [
    { d:1, q:'He ______ (live) in Beijing since 2010.', a:'has lived', 
      hint:'since + 时间点，用现在完成时', 
      sol:'答案：has lived\n\nsince 2010 表示"自2010年以来"，动作从过去持续到现在\n必须用现在完成时 have/has + done\n主语 He 是第三人称单数，用 has\n\n【标志词】since, for, already, yet, ever, never → 现在完成时' },
    { d:2, q:'By the time I arrived, the film ______ (begin).', a:'had begun',
      hint:'"过去的过去"用什么时态？',
      sol:'答案：had begun\n\nBy the time + 过去时（arrived），主句动作发生在这之前\n这是"过去的过去"，用过去完成时 had + done\nbegin 的过去分词是 begun（begin-began-begun）\n\n【口诀】by the time + 过去式，主句用 had done' },
    { d:2, q:'Look! The children ______ (play) football on the playground.', a:'are playing',
      hint:'Look! 提示此刻正在发生',
      sol:'答案：are playing\n\nLook! / Listen! 是现在进行时的经典标志词\n表示"此刻正在发生"\n结构：am/is/are + doing\nThe children 是复数，用 are' },
    { d:3, q:'I ______ (wait) for you for two hours before you finally came.', a:'had been waiting',
      hint:'强调动作在过去某点之前一直持续',
      sol:'答案：had been waiting\n\n分析：before you came 是过去的时间点\n"等"这个动作在那之前已经持续了两小时\n用过去完成进行时 had been doing\n强调动作的持续性\n\n【对比】had waited 只说明完成，had been waiting 强调一直在等' }
  ],
  g3: [
    { d:1, q:'The classroom ______ (clean) every day by the students.', a:'is cleaned',
      hint:'教室是被打扫的',
      sol:'答案：is cleaned\n\n教室不能自己打扫，是"被"学生打扫\n用被动语态：be + 过去分词\nevery day 表明是一般现在时\nThe classroom 单数，用 is\n\n结构：is + cleaned' },
    { d:2, q:'将主动句改为被动语态：They will finish the project next month.', a:'The project will be finished (by them) next month.',
      hint:'将来时被动是 will be done',
      sol:'答案：The project will be finished (by them) next month.\n\n步骤：\n① 原宾语 the project 提前作主语\n② 动词变被动：will finish → will be finished\n③ 原主语 they 用 by 引出（可省略）\n\n【将来时被动公式】will be + 过去分词' },
    { d:2, q:'It ______ (say) that he is the best teacher in our school.', a:'is said',
      hint:'"据说"的固定句型',
      sol:'答案：is said\n\nIt is said that... 是固定句型，意为"据说"\n类似句型：\nIt is reported that... 据报道\nIt is believed that... 人们相信\nIt is known that... 众所周知\n\n这类句型中 It 是形式主语' }
  ],
  g4: [
    { d:2, q:'I am interested in ______ (learn) English.', a:'learning',
      hint:'介词后面接什么形式？',
      sol:'答案：learning\n\nin 是介词，介词后必须接动名词 doing\nbe interested in doing sth 对做某事感兴趣\n\n【规律】所有介词后面接动词，一律用 doing 形式\n如：good at doing, look forward to doing, instead of doing' },
    { d:2, q:'The film is very ______ (excite), and we are all ______ (excite).', a:'exciting; excited',
      hint:'-ing修饰物，-ed修饰人',
      sol:'答案：exciting; excited\n\n【核心口诀】\n-ing 形容词：令人…的，修饰事物\n-ed 形容词：感到…的，修饰人\n\nThe film 是物 → exciting（令人兴奋的）\nwe 是人 → excited（感到兴奋的）\n\n同类词：interesting/interested, boring/bored, surprising/surprised' },
    { d:2, q:'He stopped ______ (smoke) because it is bad for his health.', a:'smoking',
      hint:'stop doing 和 stop to do 意思不同',
      sol:'答案：smoking\n\nstop doing sth = 停止做某事（不做了）\nstop to do sth = 停下来去做另一件事\n\n本句意思是"戒烟"，所以用 stop smoking\n\n【同类辨析】\nremember to do（记得要做，还没做）\nremember doing（记得做过，已做）\nforget to do / forget doing 同理' },
    { d:3, q:'______ (not know) what to do, he turned to his teacher for help.', a:'Not knowing',
      hint:'分词作状语，否定式把not放前面',
      sol:'答案：Not knowing\n\n分析：he 和 know 是主动关系（他不知道）\n用现在分词 knowing 作原因状语\n否定形式：not 放在分词前面\n\n【结构】Not doing..., 主句\n= Because he didn\'t know...\n\n注意：分词的逻辑主语必须与主句主语一致' }
  ],
  g5: [
    { d:1, q:'This is the book ______ I bought yesterday.', a:'that / which',
      hint:'先行词是物，在从句中作宾语',
      sol:'答案：that 或 which（也可省略）\n\n分析：\n先行词 the book 是物\n在从句中 I bought ___ 缺宾语\n物 + 作宾语 → which 或 that\n\n【注意】关系代词作宾语时可以省略\nThis is the book I bought yesterday. 也正确' },
    { d:2, q:'The man ______ wife is a doctor is my neighbor.', a:'whose',
      hint:'表示"他的妻子"用什么关系词？',
      sol:'答案：whose\n\n分析：\n"那个男人的妻子" → 表示所属关系\n关系代词 whose = 他的/她的/它的\n\nThe man whose wife is a doctor...\n= The man\'s wife is a doctor\n\n【记忆】whose 后面直接跟名词' },
    { d:2, q:'I still remember the day ______ we first met.', a:'when',
      hint:'先行词是时间，在从句中作状语',
      sol:'答案：when\n\n分析：\n先行词 the day 是时间\n从句 we first met 结构完整，不缺主语宾语\n缺的是时间状语 → 用关系副词 when\n\n【判断法】\n从句缺主语/宾语 → 关系代词 who/which/that\n从句结构完整 → 关系副词 when/where/why' },
    { d:3, q:'This is the only thing ______ I can do for you.', a:'that',
      hint:'先行词被 only 修饰时有特殊要求',
      sol:'答案：that（只能用 that）\n\n【只能用 that 的情况】\n① 先行词被 only, any, all, no, every, few, little 修饰\n② 先行词被序数词或最高级修饰\n③ 先行词既有人又有物\n④ 先行词是 something, anything, everything, nothing\n\n本题 the only thing 被 only 修饰，必须用 that' }
  ],
  g7: [
    { d:1, q:'______ it rains tomorrow, we will stay at home.', a:'If',
      hint:'条件状语从句',
      sol:'答案：If\n\n表示"如果明天下雨"，是条件状语从句\n引导词用 if（如果）或 unless（除非）\n\n【重要】主将从现\n主句用将来时 we will stay\n从句用一般现在时 it rains（不能用 will rain）' },
    { d:2, q:'找出错误并改正：Although he is poor, but he is happy.', a:'删去 but',
      hint:'中英文表达习惯的差异',
      sol:'答案：删去 but，改为 Although he is poor, he is happy.\n\n【中式英语陷阱】\n中文可以说"虽然…但是…"\n英文中 although/though 和 but 不能同时出现\n\n同理：\nbecause 和 so 不能同时出现\n✗ Because it rained, so we stayed home.\n✓ Because it rained, we stayed home.' },
    { d:2, q:'We will not start ______ everyone arrives.', a:'until',
      hint:'not...until 是固定搭配',
      sol:'答案：until\n\nnot...until 直到…才…\nWe will not start until everyone arrives.\n= 直到所有人到齐我们才开始\n\n【强调句型】\nIt is not until... that...\nNot until... 置句首时主句部分倒装' }
  ],
  g8: [
    { d:2, q:'If I ______ (be) you, I would accept the offer.', a:'were',
      hint:'与现在事实相反的虚拟语气',
      sol:'答案：were\n\n【与现在相反的虚拟语气】\nIf + 主语 + 过去式(be动词一律用were), 主语 + would/could/might + 动词原形\n\n本句：我不是你（与现在事实相反）\nIf I were you, I would accept...\n\n注意：虚拟语气中 be 动词无论人称一律用 were' },
    { d:3, q:'If he ______ (study) harder, he would have passed the exam.', a:'had studied',
      hint:'主句是 would have done，从句用什么？',
      sol:'答案：had studied\n\n【与过去相反的虚拟语气】\nIf + 主语 + had done, 主语 + would have done\n\n从主句 would have passed 可以判断这是与过去事实相反\n所以从句必须用 had + 过去分词\n\n【口诀】过去完成配 would have' },
    { d:2, q:'The teacher suggested that we ______ (finish) the work on time.', a:'(should) finish',
      hint:'suggest 后的从句用虚拟语气',
      sol:'答案：(should) finish\n\n【一坚持二命令三建议四要求】\ninsist, order/command, suggest/advise/propose, demand/require/request\n这些动词后的宾语从句用：(should) + 动词原形\nshould 可以省略\n\n本句：we (should) finish，不能用 finished' }
  ],
  g9: [
    { d:2, q:'The harder you work, ______ progress you will make.', a:'the more',
      hint:'"越…越…"句型',
      sol:'答案：the more\n\n【the + 比较级, the + 比较级】\n意为"越…就越…"\n\nThe harder you work, the more progress you will make.\n你越努力，取得的进步就越大\n\n注意两个分句都要用 the + 比较级' },
    { d:3, q:'Never ______ (see) such a beautiful place before.', a:'have I seen',
      hint:'否定词置句首要部分倒装',
      sol:'答案：have I seen\n\n【部分倒装规则】\n否定词或半否定词置于句首，主句用部分倒装\n即把助动词/情态动词提到主语前\n\nNever have I seen such a beautiful place.\n\n【触发倒装的词】\nnever, seldom, hardly, rarely, little, not only, no sooner, only + 状语' },
    { d:2, q:'This room is three times ______ (large) as that one.', a:'as large',
      hint:'倍数表达的固定结构',
      sol:'答案：as large\n\n【倍数表达三种方式】\n① A is + 倍数 + as + 原级 + as + B\n② A is + 倍数 + 比较级 + than + B\n③ A is + 倍数 + the size/length/height of + B\n\n本句：three times as large as\n= three times larger than' }
  ],
  g10: [
    { d:1, q:'He is good ______ playing basketball.', a:'at',
      hint:'be good + 介词',
      sol:'答案：at\n\nbe good at 擅长于\n\n【常见 be + 形容词 + 介词】\nbe good at 擅长\nbe afraid of 害怕\nbe interested in 对…感兴趣\nbe famous for 因…而闻名\nbe famous as 作为…而闻名\nbe responsible for 对…负责\nbe proud of 为…自豪' },
    { d:2, q:'辨析填空：His failure ______ (result) from laziness. / Laziness ______ (result) in his failure.', a:'resulted; resulted',
      hint:'result from 和 result in 方向相反',
      sol:'答案：两空都填 resulted，但介词不同\n\n【核心区别】\nresult from = 源于，起因于（结果 result from 原因）\nresult in = 导致（原因 result in 结果）\n\nHis failure resulted from laziness. 他的失败源于懒惰\nLaziness resulted in his failure. 懒惰导致了他的失败\n\n【同类】\nbe made of 看得出原料\nbe made from 看不出原料' },
    { d:2, q:'用正确介词填空：The book was written ______ 1998 ______ a rainy morning.', a:'in; on',
      hint:'时间介词的用法规则',
      sol:'答案：in 1998; on a rainy morning\n\n【时间介词规则】\nin + 年、月、季节、世纪、上下午\n  in 1998, in May, in summer, in the morning\non + 具体某一天、特定日期的上下午\n  on Monday, on May 1st, on a rainy morning\nat + 具体时刻、某一点\n  at 6 o\'clock, at noon, at night\n\n注意：具体某天的早晨要用 on 而不是 in' }
  ]
};
