/* ============================================================
   词根扩充库 —— 60 个高频词根
   与 wordbuild.js 的 ROOTS 合并使用
   ============================================================ */
const ROOTS_EXT = [
  {r:'dict', mean:'说', from:'拉丁语 dicere（说）',
   words:[['predict','pre(预先)+dict(说)','v.预测，预言'],
          ['dictionary','dict(说)+ionary','n.词典'],
          ['contradict','contra(相反)+dict(说)','v.反驳，与…矛盾'],
          ['dictate','dict(说)+ate','v.口述；命令'],
          ['indicate','in(朝向)+dic(说)+ate','v.表明，指出']],
   tip:'indicate 在阅读里高频：the study indicates = the study shows'},

  {r:'fact/fect', mean:'做，制造', from:'拉丁语 facere（做）',
   words:[['factory','fact(做)+ory(地方)','n.工厂'],
          ['effect','ef(出)+fect(做)','n.效果，影响'],
          ['affect','af(朝向)+fect(做)','v.影响'],
          ['perfect','per(完全)+fect(做)','adj.完美的'],
          ['manufacture','manu(手)+fact(做)+ure','v./n.制造']],
   tip:'affect 是动词，effect 是名词：Exercise affects health = has an effect on health'},

  {r:'mov/mot', mean:'动', from:'拉丁语 movere（移动）',
   words:[['move','mov(动)','v.移动，感动'],
          ['remove','re(离开)+move(动)','v.移开，去除'],
          ['motion','mot(动)+ion','n.运动，动作'],
          ['motive','mot(动)+ive','n.动机'],
          ['emotion','e(出)+mot(动)+ion','n.情绪（内心动起来）'],
          ['promote','pro(向前)+mote(动)','v.促进，晋升']],
   tip:'emotion 在阅读里常与 stress、mood 一起出现'},

  {r:'ven/vent', mean:'来', from:'拉丁语 venire（来）',
   words:[['prevent','pre(预先)+vent(来)','v.预防（提前来挡住）'],
          ['invent','in(进入)+vent(来)','v.发明'],
          ['event','e(出)+vent(来)','n.事件，大事'],
          ['convenient','con(一起)+ven(来)+ient','adj.方便的'],
          ['adventure','ad(朝向)+vent(来)+ure','n.冒险']],
   tip:'prevent sb from doing 是固定搭配，from 不能省'},

  {r:'ced/cess', mean:'走，让', from:'拉丁语 cedere（走）',
   words:[['process','pro(向前)+cess(走)','n.过程 v.处理'],
          ['access','ac(朝向)+cess(走)','n.通道，使用权'],
          ['succeed','suc(接着)+ceed(走)','v.成功'],
          ['exceed','ex(超出)+ceed(走)','v.超过'],
          ['necessary','ne(不)+cess(走)+ary','adj.必要的（绕不过去的）']],
   tip:'have access to 意为"能够使用/接触到"，to 是介词'},

  {r:'pel/puls', mean:'推，驱', from:'拉丁语 pellere（推）',
   words:[['expel','ex(向外)+pel(推)','v.驱逐，开除'],
          ['impulse','im(向内)+puls(推)','n.冲动'],
          ['pulse','puls(推)','n.脉搏'],
          ['compel','com(强)+pel(推)','v.强迫']],
   tip:'be compelled to do = be forced to do'},

  {r:'tract', mean:'拉', from:'拉丁语 trahere（拉）',
   words:[['attract','at(朝向)+tract(拉)','v.吸引'],
          ['contract','con(一起)+tract(拉)','n.合同 v.收缩'],
          ['extract','ex(向外)+tract(拉)','v.提取'],
          ['subtract','sub(下面)+tract(拉)','v.减去'],
          ['abstract','abs(离开)+tract(拉)','adj.抽象的']],
   tip:'attract tourists / attract attention 是阅读常见搭配'},

  {r:'rupt', mean:'破，断', from:'拉丁语 rumpere（断）',
   words:[['interrupt','inter(之间)+rupt(断)','v.打断'],
          ['bankrupt','bank(银行)+rupt(断)','adj.破产的'],
          ['erupt','e(出)+rupt(破)','v.爆发'],
          ['corrupt','cor(完全)+rupt(破)','adj.腐败的']],
   tip:'interrupt 在听力/阅读对话里高频'},

  {r:'sist', mean:'站立', from:'拉丁语 sistere（站）',
   words:[['insist','in(上)+sist(站)','v.坚持（站着不动）'],
          ['resist','re(反)+sist(站)','v.抵抗'],
          ['assist','as(旁边)+sist(站)','v.协助'],
          ['consist','con(一起)+sist(站)','v.由…组成'],
          ['persist','per(持续)+sist(站)','v.坚持不懈']],
   tip:'insist on doing / consist of 都是必考搭配'},

  {r:'part', mean:'部分', from:'拉丁语 pars（部分）',
   words:[['depart','de(离开)+part(部分)','v.出发，离开'],
          ['particular','part(部分)+icular','adj.特定的，特别的'],
          ['participate','part(部分)+icipate','v.参加'],
          ['partial','part(部分)+ial','adj.部分的，偏袒的'],
          ['apart','a(分开)+part(部分)','adv.分开地']],
   tip:'participate in = take part in，都是"参加"'},

  {r:'val/vail', mean:'价值，强壮', from:'拉丁语 valere（有价值）',
   words:[['value','val(价值)+ue','n.价值 v.重视'],
          ['available','a+vail(价值)+able','adj.可获得的'],
          ['valuable','valu(价值)+able','adj.贵重的'],
          ['evaluate','e(出)+valu(价值)+ate','v.评估']],
   tip:'available 在阅读里常见：The book is available = 可以借到'},

  {r:'cred', mean:'相信', from:'拉丁语 credere（相信）',
   words:[['credit','cred(信)+it','n.信用，学分'],
          ['incredible','in(不)+cred(信)+ible','adj.难以置信的'],
          ['credible','cred(信)+ible','adj.可信的']],
   tip:'credit card 信用卡；credit 也指大学学分'},

  {r:'sens/sent', mean:'感觉', from:'拉丁语 sentire（感觉）',
   words:[['sense','sens(感觉)','n.感觉，意义'],
          ['sensitive','sens(感觉)+itive','adj.敏感的'],
          ['consent','con(一起)+sent(感)','n./v.同意'],
          ['sentence','sent(感)+ence','n.句子；判决']],
   tip:'make sense 意为"讲得通"，是口语和写作高频'},

  {r:'tend/tens', mean:'伸展', from:'拉丁语 tendere（伸）',
   words:[['extend','ex(向外)+tend(伸)','v.延伸，扩展'],
          ['intend','in(向内)+tend(伸)','v.打算'],
          ['tendency','tend(伸)+ency','n.趋势，倾向'],
          ['tense','tens(伸)','adj.紧张的 n.时态'],
          ['attend','at(朝向)+tend(伸)','v.出席，照料']],
   tip:'tendency 与 trend 同义，阅读题常互换'},

  {r:'gen', mean:'产生，种族', from:'希腊语 genos（种）',
   words:[['generate','gen(生)+erate','v.产生'],
          ['generation','gen(生)+eration','n.一代人'],
          ['general','gen(种)+eral','adj.总体的'],
          ['genius','gen(生)+ius','n.天才'],
          ['gene','gen(生)','n.基因']],
   tip:'in general 意为"总的来说"，写作过渡常用'},

  {r:'log', mean:'言，学科', from:'希腊语 logos（言）',
   words:[['logic','log(言)+ic','n.逻辑'],
          ['dialogue','dia(之间)+log(言)','n.对话'],
          ['apologise','apo(离开)+log(言)+ise','v.道歉'],
          ['biology','bio(生命)+logy(学)','n.生物学'],
          ['technology','techno(技术)+logy(学)','n.科技']],
   tip:'-logy 结尾几乎都是学科名'},

  {r:'graph/gram', mean:'写，画', from:'希腊语 graphein（写）',
   words:[['photograph','photo(光)+graph(画)','n.照片'],
          ['paragraph','para(旁)+graph(写)','n.段落'],
          ['program','pro(前)+gram(写)','n.节目，程序'],
          ['diagram','dia(across)+gram(画)','n.图表'],
          ['grammar','gram(写)+mar','n.语法']],
   tip:'paragraph 在阅读题干里高频：the second paragraph'},

  {r:'aud', mean:'听', from:'拉丁语 audire（听）',
   words:[['audience','aud(听)+ience','n.观众，听众'],
          ['audio','aud(听)+io','adj.音频的'],
          ['auditorium','aud(听)+itorium','n.礼堂']],
   tip:'audience 是集合名词，可作单数也可作复数'},

  {r:'man/manu', mean:'手', from:'拉丁语 manus（手）',
   words:[['manual','manu(手)+al','adj.手工的 n.手册'],
          ['manage','man(手)+age','v.管理，设法'],
          ['manufacture','manu(手)+fact(做)+ure','v.制造'],
          ['manner','man(手)+ner','n.方式，举止']],
   tip:'manage to do 意为"设法做成"，强调结果'},

  {r:'ped/pod', mean:'脚', from:'拉丁语 pes（脚）',
   words:[['pedestrian','ped(脚)+estrian','n.行人'],
          ['expedition','ex(出)+ped(脚)+ition','n.远征，考察']],
   tip:'pedestrian crossing 人行横道'},

  {r:'cap/cept', mean:'拿，抓', from:'拉丁语 capere（拿）',
   words:[['accept','ac(朝向)+cept(拿)','v.接受'],
          ['except','ex(出)+cept(拿)','prep.除…之外'],
          ['concept','con(一起)+cept(拿)','n.概念'],
          ['capable','cap(拿)+able','adj.有能力的'],
          ['capture','cap(拿)+ture','v.捕获']],
   tip:'accept 接受（主动）；receive 收到（被动），阅读常辨析'},

  {r:'clud/clus', mean:'关闭', from:'拉丁语 claudere（关）',
   words:[['include','in(内)+clude(关)','v.包括'],
          ['exclude','ex(外)+clude(关)','v.排除'],
          ['conclude','con(一起)+clude(关)','v.得出结论'],
          ['conclusion','con+clus(关)+ion','n.结论']],
   tip:'in conclusion 是议论文结尾万能句'},

  {r:'flu', mean:'流', from:'拉丁语 fluere（流）',
   words:[['fluent','flu(流)+ent','adj.流利的'],
          ['influence','in(进入)+flu(流)+ence','n./v.影响'],
          ['flu','flu(流)','n.流感']],
   tip:'have an influence on 意为"对…有影响"'},

  {r:'sci', mean:'知道', from:'拉丁语 scire（知）',
   words:[['science','sci(知)+ence','n.科学'],
          ['conscious','con(完全)+sci(知)+ous','adj.有意识的'],
          ['conscience','con+sci(知)+ence','n.良心']],
   tip:'be conscious of 意为"意识到"，同 be aware of'},

  {r:'ord', mean:'次序', from:'拉丁语 ordo（次序）',
   words:[['order','ord(序)+er','n.次序，命令 v.订购'],
          ['ordinary','ordin(序)+ary','adj.普通的'],
          ['coordinate','co(共同)+ordin(序)+ate','v.协调']],
   tip:'in order to 意为"为了"，写作高频'},

  {r:'sper/spir', mean:'呼吸', from:'拉丁语 spirare（呼吸）',
   words:[['inspire','in(进入)+spir(呼吸)','v.激励（吹入灵感）'],
          ['spirit','spir(呼吸)+it','n.精神'],
          ['expire','ex(出)+pire(呼吸)','v.到期']],
   tip:'inspire sb to do 意为"激励某人做"'},

  {r:'firm', mean:'坚定', from:'拉丁语 firmus（坚固）',
   words:[['confirm','con(完全)+firm(坚定)','v.确认'],
          ['firm','firm(坚定)','adj.坚定的 n.公司']],
   tip:'I firmly believe that... 是议论文表态句'},

  {r:'apt/ept', mean:'适合', from:'拉丁语 aptus（适合）',
   words:[['adapt','ad(朝向)+apt(适合)','v.适应'],
          ['adopt','ad(朝向)+opt(选择)','v.采用，收养']],
   tip:'adapt to（适应）与 adopt（采用）拼写接近，常考辨析'},

  {r:'sequ/secut', mean:'跟随', from:'拉丁语 sequi（跟随）',
   words:[['consequence','con(一起)+sequ(跟)+ence','n.结果，后果'],
          ['sequence','sequ(跟)+ence','n.顺序'],
          ['consecutive','con+secut(跟)+ive','adj.连续的']],
   tip:'as a consequence = as a result'},

  {r:'medi', mean:'中间', from:'拉丁语 medius（中）',
   words:[['medium','medi(中)+um','n.媒介 adj.中等的'],
          ['immediate','im(不)+medi(中)+ate','adj.立即的（中间没间隔）'],
          ['intermediate','inter(之间)+medi(中)+ate','adj.中级的']],
   tip:'immediately 是时间副词，常放句首或句尾'},

  {r:'nov', mean:'新', from:'拉丁语 novus（新）',
   words:[['novel','nov(新)+el','n.小说 adj.新颖的'],
          ['innovation','in(进入)+nov(新)+ation','n.创新'],
          ['renew','re(再)+new(新)','v.更新，续订']],
   tip:'innovation 是科技类阅读高频词'},

  {r:'terr', mean:'土地', from:'拉丁语 terra（地）',
   words:[['territory','terr(地)+itory','n.领土'],
          ['terrible','terr(吓)+ible','adj.可怕的']],
   tip:'terrible 与 terrific（极好的）意思相反，别混'},

  {r:'liber', mean:'自由', from:'拉丁语 liber（自由）',
   words:[['liberty','liber(自由)+ty','n.自由'],
          ['liberal','liber(自由)+al','adj.开明的'],
          ['deliver','de(away)+liver(自由)','v.递送，发表']],
   tip:'deliver a speech 意为"发表演讲"'},

  {r:'sol', mean:'单独；太阳', from:'拉丁语 solus（独）',
   words:[['solo','sol(独)+o','n.独奏 adj.单独的'],
          ['solitude','sol(独)+itude','n.独处'],
          ['solar','sol(太阳)+ar','adj.太阳的']],
   tip:'solar energy 太阳能，环保话题常见'},

  {r:'equ', mean:'相等', from:'拉丁语 aequus（平）',
   words:[['equal','equ(等)+al','adj.相等的'],
          ['equipment','equip(装备)+ment','n.设备'],
          ['adequate','ad(朝向)+equ(等)+ate','adj.足够的'],
          ['equator','equ(等)+ator','n.赤道']],
   tip:'be equal to 意为"等于/胜任"'},

  {r:'sper', mean:'希望', from:'拉丁语 sperare（希望）',
   words:[['desperate','de(去除)+sper(希望)+ate','adj.绝望的，极度渴望的'],
          ['prosperity','pro(向前)+sper(希望)+ity','n.繁荣']],
   tip:'be desperate for 意为"极度渴望"'},

  {r:'cur/curs', mean:'跑，关心', from:'拉丁语 currere（跑）',
   words:[['current','curr(跑)+ent','adj.当前的 n.水流'],
          ['occur','oc(朝向)+cur(跑)','v.发生'],
          ['curious','cur(关心)+ious','adj.好奇的'],
          ['accurate','ac(朝向)+cur(关心)+ate','adj.精确的']],
   tip:'occur 与 happen 同义，但 occur 更正式'},

  {r:'fin', mean:'结束，界限', from:'拉丁语 finis（终）',
   words:[['final','fin(终)+al','adj.最后的'],
          ['finance','fin(结算)+ance','n.财政'],
          ['define','de(完全)+fine(界限)','v.定义'],
          ['infinite','in(不)+fin(终)+ite','adj.无限的']],
   tip:'finally / eventually / in the end 都表"最终"'},

  {r:'fort', mean:'强壮', from:'拉丁语 fortis（强）',
   words:[['effort','ef(出)+fort(力)','n.努力'],
          ['comfort','com(完全)+fort(强)','n.舒适 v.安慰'],
          ['fortune','fort(强)+une','n.财富，运气']],
   tip:'make an effort to do 意为"努力做"'},

  {r:'grat', mean:'感谢，喜悦', from:'拉丁语 gratus（愉快）',
   words:[['grateful','grat(谢)+eful','adj.感激的'],
          ['congratulate','con+gratul(喜)+ate','v.祝贺'],
          ['gratitude','grat(谢)+itude','n.感激']],
   tip:'be grateful to sb for sth 意为"因某事感激某人"'},

  {r:'hab/hibit', mean:'持有，居住', from:'拉丁语 habere（有）',
   words:[['habit','hab(持)+it','n.习惯'],
          ['inhabit','in(内)+habit(住)','v.居住于'],
          ['exhibit','ex(出)+hibit(持)','v.展出'],
          ['prohibit','pro(前)+hibit(持)','v.禁止']],
   tip:'prohibit sb from doing 与 prevent 用法相同'},

  {r:'ject/jac', mean:'投，躺', from:'拉丁语 jacere（投）',
   words:[['adjacent','ad(朝向)+jac(躺)+ent','adj.邻近的'],
          ['injection','in(内)+ject(投)+ion','n.注射']],
   tip:'与 object/subject/project 同根，都含"投"'},

  {r:'liter', mean:'文字', from:'拉丁语 littera（字母）',
   words:[['literature','liter(文)+ature','n.文学'],
          ['literary','liter(文)+ary','adj.文学的'],
          ['literally','liter(文)+ally','adv.字面上，确实'],
          ['illiterate','il(不)+liter(文)+ate','adj.文盲的']],
   tip:'literally 口语里常表强调："我简直…"'},

  {r:'loc', mean:'地方', from:'拉丁语 locus（地）',
   words:[['local','loc(地)+al','adj.当地的'],
          ['locate','loc(地)+ate','v.位于，找到'],
          ['allocate','al(朝向)+loc(地)+ate','v.分配']],
   tip:'local people 在旅游类阅读里高频'},

  {r:'mem', mean:'记忆', from:'拉丁语 memor（记得）',
   words:[['memory','mem(记)+ory','n.记忆'],
          ['memorial','mem(记)+orial','n.纪念碑 adj.纪念的'],
          ['remember','re(再)+member(记)','v.记得']],
   tip:'in memory of 意为"为纪念"'},

  {r:'migr', mean:'迁移', from:'拉丁语 migrare（迁）',
   words:[['immigrant','im(进入)+migr(迁)+ant','n.移民（迁入）'],
          ['emigrate','e(出)+migr(迁)+ate','v.移居国外'],
          ['migrate','migr(迁)+ate','v.迁徙']],
   tip:'im- 迁入，e- 迁出，方向相反'},

  {r:'nat', mean:'出生', from:'拉丁语 natus（生）',
   words:[['nature','nat(生)+ure','n.自然，本性'],
          ['native','nat(生)+ive','adj.本地的 n.本地人'],
          ['nation','nat(生)+ion','n.国家，民族'],
          ['natural','nat(生)+ural','adj.自然的']],
   tip:'native speaker 意为"母语者"'},

  {r:'not', mean:'知道，标记', from:'拉丁语 notare（标记）',
   words:[['notice','not(知)+ice','v./n.注意；通知'],
          ['notion','not(知)+ion','n.观念'],
          ['notable','not(知)+able','adj.显著的']],
   tip:'notice 作名词时是"通知"，写作应用文常考'},

  {r:'ple/plet', mean:'满', from:'拉丁语 plere（填满）',
   words:[['complete','com(完全)+plete(满)','adj.完整的 v.完成'],
          ['supplement','sup(下)+ple(满)+ment','n.补充'],
          ['plenty','plen(满)+ty','n.大量']],
   tip:'plenty of 后可接可数与不可数名词'},

  {r:'prov/prob', mean:'证明，试验', from:'拉丁语 probare（检验）',
   words:[['prove','prov(证)+e','v.证明'],
          ['approve','ap(朝向)+prove(证)','v.批准，赞成'],
          ['improve','im(进入)+prove(好)','v.改善'],
          ['probable','prob(试)+able','adj.很可能的']],
   tip:'approve of 意为"赞成"，approve 单独用是"批准"'},

  {r:'quir/quest', mean:'寻求', from:'拉丁语 quaerere（寻）',
   words:[['require','re(反复)+quire(求)','v.需要，要求'],
          ['inquire','in(进入)+quire(求)','v.询问'],
          ['acquire','ac(朝向)+quire(求)','v.获得'],
          ['question','quest(求)+ion','n.问题'],
          ['request','re(反复)+quest(求)','n./v.请求']],
   tip:'require sb to do / require doing 两种用法都对'},

  {r:'reg', mean:'统治，规则', from:'拉丁语 regere（统治）',
   words:[['regular','reg(规)+ular','adj.规律的'],
          ['region','reg(治)+ion','n.地区'],
          ['regulate','reg(规)+ulate','v.调节'],
          ['register','re+gist(记)+er','v.注册']],
   tip:'regular exercise 意为"规律锻炼"，健康类阅读高频'},

  {r:'serv', mean:'服务，保持', from:'拉丁语 servire（服务）',
   words:[['serve','serv(服务)','v.服务，供应'],
          ['service','serv(服务)+ice','n.服务'],
          ['preserve','pre(预先)+serve(保持)','v.保护，保存'],
          ['observe','ob(朝向)+serve(看守)','v.观察，遵守'],
          ['deserve','de(完全)+serve(服务)','v.值得']],
   tip:'deserve 后可接名词或 to do：deserve our attention'},

  {r:'sign', mean:'记号', from:'拉丁语 signum（记号）',
   words:[['signal','sign(记号)+al','n.信号'],
          ['design','de(下)+sign(记)','v./n.设计'],
          ['significant','signi(记号)+ficant','adj.重要的'],
          ['assign','as(朝向)+sign(记)','v.分配，布置']],
   tip:'significant 是 important 的高级替换，写作加分'},

  {r:'simil/sembl', mean:'相似', from:'拉丁语 similis（相似）',
   words:[['similar','simil(似)+ar','adj.相似的'],
          ['assemble','as(朝向)+sembl(似)+e','v.集合，装配'],
          ['resemble','re(反复)+sembl(似)','v.相似']],
   tip:'be similar to 意为"与…相似"，介词是 to'},

  {r:'soci', mean:'同伴', from:'拉丁语 socius（同伴）',
   words:[['social','soci(伴)+al','adj.社会的'],
          ['society','soci(伴)+ety','n.社会'],
          ['associate','as(朝向)+soci(伴)+ate','v.联想，交往']],
   tip:'be associated with 意为"与…有关"'},

  {r:'spond/spons', mean:'回应', from:'拉丁语 spondere（承诺）',
   words:[['respond','re(回)+spond(应)','v.回应'],
          ['response','re+spons(应)+e','n.回应'],
          ['responsible','re+spons(应)+ible','adj.负责的']],
   tip:'be responsible for 意为"对…负责"'},

  {r:'stat/stit', mean:'站立', from:'拉丁语 stare（站）',
   words:[['state','stat(站)+e','n.状态，国家 v.陈述'],
          ['station','stat(站)+ion','n.车站'],
          ['stable','stat(站)+ble','adj.稳定的'],
          ['institute','in(内)+stitute(立)','n.学院 v.建立'],
          ['constitute','con(一起)+stitute(立)','v.构成']],
   tip:'state 作动词是"陈述"，阅读题干常用'},

  {r:'techn', mean:'技艺', from:'希腊语 techne（技艺）',
   words:[['technique','techn(技)+ique','n.技巧'],
          ['technical','techn(技)+ical','adj.技术的'],
          ['technology','techn(技)+ology','n.科技']],
   tip:'technology 不可数，不能说 technologies（除非指多种技术）'},

  {r:'tempor', mean:'时间', from:'拉丁语 tempus（时间）',
   words:[['temporary','tempor(时)+ary','adj.暂时的'],
          ['contemporary','con(共同)+tempor(时)+ary','adj.当代的']],
   tip:'temporary 与 permanent（永久的）相对'},

  {r:'urb', mean:'城市', from:'拉丁语 urbs（城）',
   words:[['urban','urb(城)+an','adj.城市的'],
          ['suburb','sub(下)+urb(城)','n.郊区']],
   tip:'urban 与 rural（乡村的）相对，是对比类阅读高频对'},

  {r:'vac/van', mean:'空', from:'拉丁语 vacare（空）',
   words:[['vacant','vac(空)+ant','adj.空的'],
          ['vacation','vac(空)+ation','n.假期'],
          ['vanish','van(空)+ish','v.消失']],
   tip:'on vacation 意为"在度假"'},

  {r:'vert/vers', mean:'转', from:'拉丁语 vertere（转）',
   words:[['convert','con(完全)+vert(转)','v.转换'],
          ['reverse','re(反)+vers(转)','v.颠倒 adj.相反的'],
          ['universe','uni(一)+vers(转)','n.宇宙'],
          ['version','vers(转)+ion','n.版本'],
          ['advertise','ad(朝向)+vert(转)+ise','v.做广告']],
   tip:'advertise 是动词，advertisement 是名词'},

  {r:'vit/viv', mean:'生命', from:'拉丁语 vivere（活）',
   words:[['vital','vit(生)+al','adj.至关重要的'],
          ['survive','sur(超过)+vive(活)','v.幸存'],
          ['vivid','viv(活)+id','adj.生动的'],
          ['revive','re(再)+vive(活)','v.复苏']],
   tip:'vital 是 important 的高级替换'},

  {r:'volv/volu', mean:'滚，转', from:'拉丁语 volvere（滚）',
   words:[['involve','in(进入)+volve(转)','v.涉及，使参与'],
          ['evolve','e(出)+volve(转)','v.进化'],
          ['revolution','re(反复)+volu(转)+tion','n.革命']],
   tip:'be involved in 意为"参与、卷入"'}
];
