/* ============================================================
   例句库扩充 —— 覆盖 ▲◆ 标记词与高频名词形容词
   全部为专升本考试语域，可直接用于句子填空题
   ============================================================ */
const SENTS_EXT = [
// ── ▲ 基础模块新增词 ──
["academic","She won an academic award for her research.","她因研究获得了学术奖。"],
["access","Students have free access to the library.","学生可以免费使用图书馆。"],
["adequate","The room is adequate for four people.","这个房间够四个人住。"],
["adjust","It takes time to adjust to college life.","适应大学生活需要时间。"],
["advertise","The company advertised the job online.","公司在网上发布了招聘广告。"],
["afford","Not everyone can afford a car.","不是人人都买得起汽车。"],
["agency","She works for a travel agency.","她在一家旅行社工作。"],
["alarm","The alarm rings at six every morning.","闹钟每天早上六点响。"],
["alter","You may alter your plan if necessary.","如有必要你可以改变计划。"],
["ambition","His ambition is to become a doctor.","他的志向是当医生。"],
["analyse","We need to analyse the data carefully.","我们需要仔细分析数据。"],
["annual","The annual meeting will be held in May.","年会将在五月举行。"],
["anxiety","Regular exercise reduces anxiety.","规律锻炼能减轻焦虑。"],
["apparent","It is apparent that he is lying.","很明显他在撒谎。"],
["appeal","This style of travel is losing its appeal.","这种旅行方式正失去吸引力。"],
["approach","We need a new approach to teaching.","我们需要新的教学方法。"],
["appropriate","Choose the appropriate word for each blank.","为每个空选择恰当的词。"],
["approximately","The trip takes approximately two hours.","这趟行程大约需要两小时。"],
["assess","Teachers assess students in many ways.","老师用多种方式评估学生。"],
["assist","Volunteers assist the elderly every weekend.","志愿者每周末帮助老人。"],
["assume","Do not assume that everyone agrees.","不要认为每个人都同意。"],
["attitude","A positive attitude helps you succeed.","积极的态度帮助你成功。"],
["authority","The local authority approved the plan.","当地政府批准了这项计划。"],
["awareness","We should raise environmental awareness.","我们应该提高环保意识。"],
["barrier","Language is no longer a barrier today.","如今语言不再是障碍。"],
["basis","The theory has no scientific basis.","这个理论没有科学依据。"],
["behaviour","His behaviour surprised everyone.","他的行为让所有人吃惊。"],
["benefit","Reading benefits both mind and heart.","阅读对心智和心灵都有益。"],
["brief","He gave a brief introduction to the topic.","他对这个话题做了简短介绍。"],
["campaign","The school started a campaign against waste.","学校发起了反浪费运动。"],
["capacity","The hall has a capacity of 500 people.","这个礼堂能容纳五百人。"],
["category","Books here fall into three categories.","这里的书分为三类。"],
["circumstance","Under no circumstance should you give up.","在任何情况下都不该放弃。"],
["client","The company serves clients worldwide.","这家公司为全球客户服务。"],
["colleague","My colleagues are very helpful.","我的同事们很乐于助人。"],
["commercial","This is a commercial district.","这是一个商业区。"],
["commit","He committed himself to the project.","他全身心投入这个项目。"],
["community","Everyone should serve the community.","每个人都应服务社区。"],
["competence","The job requires professional competence.","这份工作需要专业能力。"],
["complex","The problem is more complex than it looks.","问题比看上去更复杂。"],
["component","Every component must be checked.","每个部件都必须检查。"],
["comprehensive","We made a comprehensive plan.","我们制定了全面的计划。"],
["concept","This concept is hard to explain.","这个概念很难解释。"],
["conference","She attended an international conference.","她参加了一次国际会议。"],
["confidence","Practice builds your confidence.","练习能建立你的信心。"],
["confirm","Please confirm your booking by email.","请通过邮件确认预订。"],
["conflict","There is a conflict between the two views.","这两种观点存在冲突。"],
["consequence","He must face the consequences.","他必须承担后果。"],
["considerable","The plan needs considerable time.","这个计划需要相当多的时间。"],
["consistent","His answer is consistent with the facts.","他的回答与事实一致。"],
["constant","Constant practice makes perfect.","持续练习才能完美。"],
["construct","They constructed a bridge over the river.","他们在河上建了一座桥。"],
["consult","You should consult a doctor first.","你应该先咨询医生。"],
["consume","Cars consume a lot of fuel.","汽车消耗大量燃料。"],
["contemporary","Contemporary art is popular now.","当代艺术现在很流行。"],
["contrary","On the contrary, I quite like it.","恰恰相反，我很喜欢它。"],
["contribute","Everyone can contribute to society.","每个人都能为社会作贡献。"],
["conventional","Conventional methods still work well.","传统方法仍然有效。"],
["core","Reading is the core of language learning.","阅读是语言学习的核心。"],
["corporate","She joined a corporate training programme.","她参加了公司培训项目。"],
["crisis","The company survived the crisis.","公司渡过了危机。"],
["criteria","The criteria for selection are strict.","选拔标准很严格。"],
["critical","This is a critical moment for us.","这对我们是关键时刻。"],
["crucial","Practice is crucial to success.","练习对成功至关重要。"],
["decade","The city has changed a lot in a decade.","这座城市十年间变化很大。"],
["decline","Sales declined sharply last quarter.","上季度销售额急剧下降。"],
["definite","We need a definite answer today.","我们今天需要一个明确答复。"],
["demonstrate","The study demonstrates a clear link.","研究证明了明确的联系。"],
["deny","He denied taking part in it.","他否认参与其中。"],
["depression","Exercise helps prevent depression.","锻炼有助于预防抑郁。"],
["derive","The word derives from Latin.","这个词源自拉丁语。"],
["desperate","She was desperate for a chance.","她极度渴望一个机会。"],
["distinct","There is a distinct difference between them.","它们之间有明显区别。"],
["distribute","They distributed food to the villagers.","他们把食物分发给村民。"],
["diverse","China has diverse cultures.","中国有多元的文化。"],
["domestic","Domestic tourism grew rapidly.","国内旅游增长迅速。"],
["dominate","This topic dominated the discussion.","这个话题主导了讨论。"],
["dramatic","There was a dramatic rise in prices.","物价急剧上涨。"],
["duration","The duration of the course is six weeks.","课程时长是六周。"],
["dynamic","The market is very dynamic.","市场非常有活力。"],
["economic","Economic growth benefits everyone.","经济增长惠及每个人。"],
["efficient","This is an efficient way to study.","这是高效的学习方法。"],
["element","Trust is a key element of friendship.","信任是友谊的关键要素。"],
["eliminate","We must eliminate all mistakes.","我们必须消除所有错误。"],
["emphasis","We lay emphasis on practical ability.","我们强调实践能力。"],
["enhance","Reading enhances your vocabulary.","阅读能增强你的词汇量。"],
["enormous","The project requires enormous effort.","这个项目需要巨大的努力。"],
["ensure","Please ensure that all doors are locked.","请确保所有门都锁好。"],
["enterprise","He works in a state-owned enterprise.","他在一家国企工作。"],
["entertainment","The park offers various entertainment.","公园提供各种娱乐活动。"],
["enthusiastic","Students are enthusiastic about the trip.","学生们对这次旅行很热情。"],
["environment","We must protect the environment.","我们必须保护环境。"],
["equipment","The lab has modern equipment.","实验室有现代化的设备。"],
["essential","Water is essential to life.","水对生命至关重要。"],
["establish","The school was established in 1950.","这所学校建于1950年。"],
["estimate","Experts estimate the cost at ten million.","专家估计成本为一千万。"],
["evaluate","Teachers evaluate students' progress.","老师评估学生的进步。"],
["eventually","Eventually, they reached an agreement.","最终他们达成了协议。"],
["evidence","There is no evidence to support it.","没有证据支持这一点。"],
["exceptional","Her performance was exceptional.","她的表现非常出色。"],
["expand","The company plans to expand overseas.","公司计划向海外扩张。"],
["expense","Travel expenses will be covered.","差旅费将被报销。"],
["expert","Experts believe this trend will continue.","专家认为这一趋势会持续。"],
["explore","Young people explore rural areas for a year.","年轻人花一年探索乡村。"],
["expose","Children should not be exposed to violence.","儿童不应接触暴力。"],
["extend","We decided to extend the deadline.","我们决定延长截止日期。"],
["external","External factors also matter.","外部因素同样重要。"],
["facility","The school has excellent facilities.","学校设施优良。"],
["factor","Price is an important factor.","价格是重要因素。"],
["feature","This feature makes it different.","这个特点使它与众不同。"],
["federal","The federal government made the decision.","联邦政府作出了决定。"],
["finance","He studies finance at university.","他在大学学金融。"],
["flexible","The schedule is quite flexible.","日程安排相当灵活。"],
["fundamental","Honesty is a fundamental principle.","诚实是基本原则。"],
["generate","Solar panels generate clean energy.","太阳能板产生清洁能源。"],
["genuine","He showed genuine interest in the topic.","他对这个话题表现出真正的兴趣。"],
["gradually","The weather gradually became warmer.","天气逐渐变暖。"],
["guarantee","We guarantee the quality of our products.","我们保证产品质量。"],
["identify","Scientists identified a new species.","科学家鉴定出一个新物种。"],
["identity","Please show your identity card.","请出示身份证。"],
["ignore","You should not ignore small problems.","你不该忽视小问题。"],
["illustrate","The example illustrates the point well.","这个例子很好地说明了观点。"],
["impact","Technology has a huge impact on life.","科技对生活有巨大影响。"],
["implement","The new rule will be implemented soon.","新规定很快将实施。"],
["imply","His words imply that he disagrees.","他的话暗示他不同意。"],
["impose","The government imposed a new tax.","政府征收了一项新税。"],
["incredible","The view from the top is incredible.","山顶的景色难以置信。"],
["indicate","The study indicates a positive result.","研究表明结果是积极的。"],
["individual","Each individual has different needs.","每个人的需求不同。"],
["initial","My initial reaction was surprise.","我最初的反应是惊讶。"],
["initiative","She took the initiative to help.","她主动提供帮助。"],
["innovation","Innovation drives economic growth.","创新推动经济增长。"],
["insight","The book gives insight into history.","这本书让人洞察历史。"],
["insist","She insisted on paying the bill.","她坚持要付账。"],
["institute","He works at a research institute.","他在一家研究所工作。"],
["instrument","The violin is a musical instrument.","小提琴是一种乐器。"],
["integrate","We should integrate theory with practice.","我们应把理论与实践结合。"],
["intense","The competition was intense.","竞争非常激烈。"],
["interaction","Social interaction is important for kids.","社交互动对孩子很重要。"],
["internal","This is an internal document.","这是一份内部文件。"],
["interpret","How do you interpret this sentence?","你怎么理解这个句子？"],
["invest","They invested a lot in education.","他们在教育上投入很多。"],
["investigate","Police are investigating the case.","警方正在调查此案。"],
["involve","The job involves frequent travel.","这份工作涉及频繁出差。"],
["issue","This is a serious social issue.","这是一个严重的社会问题。"],
["justify","Nothing can justify such behaviour.","没有什么能为这种行为辩解。"],
["labour","Manual labour is still needed.","仍然需要体力劳动。"],
["launch","The company launched a new product.","公司推出了一款新产品。"],
["legal","Everyone must take legal responsibility.","每个人都要承担法律责任。"],
["liberal","He holds liberal views on education.","他对教育持开明观点。"],
["license","You need a license to drive.","开车需要驾照。"],
["link","There is a close link between the two.","两者之间有密切联系。"],
["locate","The hotel is located near the station.","酒店位于车站附近。"],
["maintain","It is important to maintain good habits.","保持好习惯很重要。"],
["major","She majors in English literature.","她主修英国文学。"],
["mature","He is mature for his age.","就年龄而言他很成熟。"],
["mechanism","The mechanism works automatically.","这个装置自动运转。"],
["mental","Exercise improves mental health.","锻炼能改善心理健康。"],
["minimum","The minimum age for the job is eighteen.","这份工作的最低年龄是十八岁。"],
["modify","We modified the plan slightly.","我们稍微修改了计划。"],
["monitor","Teachers monitor students' progress.","老师监督学生的进步。"],
["motivate","Good teachers motivate their students.","好老师能激励学生。"],
["negative","Try to avoid negative thinking.","尽量避免消极思维。"],
["norm","Working from home has become the norm.","居家办公已成为常态。"],
["objective","Our main objective is to improve quality.","我们的主要目标是提高质量。"],
["obtain","She obtained her degree last year.","她去年获得了学位。"],
["obvious","The answer is quite obvious.","答案相当明显。"],
["occupy","The desk occupies too much space.","这张桌子占了太多空间。"],
["occur","The accident occurred at midnight.","事故发生在午夜。"],
["opportunity","This is a rare opportunity.","这是难得的机会。"],
["optimistic","She remains optimistic about the future.","她对未来保持乐观。"],
["option","You have three options to choose from.","你有三个选项可选。"],
["outcome","We are satisfied with the outcome.","我们对结果很满意。"],
["overall","The overall performance was good.","总体表现不错。"],
["overcome","He overcame many difficulties.","他克服了许多困难。"],
["participate","Many students participated in the contest.","许多学生参加了比赛。"],
["particular","Pay particular attention to spelling.","要特别注意拼写。"],
["perceive","People perceive risks differently.","人们对风险的看法不同。"],
["percentage","A high percentage of students passed.","很高比例的学生通过了。"],
["perspective","From my perspective, it is worth trying.","在我看来，这值得一试。"],
["phase","We are entering a new phase.","我们正进入一个新阶段。"],
["philosophy","He studied Chinese philosophy.","他研究中国哲学。"],
["physical","Physical activity benefits memory.","身体活动有益记忆。"],
["policy","The new policy takes effect next month.","新政策下月生效。"],
["potential","She has great potential in music.","她在音乐上很有潜力。"],
["precise","Please give me a precise figure.","请给我一个精确数字。"],
["previous","The previous chapter explains it.","上一章解释了这一点。"],
["primary","Our primary goal is safety.","我们的首要目标是安全。"],
["principle","Honesty is my basic principle.","诚实是我的基本原则。"],
["priority","Health should be your top priority.","健康应是你的首要任务。"],
["procedure","Follow the standard procedure.","遵循标准程序。"],
["professional","She is a professional translator.","她是专业翻译。"],
["prospect","The prospect of graduation excites me.","毕业的前景让我兴奋。"],
["publish","The paper was published last month.","这篇论文上月发表。"],
["pursue","He decided to pursue further study.","他决定继续深造。"],
["random","The sample was chosen at random.","样本是随机选取的。"],
["range","Prices range from ten to fifty yuan.","价格从十元到五十元不等。"],
["rate","The unemployment rate has fallen.","失业率下降了。"],
["ratio","The ratio of boys to girls is two to one.","男女比例是二比一。"],
["react","How did he react to the news?","他对这消息有何反应？"],
["recover","She recovered quickly from the illness.","她很快从病中康复。"],
["reduce","Slow travel reduces stress.","慢旅行能减轻压力。"],
["reform","Educational reform is under way.","教育改革正在进行。"],
["regarding","I have a question regarding the schedule.","我有个关于日程的问题。"],
["region","This region is famous for tea.","这个地区以茶闻名。"],
["register","You must register before Friday.","你必须在周五前注册。"],
["regulation","New regulations came into force.","新规定已生效。"],
["reject","The proposal was rejected.","提案被否决了。"],
["relevant","Please provide relevant documents.","请提供相关文件。"],
["reliable","He is a reliable friend.","他是个可靠的朋友。"],
["reluctant","She was reluctant to leave.","她不情愿离开。"],
["remarkable","He made remarkable progress.","他取得了显著进步。"],
["remote","The village is quite remote.","这个村庄相当偏远。"],
["reputation","The school has a good reputation.","这所学校声誉良好。"],
["resource","We should save natural resources.","我们应节约自然资源。"],
["restrict","Access is restricted to members.","仅限会员进入。"],
["retain","Try to retain what you learn.","努力保留你学到的东西。"],
["reveal","The survey revealed an interesting fact.","调查揭示了一个有趣事实。"],
["revise","I need to revise for the exam.","我需要为考试复习。"],
["rural","Some students volunteer in rural schools.","有些学生在农村学校做志愿者。"],
["scheme","The scheme benefits poor families.","该方案惠及贫困家庭。"],
["scope","This is beyond the scope of our study.","这超出了我们研究的范围。"],
["secure","Your data is completely secure.","你的数据完全安全。"],
["sector","She works in the public sector.","她在公共部门工作。"],
["seek","Graduates seek jobs in big cities.","毕业生在大城市求职。"],
["sequence","Put the pictures in the right sequence.","把图片按正确顺序排列。"],
["significant","Education plays a significant role.","教育起着重要作用。"],
["similar","My view is similar to yours.","我的看法和你相似。"],
["specific","Please give a specific example.","请举一个具体例子。"],
["stable","The economy remains stable.","经济保持稳定。"],
["statistics","Statistics show a clear trend.","统计数据显示了明显趋势。"],
["strategy","We need a better strategy.","我们需要更好的策略。"],
["stress","Exercise helps relieve stress.","锻炼有助于缓解压力。"],
["structure","The structure of the essay is clear.","这篇文章结构清晰。"],
["submit","Please submit your report by Friday.","请在周五前提交报告。"],
["substantial","There was a substantial increase.","有大幅增长。"],
["sufficient","We have sufficient time.","我们有充足的时间。"],
["survey","A survey of 2,000 adults was conducted.","对两千名成年人进行了调查。"],
["sustain","We must sustain this progress.","我们必须保持这一进步。"],
["tendency","There is a tendency towards slow travel.","有一种慢旅行的趋势。"],
["theme","The theme of the essay is friendship.","这篇文章的主题是友谊。"],
["theory","Theory must be combined with practice.","理论必须与实践结合。"],
["thorough","She made a thorough investigation.","她做了彻底的调查。"],
["transfer","He transferred to another school.","他转到了另一所学校。"],
["transform","Technology has transformed our life.","科技改变了我们的生活。"],
["transition","The transition period lasted two years.","过渡期持续了两年。"],
["ultimate","Our ultimate goal is quality education.","我们的最终目标是优质教育。"],
["undertake","She undertook the task willingly.","她欣然承担了这项任务。"],
["unique","Each person has unique talents.","每个人都有独特的才能。"],
["urban","Urban life is much faster.","城市生活节奏快得多。"],
["valid","Your ticket is valid for one month.","你的票有效期一个月。"],
["vary","Opinions vary from person to person.","各人看法不同。"],
["vehicle","Electric vehicles are becoming popular.","电动汽车越来越流行。"],
["version","This is the latest version.","这是最新版本。"],
["via","We travelled to Beijing via Wuhan.","我们经武汉去北京。"],
["virtual","Virtual classrooms are common now.","虚拟教室现在很常见。"],
["visible","The results are clearly visible.","结果清晰可见。"],
["vital","Sleep is vital to health.","睡眠对健康至关重要。"],
["voluntary","Participation is entirely voluntary.","参与完全是自愿的。"],
["welfare","The government improved social welfare.","政府改善了社会福利。"],
["widespread","The practice is widespread in China.","这种做法在中国很普遍。"],

// ── 高频名词与形容词 ──
["advantage","One advantage is that it saves time.","一个优点是它节省时间。"],
["ancient","Ancient China had great inventions.","古代中国有伟大的发明。"],
["annual","We hold an annual sports meeting.","我们每年举办运动会。"],
["appearance","Do not judge by appearance.","不要以貌取人。"],
["application","I sent my application last week.","我上周寄出了申请。"],
["argument","They had a long argument about it.","他们为此长时间争论。"],
["atmosphere","The atmosphere in class was relaxed.","课堂气氛很轻松。"],
["audience","The audience applauded warmly.","观众热烈鼓掌。"],
["average","The average score was seventy.","平均分是七十。"],
["balance","Try to keep a balance between work and rest.","努力保持工作与休息的平衡。"],
["basic","Reading is a basic skill.","阅读是一项基本技能。"],
["boundary","There is no boundary to learning.","学无止境。"],
["capital","Beijing is the capital of China.","北京是中国的首都。"],
["ceremony","The opening ceremony was grand.","开幕式很盛大。"],
["challenge","Learning a language is a challenge.","学语言是一项挑战。"],
["character","He has a strong character.","他性格坚强。"],
["charity","They donated money to charity.","他们向慈善机构捐款。"],
["citizen","Every citizen has rights and duties.","每个公民都有权利和义务。"],
["civilisation","Chinese civilisation is ancient.","中华文明历史悠久。"],
["climate","The climate here is mild.","这里气候温和。"],
["comfort","The news brought her comfort.","这消息给了她安慰。"],
["competition","The competition was very fierce.","竞争非常激烈。"],
["condition","The house is in good condition.","这房子状况良好。"],
["confidence","Practice builds confidence.","练习建立信心。"],
["connection","There is a connection between them.","它们之间有联系。"],
["consumer","Consumers demand better quality.","消费者要求更好的质量。"],
["contrast","In contrast, rural life is slower.","相比之下乡村生活节奏慢。"],
["cooperation","Cooperation leads to success.","合作带来成功。"],
["courage","It takes courage to admit mistakes.","承认错误需要勇气。"],
["culture","We should respect other cultures.","我们应尊重其他文化。"],
["curiosity","Curiosity drives scientific discovery.","好奇心推动科学发现。"],
["custom","It is a local custom here.","这是这里的当地习俗。"],
["damage","The storm caused heavy damage.","暴风雨造成严重损失。"],
["degree","She has a degree in engineering.","她有工程学学位。"],
["demand","There is a growing demand for it.","对它的需求在增长。"],
["desire","People desire real experiences.","人们渴望真实的体验。"],
["destination","Xi'an is a popular destination.","西安是热门目的地。"],
["disaster","The earthquake was a great disaster.","地震是一场大灾难。"],
["discipline","Self-discipline is the key.","自律是关键。"],
["discovery","The discovery changed everything.","这一发现改变了一切。"],
["distance","The distance is about ten kilometres.","距离大约十公里。"],
["duty","It is our duty to protect nature.","保护自然是我们的责任。"],
["economy","The economy has grown steadily.","经济稳步增长。"],
["emergency","Call this number in an emergency.","紧急情况请拨此号码。"],
["emotion","Brain areas for emotion are connected.","负责情绪的脑区相互连接。"],
["employment","Employment opportunities are increasing.","就业机会在增加。"],
["energy","We should save energy in daily life.","日常生活中我们应节约能源。"],
["equipment","The gym has modern equipment.","健身房有现代化设备。"],
["exhibition","The exhibition attracted many visitors.","展览吸引了许多参观者。"],
["expectation","The result exceeded our expectations.","结果超出了我们的预期。"],
["failure","Failure is the mother of success.","失败是成功之母。"],
["fashion","Slow travel is becoming a fashion.","慢旅行正成为一种时尚。"],
["freedom","Freedom comes with responsibility.","自由伴随着责任。"],
["function","This button has two functions.","这个按钮有两个功能。"],
["generation","Each generation has its own values.","每一代人有自己的价值观。"],
["goal","Set a clear goal for yourself.","为自己设定明确目标。"],
["habit","Reading is a good habit.","阅读是好习惯。"],
["harmony","We live in harmony with nature.","我们与自然和谐相处。"],
["honour","It is an honour to be here.","很荣幸来到这里。"],
["humour","He has a good sense of humour.","他很有幽默感。"],
["impression","She left a deep impression on me.","她给我留下深刻印象。"],
["income","His income has doubled.","他的收入翻了一番。"],
["industry","The tourism industry is growing.","旅游业正在增长。"],
["instance","For instance, we can start early.","例如，我们可以早点开始。"],
["intelligence","Artificial intelligence changes work.","人工智能改变了工作方式。"],
["interest","He shows great interest in history.","他对历史很感兴趣。"],
["journey","The journey took three hours.","旅程用了三小时。"],
["justice","We believe in social justice.","我们相信社会公正。"],
["knowledge","Knowledge changes destiny.","知识改变命运。"],
["landscape","The landscape here is beautiful.","这里风景优美。"],
["leadership","Good leadership matters a lot.","优秀的领导力很重要。"],
["luxury","This is a luxury we cannot afford.","这是我们负担不起的奢侈。"],
["majority","The majority of students agreed.","大多数学生同意了。"],
["material","We need more teaching materials.","我们需要更多教学材料。"],
["memory","Short trips leave little memory.","短途旅行留不下什么记忆。"],
["method","This method proved effective.","这个方法证明有效。"],
["minority","A minority of people disagreed.","少数人不同意。"],
["mood","Exercise improves your mood.","锻炼能改善情绪。"],
["nature","Human nature is complex.","人性是复杂的。"],
["necessity","Water is a daily necessity.","水是日常必需品。"],
["opinion","In my opinion, honesty matters most.","在我看来，诚实最重要。"],
["origin","The custom has ancient origins.","这个习俗有古老的起源。"],
["passion","She has a passion for music.","她对音乐充满热情。"],
["patience","Teaching requires great patience.","教学需要极大的耐心。"],
["pattern","We noticed an interesting pattern.","我们注意到一个有趣的模式。"],
["performance","Her performance was outstanding.","她的表现很出色。"],
["personality","He has a warm personality.","他性格温和。"],
["phenomenon","This is a common phenomenon.","这是常见现象。"],
["population","The population is still growing.","人口仍在增长。"],
["poverty","Education helps reduce poverty.","教育有助于减少贫困。"],
["pressure","Students face great pressure.","学生面临很大压力。"],
["profit","The company made a big profit.","公司赚了一大笔利润。"],
["progress","You have made great progress.","你取得了很大进步。"],
["proportion","A large proportion agreed.","很大一部分人同意了。"],
["purpose","The purpose is to raise awareness.","目的是提高意识。"],
["quality","We should improve quality of life.","我们应提高生活质量。"],
["quantity","Quality matters more than quantity.","质量比数量更重要。"],
["reality","Reality is often different from dreams.","现实常与梦想不同。"],
["reason","The main reason is lack of practice.","主要原因是缺乏练习。"],
["relationship","They have a close relationship.","他们关系密切。"],
["respect","We should show respect to elders.","我们应尊敬长辈。"],
["responsibility","Protecting nature is our responsibility.","保护自然是我们的责任。"],
["revolution","The industrial revolution changed history.","工业革命改变了历史。"],
["role","Education plays a key role.","教育起着关键作用。"],
["scenery","The scenery along the river is lovely.","河边的景色很美。"],
["schedule","The schedule is very tight.","日程安排很紧。"],
["security","Job security is important.","工作保障很重要。"],
["service","The hotel offers excellent service.","这家酒店服务优良。"],
["situation","The situation is improving.","情况正在好转。"],
["skill","Communication is a key skill.","沟通是一项关键技能。"],
["society","Everyone contributes to society.","每个人都为社会作贡献。"],
["solution","There is no easy solution.","没有简单的解决办法。"],
["standard","The product meets high standards.","产品符合高标准。"],
["strength","Unity is our greatest strength.","团结是我们最大的力量。"],
["success","Success comes from hard work.","成功来自努力。"],
["support","Thank you for your support.","感谢你的支持。"],
["surface","The surface is very smooth.","表面很光滑。"],
["symbol","The dragon is a symbol of China.","龙是中国的象征。"],
["talent","She has a talent for languages.","她有语言天赋。"],
["task","The task must be finished today.","任务必须今天完成。"],
["technique","He mastered the technique quickly.","他很快掌握了这项技术。"],
["tradition","We should preserve traditions.","我们应保护传统。"],
["treatment","This should not replace professional treatment.","这不该取代专业治疗。"],
["trust","Trust takes years to build.","信任需要多年建立。"],
["truth","Tell me the truth, please.","请告诉我实情。"],
["value","We should value every chance.","我们应珍惜每个机会。"],
["variety","There is a variety of choices.","有多种选择。"],
["victory","The victory belongs to everyone.","胜利属于每个人。"],
["wealth","Health is better than wealth.","健康胜过财富。"],
["wisdom","Age brings wisdom.","年龄带来智慧。"],
["youth","Youth is the best time to learn.","青年是学习的最佳时期。"]
];

/* 并入例句索引 */
(function mergeSentsExt(){
  if(typeof buildSentIndex!=='function') return;
  const _b=buildSentIndex;
  buildSentIndex=function(){
    const idx=_b();
    if(idx.__ext2) return idx;
    SENTS_EXT.forEach(e=>{
      const k=e[0].toLowerCase();
      idx[k]=idx[k]||[];
      if(!idx[k].some(x=>x.sent===e[1])) idx[k].push({sent:e[1], src:'考试例句', note:'', cn:e[2]});
    });
    idx.__ext2=true;
    return idx;
  };
})();
