/* ============================================================
   词根词缀体系 + 同义替换 + 真题词汇
   目标：把 3000 词从"死记"变成"推导"
   ============================================================ */

/* ---------- 一、核心词根（按专升本出现频次排序） ---------- */
const ROOTS = [
  {r:'spect', mean:'看', from:'拉丁语 specere（看）',
   words:[['inspect','in(向内)+spect(看)','v.检查，视察'],
          ['respect','re(反复)+spect(看)','n./v.尊敬（反复看→敬重）'],
          ['expect','ex(向外)+spect(看)','v.期待（向外看→盼望）'],
          ['aspect','a(朝向)+spect(看)','n.方面，外观'],
          ['perspective','per(透过)+spect(看)+ive','n.观点，视角'],
          ['spectacular','spect(看)+acular','adj.壮观的（值得看的）']],
   tip:'看到 spect 就想"看"，再看前缀判断方向：in向内、ex向外、re反复、per透过'},

  {r:'port', mean:'搬运，运输', from:'拉丁语 portare（搬）',
   words:[['import','im(向内)+port(运)','v./n.进口'],
          ['export','ex(向外)+port(运)','v./n.出口'],
          ['transport','trans(横过)+port(运)','v./n.运输'],
          ['support','sup(下面)+port(搬)','v./n.支持（在下面撑住）'],
          ['report','re(回)+port(搬)','v./n.报告（把信息搬回来）'],
          ['portable','port(搬)+able(能)','adj.便携的']],
   tip:'import/export 这对反义词是必考点，im-向内、ex-向外'},

  {r:'duc/duct', mean:'引导', from:'拉丁语 ducere（引）',
   words:[['introduce','intro(向内)+duce(引)','v.介绍，引进'],
          ['reduce','re(回)+duce(引)','v.减少（引回来→变少）'],
          ['produce','pro(向前)+duce(引)','v.生产（引出来）'],
          ['conduct','con(共同)+duct(引)','v.实施，指挥'],
          ['education','e(出)+duc(引)+ation','n.教育（引导出潜能）'],
          ['product','pro(向前)+duct(引)','n.产品']],
   tip:'produce/product/production 是一家人，动词-名词-抽象名词'},

  {r:'ject', mean:'投掷', from:'拉丁语 jacere（扔）',
   words:[['object','ob(反对)+ject(扔)','n.物体 v.反对（扔回去）'],
          ['subject','sub(下面)+ject(扔)','n.主题，科目'],
          ['project','pro(向前)+ject(扔)','n.项目 v.投射'],
          ['reject','re(回)+ject(扔)','v.拒绝（扔回去）'],
          ['inject','in(进入)+ject(扔)','v.注射']],
   tip:'object 做名词是"物体"，做动词是"反对"，重音位置不同'},

  {r:'fer', mean:'带来，拿', from:'拉丁语 ferre（带）',
   words:[['transfer','trans(横过)+fer(带)','v.转移，转让'],
          ['offer','of(向)+fer(带)','v./n.提供'],
          ['prefer','pre(先)+fer(带)','v.更喜欢（先拿的→偏爱）'],
          ['suffer','suf(下面)+fer(带)','v.遭受（承受在下）'],
          ['differ','dif(分开)+fer(带)','v.不同'],
          ['refer','re(回)+fer(带)','v.提到，参考']],
   tip:'prefer A to B（喜欢A胜过B）是高频搭配，注意 to 不是 than'},

  {r:'press', mean:'压', from:'拉丁语 premere（压）',
   words:[['express','ex(向外)+press(压)','v.表达（把想法压出来）'],
          ['impress','im(向内)+press(压)','v.给…留下印象'],
          ['depress','de(向下)+press(压)','v.使沮丧（压下去）'],
          ['pressure','press(压)+ure','n.压力'],
          ['compress','com(一起)+press(压)','v.压缩']],
   tip:'be impressed by/with（对…印象深刻）是写作常用'},

  {r:'form', mean:'形状，形成', from:'拉丁语 forma（形状）',
   words:[['inform','in(进入)+form(形)','v.通知（使形成认知）'],
          ['reform','re(重新)+form(形)','v./n.改革'],
          ['perform','per(完全)+form(形)','v.表演，执行'],
          ['transform','trans(变换)+form(形)','v.转变'],
          ['formal','form(形式)+al','adj.正式的'],
          ['information','in+form+ation','n.信息（不可数！）']],
   tip:'information 永远不可数，不能说 informations 或 an information'},

  {r:'pos/pon', mean:'放置', from:'拉丁语 ponere（放）',
   words:[['compose','com(一起)+pose(放)','v.组成，创作'],
          ['propose','pro(向前)+pose(放)','v.提议，求婚'],
          ['suppose','sup(下面)+pose(放)','v.假设，认为'],
          ['oppose','op(相对)+pose(放)','v.反对'],
          ['position','pos(放)+ition','n.位置，职位'],
          ['purpose','pur(向前)+pose(放)','n.目的']],
   tip:'be supposed to do 意为"应该做"，是高频固定搭配'},

  {r:'tain/ten', mean:'保持，握', from:'拉丁语 tenere（持有）',
   words:[['contain','con(共同)+tain(持)','v.包含'],
          ['maintain','main(手)+tain(持)','v.维持，保养'],
          ['obtain','ob(朝向)+tain(持)','v.获得'],
          ['entertain','enter(之间)+tain(持)','v.娱乐，招待'],
          ['content','con+tent(持)','n.内容 adj.满足的']],
   tip:'contain 强调"内含"，include 强调"包括在内"，考试常辨析'},

  {r:'vis/vid', mean:'看', from:'拉丁语 videre（看）',
   words:[['visible','vis(看)+ible(能)','adj.可见的'],
          ['vision','vis(看)+ion','n.视力，视野'],
          ['visit','vis(看)+it','v./n.参观，拜访'],
          ['provide','pro(向前)+vide(看)','v.提供（预先看到需求）'],
          ['evidence','e(出)+vid(看)+ence','n.证据（看得出来的）'],
          ['review','re(再)+view(看)','v./n.复习，评论']],
   tip:'provide sb with sth = provide sth for sb，介词不同'},

  {r:'struct', mean:'建造', from:'拉丁语 struere（建）',
   words:[['construct','con(共同)+struct(建)','v.建造'],
          ['instruct','in(进入)+struct(建)','v.指导（在心里建立知识）'],
          ['destroy','de(去除)+stroy(建)','v.破坏'],
          ['structure','struct(建)+ure','n.结构'],
          ['industry','indu(内)+stry(建)','n.工业，产业']],
   tip:'construct/destroy 是反义词对，de- 前缀表"去除、相反"'},

  {r:'mit/miss', mean:'送，派', from:'拉丁语 mittere（送）',
   words:[['admit','ad(朝向)+mit(送)','v.承认，准许进入'],
          ['permit','per(通过)+mit(送)','v.允许 n.许可证'],
          ['submit','sub(下面)+mit(送)','v.提交，服从'],
          ['transmit','trans(横过)+mit(送)','v.传输'],
          ['mission','miss(送)+ion','n.任务，使命'],
          ['dismiss','dis(离开)+miss(送)','v.解雇，解散']],
   tip:'admit doing（承认做过）后接动名词，不能接不定式'},

  {r:'scrib/script', mean:'写', from:'拉丁语 scribere（写）',
   words:[['describe','de(向下)+scribe(写)','v.描述'],
          ['subscribe','sub(下面)+scribe(写)','v.订阅，签署'],
          ['prescribe','pre(预先)+scribe(写)','v.开处方'],
          ['description','de+script(写)+ion','n.描述'],
          ['manuscript','manu(手)+script(写)','n.手稿']],
   tip:'describe 是及物动词，不能说 describe about'},

  {r:'cede/ceed/cess', mean:'走，让步', from:'拉丁语 cedere（走）',
   words:[['proceed','pro(向前)+ceed(走)','v.继续进行'],
          ['succeed','suc(下面)+ceed(走)','v.成功，继任'],
          ['exceed','ex(超出)+ceed(走)','v.超过'],
          ['process','pro(向前)+cess(走)','n.过程 v.处理'],
          ['access','ac(朝向)+cess(走)','n.通道，使用权'],
          ['necessary','ne(不)+cess(走)+ary','adj.必要的']],
   tip:'succeed in doing（成功做某事），介词是 in 不是 to'},

  {r:'grad/gress', mean:'走，步', from:'拉丁语 gradi（走）',
   words:[['graduate','grad(走)+uate','v.毕业（走完学业）'],
          ['gradual','grad(步)+ual','adj.逐渐的'],
          ['progress','pro(向前)+gress(走)','n./v.进步'],
          ['degree','de(向下)+gree(步)','n.程度，学位'],
          ['aggressive','ag(朝向)+gress(走)+ive','adj.好斗的，进取的']],
   tip:'graduate from（毕业于），介词必须是 from'}
];

/* ---------- 二、高频前缀 ---------- */
const PREFIXES = [
  {p:'un-', mean:'不，非（否定）',
   ex:[['happy→unhappy','不快乐的'],['fair→unfair','不公平的'],
       ['able→unable','不能的'],['usual→unusual','不寻常的'],
       ['fortunately→unfortunately','不幸地']],
   note:'最常用的否定前缀，加在形容词/副词前'},
  {p:'in-/im-/il-/ir-', mean:'不，非（否定）',
   ex:[['correct→incorrect','不正确的'],['possible→impossible','不可能的'],
       ['patient→impatient','不耐烦的'],['legal→illegal','非法的'],
       ['regular→irregular','不规则的']],
   note:'im- 用于 m/p/b 前，il- 用于 l 前，ir- 用于 r 前，其余用 in-'},
  {p:'dis-', mean:'不，相反',
   ex:[['agree→disagree','不同意'],['appear→disappear','消失'],
       ['honest→dishonest','不诚实的'],['advantage→disadvantage','缺点'],
       ['cover→discover','发现（去掉覆盖）']],
   note:'既可否定，也表"分开、去除"'},
  {p:'re-', mean:'again 再，重新；back 回',
   ex:[['use→reuse','重复使用'],['build→rebuild','重建'],
       ['turn→return','返回'],['view→review','复习'],
       ['cycle→recycle','回收']],
   note:'环保话题高频：reduce, reuse, recycle 三个 R'},
  {p:'pre-', mean:'预先，前',
   ex:[['view→preview','预览'],['pare→prepare','准备'],
       ['dict→predict','预测'],['fer→prefer','更喜欢']],
   note:'表示时间或位置在前'},
  {p:'ex-', mean:'向外，出',
   ex:[['port→export','出口'],['press→express','表达'],
       ['pect→expect','期待'],['it→exit','出口']],
   note:'与 in-/im- 构成反义对'},
  {p:'en-/em-', mean:'使…（构成动词）',
   ex:[['large→enlarge','扩大'],['able→enable','使能够'],
       ['courage→encourage','鼓励'],['power→empower','授权']],
   note:'把名词/形容词变成动词'},
  {p:'inter-', mean:'在…之间，相互',
   ex:[['national→international','国际的'],['net→Internet','互联网'],
       ['action→interaction','互动'],['view→interview','面试']],
   note:'inter 本身就是"之间"'},
  {p:'over-', mean:'过度，超过',
   ex:[['weight→overweight','超重的'],['come→overcome','克服'],
       ['seas→overseas','海外的'],['all→overall','总体的']],
   note:'常表"过分"，如 overwork 过劳'},
  {p:'under-', mean:'在下，不足',
   ex:[['stand→understand','理解'],['ground→underground','地下的'],
       ['line→underline','划线强调'],['estimate→underestimate','低估']],
   note:'与 over- 构成反义'},
  {p:'self-', mean:'自我',
   ex:[['confidence→self-confidence','自信'],['study→self-study','自学'],
       ['control→self-control','自制力']],
   note:'构词能力强，写作可用'},
  {p:'co-/con-/com-', mean:'共同，一起',
   ex:[['operate→cooperate','合作'],['worker→co-worker','同事'],
       ['nect→connect','连接'],['municate→communicate','交流']],
   note:'com- 用于 b/m/p 前'}
];

/* ---------- 三、高频后缀（决定词性，填空题核心） ---------- */
const SUFFIXES = [
  {s:'-tion/-sion', pos:'名词', mean:'动作，状态',
   ex:[['educate→education','教育'],['decide→decision','决定'],
       ['discuss→discussion','讨论'],['produce→production','生产'],
       ['inform→information','信息']],
   note:'动词变名词最常见的方式，语法填空必考'},
  {s:'-ment', pos:'名词', mean:'动作结果',
   ex:[['develop→development','发展'],['achieve→achievement','成就'],
       ['govern→government','政府'],['agree→agreement','协议'],
       ['move→movement','运动']],
   note:'直接加，不改变原词拼写'},
  {s:'-ness', pos:'名词', mean:'性质，状态',
   ex:[['happy→happiness','幸福'],['kind→kindness','善良'],
       ['ill→illness','疾病'],['dark→darkness','黑暗']],
   note:'形容词变名词；辅音+y 要改 i'},
  {s:'-ity/-ty', pos:'名词', mean:'性质',
   ex:[['able→ability','能力'],['safe→safety','安全'],
       ['difficult→difficulty','困难'],['active→activity','活动'],
       ['possible→possibility','可能性']],
   note:'形容词变抽象名词'},
  {s:'-er/-or/-ist', pos:'名词', mean:'人',
   ex:[['teach→teacher','教师'],['act→actor','演员'],
       ['visit→visitor','访客'],['science→scientist','科学家'],
       ['art→artist','艺术家']],
   note:'注意 -or 的词：actor, visitor, editor, director'},
  {s:'-ful', pos:'形容词', mean:'充满…的',
   ex:[['care→careful','小心的'],['use→useful','有用的'],
       ['help→helpful','有帮助的'],['success→successful','成功的'],
       ['beauty→beautiful','美丽的']],
   note:'beauty→beautiful 要改 y 为 i'},
  {s:'-less', pos:'形容词', mean:'没有…的',
   ex:[['care→careless','粗心的'],['use→useless','无用的'],
       ['home→homeless','无家可归的'],['hope→hopeless','绝望的']],
   note:'与 -ful 构成反义对，考试常一起考'},
  {s:'-able/-ible', pos:'形容词', mean:'能够…的',
   ex:[['accept→acceptable','可接受的'],['comfort→comfortable','舒适的'],
       ['possible','可能的'],['reason→reasonable','合理的']],
   note:'表示"可以被…"，常含被动含义'},
  {s:'-ous', pos:'形容词', mean:'有…性质的',
   ex:[['danger→dangerous','危险的'],['fame→famous','著名的'],
       ['nerve→nervous','紧张的'],['humour→humorous','幽默的']],
   note:'fame→famous 要去 e'},
  {s:'-ive', pos:'形容词', mean:'有…倾向的',
   ex:[['act→active','活跃的'],['create→creative','有创造力的'],
       ['effect→effective','有效的'],['attract→attractive','有吸引力的']],
   note:'create→creative 去 e 加 ive'},
  {s:'-ly', pos:'副词', mean:'以…方式',
   ex:[['quick→quickly','快速地'],['careful→carefully','仔细地'],
       ['happy→happily','高兴地'],['true→truly','真正地'],
       ['terrible→terribly','可怕地']],
   note:'语法填空最高频！true→truly 去 e；-le 结尾去 e 加 y'},
  {s:'-ize/-ise', pos:'动词', mean:'使…化',
   ex:[['modern→modernize','使现代化'],['real→realize','意识到'],
       ['organ→organize','组织'],['special→specialize','专门从事']],
   note:'英式用 -ise，美式用 -ize，考纲用英式'},
  {s:'-en', pos:'动词', mean:'使…变得',
   ex:[['wide→widen','加宽'],['strength→strengthen','加强'],
       ['short→shorten','缩短'],['deep→deepen','加深']],
   note:'形容词/名词变动词'},
  {s:'-ing/-ed', pos:'形容词', mean:'令人…的／感到…的',
   ex:[['interest→interesting/interested','有趣的／感兴趣的'],
       ['excite→exciting/excited','令人兴奋的／感到兴奋的'],
       ['bore→boring/bored','无聊的／感到无聊的'],
       ['relax→relaxing/relaxed','令人放松的／感到放松的']],
   note:'★必考★ -ing 修饰物，-ed 修饰人。The film is boring. / I am bored.'}
];

/* ---------- 四、同义替换（阅读理解核心技能） ---------- */
const SYNONYMS = [
  {topic:'重要', core:'important',
   words:['significant','essential','crucial','vital','key','major'],
   ex:'Education plays a significant/crucial role in society.',
   note:'阅读题干用 important，原文常用 significant/crucial，这就是同义替换'},
  {topic:'增加', core:'increase',
   words:['rise','grow','go up','climb','expand','boost'],
   ex:'The number of tourists has risen sharply.',
   note:'反义：decrease, drop, fall, decline, reduce'},
  {topic:'减少', core:'decrease',
   words:['reduce','drop','fall','decline','cut down','lower'],
   ex:'We should cut down our use of plastic bags.'},
  {topic:'原因', core:'because of',
   words:['due to','owing to','thanks to','as a result of','on account of'],
   ex:'Due to the heavy rain, the game was cancelled.',
   note:'thanks to 通常用于好事，due to 中性'},
  {topic:'结果', core:'so',
   words:['therefore','thus','as a result','consequently','hence'],
   ex:'He didn\'t study hard; as a result, he failed.'},
  {topic:'但是', core:'but',
   words:['however','nevertheless','yet','while','whereas','on the contrary'],
   ex:'The plan looks good; however, it costs too much.',
   note:'however 后要加逗号，but 不用'},
  {topic:'认为', core:'think',
   words:['believe','consider','hold','maintain','argue','claim'],
   ex:'Many people believe that exercise improves mood.'},
  {topic:'帮助', core:'help',
   words:['assist','aid','contribute to','benefit','be of help'],
   ex:'Reading contributes to your vocabulary growth.'},
  {topic:'解决', core:'solve',
   words:['deal with','cope with','handle','address','tackle','settle'],
   ex:'We must deal with the pollution problem.',
   note:'deal with 是最常用的替换'},
  {topic:'提高', core:'improve',
   words:['enhance','promote','better','raise','upgrade','strengthen'],
   ex:'Regular exercise enhances your health.'},
  {topic:'困难', core:'difficult',
   words:['hard','tough','challenging','demanding','complicated'],
   ex:'Learning a language is challenging but rewarding.'},
  {topic:'许多', core:'many',
   words:['numerous','plenty of','a great deal of','a large number of','massive'],
   ex:'Numerous students take part in the activity.',
   note:'a great deal of 接不可数，a large number of 接可数'},
  {topic:'著名', core:'famous',
   words:['well-known','noted','celebrated','renowned','outstanding'],
   ex:'He is a well-known scientist in this field.'},
  {topic:'获得', core:'get',
   words:['obtain','acquire','gain','receive','achieve','earn'],
   ex:'She obtained a degree in engineering.'},
  {topic:'需要', core:'need',
   words:['require','demand','call for','be in need of'],
   ex:'This job requires great patience.'},
  {topic:'展示', core:'show',
   words:['demonstrate','indicate','reveal','illustrate','display','present'],
   ex:'The study indicates that exercise reduces stress.',
   note:'阅读题常问 "the study shows"，原文可能是 indicates'},
  {topic:'参加', core:'take part in',
   words:['participate in','join in','attend','be involved in'],
   ex:'Over 500 students participated in the competition.',
   note:'attend 接活动/学校，join 接组织'},
  {topic:'最终', core:'finally',
   words:['eventually','ultimately','in the end','at last'],
   ex:'Eventually, they reached an agreement.'}
];

/* ---------- 五、真题高频词汇（从真题语料提取） ---------- */
const EXAM_WORDS = [
  {w:'appeal', ph:"/ə'piːl/", def:'n.吸引力；呼吁 v.吸引；呼吁',
   src:'2026语法填空', sent:'This "boot camp" style of travel is losing its appeal.',
   note:'lose one\'s appeal 失去吸引力'},
  {w:'countless', ph:"/'kaʊntləs/", def:'adj.无数的，数不清的',
   src:'2026语法填空', sent:'They visited countless places in a very short time.',
   note:'count(数)+less(无) = 数不清的'},
  {w:'in exchange for', ph:'', def:'phr.作为交换',
   src:'2026阅读', sent:'They work in guesthouses in exchange for a place to stay.',
   note:'固定搭配，注意介词 for'},
  {w:'reflect', ph:"/rɪ'flekt/", def:'v.反映；反射；思考',
   src:'2026阅读', sent:'The change reflects a deeper desire for real experiences.',
   note:'reflect on 意为"反思"'},
  {w:'rather than', ph:'', def:'phr.而不是',
   src:'2026语法填空', sent:'a desire for real experiences rather than photos',
   note:'★高频★ 连接两个并列成分，前后形式要一致'},
  {w:'trend', ph:'/trend/', def:'n.趋势，潮流',
   src:'2026阅读', sent:'Slow travel is emerging as a defining trend.',
   note:'▲考纲标记词，写作常用'},
  {w:'briskly', ph:"/'brɪskli/", def:'adv.轻快地，敏捷地',
   src:'2026阅读', sent:'Adults who walk briskly for thirty minutes a day...',
   note:'brisk(轻快的)+ly，语法填空考副词变形'},
  {w:'point out', ph:'', def:'phr.指出',
   src:'2026阅读', sent:'The researchers pointed out that physical activity benefits memory.',
   note:'后接 that 从句'},
  {w:'set the direction for', ph:'', def:'phr.为…指明方向',
   src:'2026连词成句', sent:"The Plan sets the clear direction for China's development.",
   note:'2026连词成句真题原句'},
  {w:'no point in doing', ph:'', def:'phr.做…没有意义',
   src:'2026完成句子', sent:'There is no point in worrying about things you cannot change.',
   note:'★in 是介词，后必须接动名词★'},
  {w:'as is known to all', ph:'', def:'phr.众所周知',
   src:'历年高频', sent:'As is known to all, China is a developing country.',
   note:'as 引导非限制性定语从句，指代整个主句'},
  {w:'would rather', ph:'', def:'phr.宁愿',
   src:'历年高频', sent:'I would rather you stayed at home now.',
   note:'★后接从句用虚拟语气（过去式表现在）★'},
  {w:'hardly...when', ph:'', def:'phr.一…就…',
   src:'历年高频', sent:'Hardly had I entered the room when the phone rang.',
   note:'★Hardly 置句首要倒装，主句用过去完成时★'},
  {w:'the number of', ph:'', def:'phr.…的数量',
   src:'历年高频', sent:'The number of students is fifty.',
   note:'★谓语用单数；a number of 才用复数★'},
  {w:'be worth doing', ph:'', def:'phr.值得做',
   src:'历年高频', sent:'The book is worth reading.',
   note:'worth 后用动名词主动形式表被动'},
  {w:'look forward to', ph:'', def:'phr.期待',
   src:'写作高频', sent:'Looking forward to hearing from you.',
   note:'★to 是介词，后接动名词★书信结尾必用'},
  {w:'appreciate', ph:"/ə'priːʃieɪt/", def:'v.感激；欣赏；理解',
   src:'写作高频', sent:'I would appreciate it if you could give me an early reply.',
   note:'★appreciate 后必须加 it 作形式宾语★'},
  {w:'on behalf of', ph:'', def:'phr.代表',
   src:'写作高频', sent:'On behalf of our class, I invite you to the party.',
   note:'邀请信开头常用'},
  {w:'emerge', ph:"/ɪ'mɜːdʒ/", def:'v.出现，浮现',
   src:'2026阅读', sent:'Slow travel is emerging as a defining trend.',
   note:'◆考纲拓展词'},
  {w:'in conclusion', ph:'', def:'phr.总之',
   src:'写作高频', sent:'In conclusion, I firmly believe that...',
   note:'议论文结尾万能句'}
];

/* ---------- 六、构词法练习题 ---------- */
const MORPH_QUIZ = [
  {stem:'proud', want:'副词', ans:['proudly'], hint:'修饰动词用副词', why:'形容词加 -ly 变副词'},
  {stem:'develop', want:'名词', ans:['development'], hint:'加 -ment', why:'动词加 -ment 变名词'},
  {stem:'happy', want:'名词', ans:['happiness'], hint:'y 改 i 加 -ness', why:'形容词加 -ness 变抽象名词'},
  {stem:'care', want:'形容词(有…的)', ans:['careful'], hint:'加 -ful', why:'名词加 -ful 表"充满"'},
  {stem:'care', want:'形容词(没有…的)', ans:['careless'], hint:'加 -less', why:'名词加 -less 表"缺乏"'},
  {stem:'possible', want:'否定形式', ans:['impossible'], hint:'p 前用 im-', why:'im- 用于 m/p/b 开头的词'},
  {stem:'regular', want:'否定形式', ans:['irregular'], hint:'r 前用 ir-', why:'ir- 用于 r 开头的词'},
  {stem:'decide', want:'名词', ans:['decision'], hint:'de 结尾改 sion', why:'-de 结尾的动词变名词常用 -sion'},
  {stem:'able', want:'名词', ans:['ability'], hint:'改 -ity', why:'形容词加 -ity 变名词'},
  {stem:'strong', want:'名词', ans:['strength'], hint:'变元音加 th', why:'不规则变化，必须记'},
  {stem:'true', want:'副词', ans:['truly'], hint:'去 e 加 ly', why:'true→truly 是特殊变化'},
  {stem:'terrible', want:'副词', ans:['terribly'], hint:'-le 去 e 加 y', why:'-le 结尾的形容词变副词去 e 加 y'},
  {stem:'relax', want:'形容词(修饰人)', ans:['relaxed'], hint:'用 -ed', why:'-ed 修饰人的感受'},
  {stem:'relax', want:'形容词(修饰物)', ans:['relaxing'], hint:'用 -ing', why:'-ing 修饰引起感受的事物'},
  {stem:'act', want:'形容词', ans:['active'], hint:'加 -ive', why:'动词加 -ive 变形容词'},
  {stem:'wide', want:'动词', ans:['widen'], hint:'加 -n', why:'形容词加 -en 变动词'},
  {stem:'real', want:'动词', ans:['realize','realise'], hint:'加 -ize/-ise', why:'加 -ize 表"使…化"'},
  {stem:'danger', want:'形容词', ans:['dangerous'], hint:'加 -ous', why:'名词加 -ous 变形容词'},
  {stem:'science', want:'人', ans:['scientist'], hint:'加 -ist', why:'-ist 表示从事某职业的人'},
  {stem:'good', want:'比较级', ans:['better'], hint:'不规则', why:'good-better-best 必须背'}
];
